### ISSUE TITLE
Connecting behind corporate proxy with username and password

### ISSUE THREAD

**Issue by PiPauwels** [irssi/irssi#1028]
My setup: 
- Irssi with enabled (password protected) IrssiProxy at my home computer
- Work computer behind a corporate HTTP proxy, requiring username and password.
- IrssiProxy is working: I can connect to it from my cellphone, and from my work computer, using a web based IRC client (Kiwi IRC).

The problem: I've setup Irssi on my work computer, from which I'm trying to connect to my IrssiProxy at home. I've setup the proxy as described in the docs, and with the solution proposed in question #339 by @ailin-nemui. My proxy setup is as follows:
```
proxy_address = dmzproxy005.dcn.qet.intra
proxy_password =
proxy_port = 8080
proxy_string = CONNECT %s:%d HTTP/1.0
Proxy-Authorization: QkFhUSERNAMEAwMPASSWORDBpcA


proxy_string_after = conn %s %d
use_proxy = ON
```
The ```proxy_string``` was set using this expression (with the ```Proxy-Authorization``` part being the base64 code containing the username and password of my corporate proxy):
```
/EVAL SET proxy_string CONNECT %s:%d HTTP/1.1\nProxy-Authorization: QkFhUSERNAMEAwMPASSWORDBpcA\n\n
```
The authentication on my corporate proxy server seems to work, because when I'm trying to connect my Irssi client at work to my IrssiProxy at home, it says:
```
-!- Irssi: Looking up matrix.foo.com
-!- Irssi: Connecting to matrix.foo.com [10.7.19.13] port 63061
-!- Irssi: Connection to matrix.foo.com established
-!- HTTP/1.1 200 Connection Established
-!- Proxy-Agent: IWSS
-!- Date: Thu, 28 Mar 2019 15:04:35 GMT
```
On the side of my IrssiProxy, it's clear that my Irssi at work got through the corporate proxy:
```
-!- Irssi: Proxy: New client ::ffff:191.191.119.90:27729 on port 63061
-!- Irssi: Proxy: Client ::ffff:191.191.119.90:27729 disconnected
```
... the only problem being: immediately after connecting to the IrssiProxy, the client disconnects. I can't seem to figure out what's going on here... I must be missing something in my proxy settings from Irssi on my work computer.

If I connect my work computer to another network (without proxy), and disable the proxy with ```/set use_proxy OFF``` it's working just fine...

**Comment by ailin-nemui** [comment]
can you `/connect -rawlog rawlog.txt yournet` and show that file? I'm not sure if it contains any useful output. could it be possible that your corporate proxy simply disconnects the connection shortly after a few messages are exchanged?

**Comment by PiPauwels** [comment]
```
<< CONNECT matrix.foo.com:63061 HTTP/1.0
Proxy-Authorization: QkFhUSERNAMEAwMPASSWORDBpcA


<< CAP LS
<< PASS <irssiproxy password>
<< NICK pipauwels
<< USER pipauwels pipauwels matrix.foo.com :pipauwels
<<
>> HTTP/1.1 200 Connection Established
>> Proxy-Agent: IWSS
>> Date: Fri, 29 Mar 2019 09:28:48 GMT
>>
```

Should the messages CAP LS / PASS / NICK / USER not be sent àfter the "Connection established" message? If it would be the corporate proxy that's disconnecting... should it then not do the same thing in Kiwi IRC (which connects just fine through the proxy). BTW, this is an exerpt from the rawlog of Kiwi IRC:

```
[C] CAP LS 302
[C] PASS <irssiproxy password>
[C] NICK pipauwels
[C] USER pipauwels 0 * https://kiwiirc.com/
```

Maybe I could try connecting with a desktop IRC application, to see if that works...

**Comment by ailin-nemui** [comment]
where is the kiwiirc running? kiwiirc is connecting to your irssiproxy (or any other network) from the server where kiwiirc is running, *not* from your corporate proxy
