### ISSUE TITLE
Improve SSL Documentation

### ISSUE THREAD

**Issue by blackthornedk** [irssi/irssi#1029]
Since #207 was done, the documentation on https://irssi.org/documentation/help/server/ was only partially updated, and https://irssi.org/documentation/settings/ doesn't mention ssl_* or tls_* at all.

Also it was not clear to me, that tls_verify is not enabled by default. What does that mean? Were no certificate checks done at all on my connections, before now?

**Comment by ailin-nemui** [comment]
> Also it was not clear to me, that tls_verify is not enabled by default. What does that mean? Were no certificate checks done at all on my connections, before now?

indeed

by the way you can get involved and submit a PR with updated docs :-)

**Comment by blackthornedk** [comment]
> by the way you can get involved and submit a PR with updated docs :-)

I already sent in https://github.com/irssi/irssi/pull/1030 but I don' t know where the website docs are located.

**Comment by blackthornedk** [comment]
Updated with https://github.com/irssi/irssi.github.io/pull/63
But I have no idea how to fix https://irssi.org/documentation/settings/
I'm a bit confused about the servers / server sections of the last file.

**Comment by ailin-nemui** [comment]
Cool! Please have a look at the comment on top of https://github.com/irssi/irssi.github.io/blob/ef6f263ff09eb663bf563c81dbe0bdface8edb9b/documentation/help/server.markdown

The change has to be submitted to https://github.com/irssi/irssi/blob/master/src/fe-common/irc/fe-irc-server.c instead!

What's wrong about the settings docs? I think there are no TLS related settings other than https://irssi.org/documentation/settings/#tls_verbose_connect

**Comment by blackthornedk** [comment]
> Cool! Please have a look at the comment on top of https://github.com/irssi/irssi.github.io/blob/ef6f263ff09eb663bf563c81dbe0bdface8edb9b/documentation/help/server.markdown
> 
> The change has to be submitted to https://github.com/irssi/irssi/blob/master/src/fe-common/irc/fe-irc-server.c instead!

OK, I updated #1030 instead. 
So no changes are needed to the other repository, for the website to be updated?

> What's wrong about the settings docs? I think there are no TLS related settings other than https://irssi.org/documentation/settings/#tls_verbose_connect

I think I misunderstood the purpose of 'settings'. I read them as a definition file for the .irssi/config file, and not as general purpose settings. As I read over them again, I suspect it to be a definition of the various settings used by the /SET command?

**Comment by ailin-nemui** [comment]
Nice!

>  So no changes are needed to the other repository, for the website to be updated?

The website help is generated from a script (https://github.com/irssi/irssi.github.io/blob/master/_tools/Help2md.md)

> I suspect it to be a definition of the various settings used by the /SET command?

Indeed

**Comment by ailin-nemui** [comment]
did you solve this issue or is there something left to do @blackthornedk ?

**Comment by blackthornedk** [comment]
It looks like we're as close as can be.
