### ISSUE TITLE
"Statusbar doesn't exist: X", even though it does

### ISSUE THREAD

**Issue by mozbhearsum** [irssi/irssi#1033]
After upgrading from 1.1.1 to 1.2.0 I noticed this error whenever I started irssi or loaded my config:
```
07:55 -!- Irssi: Statusbar doesn't exist: wl0
```

However, this statusbar clearly _does_ exist, as it has info:
```
07:55 Statusbar: wl0
07:55 Type     : root
07:55 Placement: top
07:55 Position : 0
07:55 Visible  : always
07:55 Items    : Name                                Priority  Alignment
07:55          : barstar                             100       left
07:55          : wlstat0                             0         left
07:55          : barend                              100       right
```

The bar itself changed in appearence after the upgrade as well, which makes me wonder if is not being fully loaded or configured. Here is the configuration section:
```
    wl0 = {
      placement = "top";
      items = {
        barstar = { priority = "100"; };
        wlstat0 = { };
        barend = { priority = "100"; alignment = "right"; };
      };
    };
```

This bar intended to be used by [wlstat.pl](https://github.com/f4cket/irssi/blob/master/wlstat.pl), which hasn't seen an update in ages, so another possibility could be that it has stopped working correctly with irssi, I suppose.

**Comment by ailin-nemui** [comment]
Try adv_windowlist.pl instead

**Comment by dequis** [comment]
Not sure this is invalid tbh. We changed the syntax of /statusbar completely, see https://irssi.org/documentation/help/statusbar/, but we still claim "The old syntax is still accepted for backward compatibility, but no longer documented.". That might not be quite true.

**Comment by ailin-nemui** [comment]
@dequis we still support the old syntax but that doesn't mean we stay silent on mistakes anymore. /statusbar x reset complains now

**Comment by mozbhearsum** [comment]
I migrated to adv_windowlist.pl, as recommended. For anyone else wishing to do so, here's some config stuff to make it look like wlstat.pl:
In ~/.irss/config:
```
settings = {
  "perl/core/scripts" = {
    awl_shared_sbar = "OFF";
    awl_viewer = "no";
    awl_display_key = "[$N]$H$C$S";
    awl_placement = "top";
    awl_block = "99";
    awl_display_header = "";
  };
};
```

In ~/.irssi/default.theme (or wherever your theme is):
```
formats = {
  "Irssi::Script::adv_windowlist" = {
    awl_display_nokey = "[$N]${cumode}$H$C$S";
    awl_display_key = "[$N]${cumode}$H$C$S";
    awl_display_header = "";
    awl_display_nokey_visible = "[$N]${cumode}$H$C$S";
    awl_display_key_visible = "[$N]${cumode}$H$C$S";
    awl_display_nokey_active = "[$N]${cumode}$H$C$S";
    awl_display_key_active = "[$N]${cumode}$H$C$S";
  };
};
```
