### ISSUE TITLE
resolve_reverse_lookup can cause cert verification failure

### ISSUE THREAD

**Issue by tomaw** [irssi/irssi#1034]
When this is enabled cert CN verification is done to the name in the PTR which can cause failures. It probably adds MITM potential.

**Comment by jjakob** [comment]
Can confirm, causes error "None of the Subject Alt Names in the certificate match hostname [ipv6 address]". Turning off resolve_reverse_lookup fixes it.

**Comment by horgh** [comment]
The option was added in 5b60b859d45feaa5504a196d77a5a4a318130493. It replaces the server name with what we found from the IP's reverse DNS: https://github.com/irssi/irssi/blob/master/src/core/servers.c#L307-L310.

That is a strange thing to do. The history doesn't include the motivation. I'm inclined to remove the option to solve this. I don't understand why we'd ever want to prefer the PTR record.
