### ISSUE TITLE
/SAVE fails in Solaris 10 "Invalid argument"

### ISSUE THREAD

**Issue by zvainio** [irssi/irssi#1042]
For some reason Solaris 10 does not accept NULL as a parameter.  I remembered that this was an issue while ago with GNU screen also

ERRORS
     The realpath() function will fail if:

     EINVAL          Either the file_name or resolved_name  argument is a null pointer.

src/lib-config/write.c

	/* expand all symlinks; else we may replace a symlink with a regular file */
	dest_name = realpath(base_name, NULL);

It was fixed with this

	char realbuf[PATH_MAX];
	dest_name = realpath(base_name, realbuf);

After this I'm able to use /SAVE command again

**Comment by ailin-nemui** [comment]
:-(

**Comment by ailin-nemui** [comment]
would this work?

```
diff --git a/src/lib-config/write.c b/src/lib-config/write.c
index b8ef6156..5dbbd1ed 100644
--- a/src/lib-config/write.c
+++ b/src/lib-config/write.c
@@ -315,6 +315,15 @@ int config_write(CONFIG_REC *rec, const char *fname, int create_mode)
 	/* expand all symlinks; else we may replace a symlink with a regular file */
 	dest_name = realpath(base_name, NULL);
 
+	if (errno == EINVAL) {
+		/* variable path length not supported by glibc < 2.3, Solaris < 11 */
+		char resolved_path[PATH_MAX] = { 0 };
+		errno = 0;
+		if ((dest_name = realpath(base_name, resolved_path)) != NULL) {
+			dest_name = g_strdup(dest_name);
+		}
+	}
+
 	if (dest_name == NULL) {
 		if (errno == ENOENT) {
 			dest_name = g_strdup(base_name);
```

**Comment by zvainio** [comment]
That code change works fine for me.
