### ISSUE TITLE
Document Irssi::get_irssi_dir()

### ISSUE THREAD

**Issue by ashafer01** [irssi/irssi#1051]
I can't seem to find a canonical way to find the value passed to `--home`, and it seems most scripts use `$ENV{HOME}/.irssi` which of course may or may not correspond to `--home`.

Is there already a way to get the `--home` path? If not, can one be added, preferably normalized to an absolute path?

**Comment by dwfreed** [comment]
Irssi::get_irssi_dir(), which is unfortunately not documented in perl.txt.  This will return the absolute path of what was provided to --home, or the builtin default.  Note that the path is not canonicalized (so any path element could be a symlink).

**Comment by ashafer01** [comment]
Perfect, thanks!

Will leave this open to track adding to docs. If no one else grabs it I may submit a PR later on.
