### ISSUE TITLE
irssi warning ssl handshake failed wrong version number

### ISSUE THREAD

**Issue by kaminsky9444** [irssi/irssi#1056]
Hello, 

I use Irssi with Tor, and i am often disconnected from Freenode with this message : 

irssi warning ssl handshake failed wrong version number.

Here is the output of the strace when the problem occurs : 

https://termbin.com/w9va.

Irssi version : irssi 1.2.0 (20190211 1805).
Tor version : 0.2.9.16-1.
OpenSSL version : 1.1.0j-1~deb9u1.

Thanks you.

**Comment by ailin-nemui** [comment]
can see your `/server list `

**Comment by kaminsky9444** [comment]
06/16/19 10:48:26 Server               Port  Network    Settings
06/16/19 10:48:26 irc.dal.net          6667  DALnet     
06/16/19 10:48:26 irc.efnet.org        6667  EFNet      
06/16/19 10:48:26 irc.esper.net        6667  EsperNet   
06/16/19 10:48:26 irc.gamesurge.net    6667  GameSurge  
06/16/19 10:48:26 eu.irc6.net          6667  IRCnet     
06/16/19 10:48:26 open.ircnet.net      6667  IRCnet     
06/16/19 10:48:26 irc.ircsource.net    6667  IRCSource  
06/16/19 10:48:26 irc.netfuze.net      6667  NetFuze    
06/16/19 10:48:26 irc.oftc.net         6667  OFTC       
06/16/19 10:48:26 irc.quakenet.org     6667  QuakeNet   
06/16/19 10:48:26 irc.rizon.net        6667  Rizon      
06/16/19 10:48:26 irc.undernet.org     6667  Undernet   
06/16/19 10:48:26 10.8.0.9             7000  Freenode   tls, tls_cert: ~/.irssi/certs/FreenodeTor.pem

**Comment by kaminsky9444** [comment]
https://ibb.co/DrfqwZ9

**Comment by ailin-nemui** [comment]
is this only on automated reconnect? or on /connect? anything noticeable about its regularity?

**Comment by kaminsky9444** [comment]
I have this message on /connect, and also after a few days on freenode, no, nothing to report on its regularity.

**Comment by kaminsky9444** [comment]
You have no solution (i think).

**Comment by ailin-nemui** [comment]
I have no idea

**Comment by kaminsky9444** [comment]
Ok, I leave the ticket open, if a person has an idea.. .

Thanks you.

**Comment by ailin-nemui** [comment]
I don't understand enough of tor, but did you try using the onion address instead of 10.8.0.9? how do you "fix" the problem? do you need to restart irssi, or does it suffice to /(re)connect again?

**Comment by kaminsky9444** [comment]
Yes, I tried it with the .onion and the problem persists. I solve the error using the /reconnect command or relaunching Irssi.

**Comment by abitfan** [comment]
I have not verified this to be the case but I would think this is normal and expected
behavior. Tor circuits are not guaranteed to remain open so anytime someone restarts
a relay that is used to build the route from you to freenode's .onion the connection
will break.

**Comment by kaminsky9444** [comment]
I also note, that I never go beyond 3 days, without having this error. 
Why 3 days?, and no more?.
Thanks you.

**Comment by kaminsky9444** [comment]
I have this error, when I am disconnected (after a few days, maximum three days) : warning SSL read error: server closed connection unexpectedly.

Thanks you.

**Comment by kaminsky9444** [comment]
https://github.com/matrix-org/matrix-ircd/issues/35 ?.

**Comment by kaminsky9444** [comment]
https://github.com/freenode/ircd-seven/issues/169#issuecomment-504071924

**Comment by foxiepaws** [comment]
In my testing, This issue seems to have to do with various different SSL versions. I had this happening constantly after building with a newer version of OpenSSL, not just with irssi but also with my IRCd. 

I'm not completely sure what causes it but after rebuilding/reinstalling everything to use a more modern version of OpenSSL, this went away.

**Comment by diizzyy** [comment]
This occurs on reconnect if you mix SSL servers with non SSL-servers.

```
servers = (
  {
    address = "irc.nordunet.se";
    chatnet = "EFNet";
    port = "6697";
    use_tls = "yes";
    tls_verify = "no";
  },
  {
    address = "efnet.portlane.se";
    chatnet = "EFNet";
    port = "6669";
    use_ssl = "no";
    ssl_verify = "no";
  }
);
```
