### ISSUE TITLE
meson.build not working (Meson 0.37)

### ISSUE THREAD

**Issue by vague666** [irssi/irssi#1066]
With the latest HEAD after #1065 was merged

vague@irssi:~/irssi$ meson Build -Denable-true-color=yes --prefix=$PWD
The Meson build system
Version: 0.37.1
Source dir: /home/vague/irssi
Build dir: /home/vague/irssi/Build
Build type: native build

Meson encountered an error in file meson.build, line 308, column 46:
Expecting rbracket got comma.

If I remove ", 'C:/'" from line 308 then I get a new error, looks like identifier 'in' is wrong
vague@irssi:~/irssi$ meson Build -Denable-true-color=yes --prefix=$PWD
The Meson build system
Version: 0.37.1
Source dir: /home/vague/irssi
Build dir: /home/vague/irssi/Build
Build type: native build

Meson encountered an error in file meson.build, line 310, column 32:
Expecting eol got id.

Is my meson too old or what's the matter?

**Comment by ailin-nemui** [comment]
it is, and in the older meson versions it didn't even support self-detecting that.

you can see the required version here
https://github.com/irssi/irssi/blob/84301a29f8c5ee9206a325f124e6040937071066/meson.build#L3
luckily you can just download the python source code and run meson.py there to test a newer meson release

Thanks for trying!

**Comment by dequis** [comment]
We should maybe add the meson version to the title of this issue

Also what distro?
