### ISSUE TITLE
proxy.txt is incomprehensive

### ISSUE THREAD

**Issue by AndrewMcSwain** [irssi/irssi#1143]
The documentation is instructing me to do the following: 

  cd src/irc/proxy

I would suggest including the proper path (in my system it's /usr/local/include/irssi/src/irc), or even just three dots and a slash. As a rather new gnu user this was non-trivial to figure out.

step two:
run make.
returns 'make: no target to make'

I don't know where to go from here, since I am unsure what I would even be compiling by running the command. Judging from the instructions this would be an alternative to recompiling, and here i am running make? 

Im on freebsd 12 and am using the binary provided and installed by pkg. Is my use case supported by this documentation? I think not. It would be worthy to at least specify the use cases your documentation covers in the documentation itself, lest someone do something like compile manually over the top of an installation pre-configured by a package manager, which could lead to depdency conflicts and so on for the user. 

thanks

**Comment by ailin-nemui** [comment]
thanks for the issue report, this file should be clarified. 

you should follow the first instructions, which suggest to compile irssi with `./configure --with-proxy`

either way this needs to be done when compiling irssi, for example in /home/andrew/unpacked-irssi-sources. in other words it is not possible to do this from /usr/local/include

depending on how you installed irssi in the first place (ports tree, package manager,...) there may be some other convention how to use the proxy. but that would be distribution dependent (out of the hands of irssi developers)

**Comment by ailin-nemui** [comment]
did you try `make config` in the port
