### ISSUE TITLE
 warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]

### ISSUE THREAD

**Issue by ekollof** [irssi/irssi#1144]
Hi,

This pops up several times when building irssi with a recent glib. Maybe this should be looked at.

Relevant: https://tecnocode.co.uk/2019/08/24/gtimeval-deprecation-in-glib-2-61-2/

**Comment by ailin-nemui** [comment]
@ekollof can you test #1145 ?
