### ISSUE TITLE
Are nicknames in Cyrillic supported?

### ISSUE THREAD

**Issue by pnedkov** [irssi/irssi#1157]
Does irssi support nicknames in Cyrillic?

In messages and channel topics Cyrillic letters are shown correctly, but nicknames in Cyrillic are shown as rectangles. Also, attempting to change your nickname using the `/nick` command with a nickname that contains Cyrillic letters throws the following error: `Erroneous Nickname`

`
 core = {
    recode_fallback = "CP1251";
    recode_out_default_charset = "UTF8";
    recode_transliterate = "no";
    recode_autodetect_utf8 = "yes";
    recode = "yes";
  };
`

WeeChat for example has no problem displaying nicknames in Cyrillic.

**Comment by ailin-nemui** [comment]
if the server and nicknames are utf-8 then it should work... recode support is incomplete afaik, see #55

**Comment by pnedkov** [comment]
When I connect to the irc server I see this:
`CASEMAPPING=bulgarian-WINDOWS1251-charlink`

This leads me to believe that the irc server is using CP1251/WINDOWS1251 encoding for everything.
