### ISSUE TITLE
Problem with expanding backslash \\

### ISSUE THREAD

**Issue by kayvax** [irssi/irssi#1168]
When you try to use comand that is saved in config file, for example:
say "\\\test" 
does not expand to \test
It only works if text is in single quotes in config file:
say '\\\test'

**Comment by ailin-nemui** [comment]
```
/alias t1 say "\\test"
"\test"
/alias t1 say '\\test'
'\test'
```
works for me

**Comment by kayvax** [comment]
This is what adding with alias looks like when saved to config:
`t1 = "say '\\\\test'";
t2 = "say \"\\\\test\"";`

When you manualy add 
`t1 say "\\test"`
to config and reload from irssi it will not work

**Comment by ailin-nemui** [comment]
uh... don't do it?
