### ISSUE TITLE
meson says our minimum version is wrong

### ISSUE THREAD

**Issue by dequis** [irssi/irssi#1185]
And also that the same reason that's wrong is a deprecated feature?

```
WARNING: Project specifies a minimum meson_version '>= 0.47.0' but uses features which were added in newer versions:
 * 0.50.0: {'install arg in configure_file'}
WARNING: Deprecated features used:
 * 0.50.0: {'install arg in configure_file'}
```

```
$ meson --version
0.54.0
```

**Comment by ailin-nemui** [comment]
I think meson is moving too fast. not sure if we can't just disregard this warning with the benefit that the build remains working on both versions of meson

**Comment by ailin-nemui** [comment]
btw oddly I dont get the warning, how did you make it print the warning?

**Comment by dequis** [comment]
Dunno. Command used:

```
meson build -Dstatic-dependency=yes -Dinstall-glib=force -Dwith-fuzzer=yes -Dfuzzer-link-language=cpp
```

**Comment by ailin-nemui** [comment]
ah, I think the warning you see is actually from GLib 2.58.3's meson.build :-)

**Comment by dequis** [comment]
Oh, lol. Nevermind then.
