### ISSUE TITLE
Compile problem - undefined functions

### ISSUE THREAD

**Issue by timeisflowing** [irssi/irssi#1186]
I tried branch 86b72d5829935f81410ccc9ae724c7c9d4b39cfa

make[3]: Entering directory '/home/z00/irssi/src/fe-text'
  CCLD     irssi
/usr/bin/ld: irssi.o: in function `textui_finish_init':
/home/z00/irssi/src/fe-text/irssi.c:174: undefined reference to `textbuffer_formats_init'
/usr/bin/ld: irssi.o: in function `textui_deinit':
/home/z00/irssi/src/fe-text/irssi.c:263: undefined reference to `textbuffer_formats_deinit'
/usr/bin/ld: textbuffer.o: in function `textbuffer_remove':
/home/z00/irssi/src/fe-text/textbuffer.c:202: undefined reference to `textbuffer_format_rec_free'
/usr/bin/ld: textbuffer.o: in function `textbuffer_remove_all_lines':
/home/z00/irssi/src/fe-text/textbuffer.c:216: undefined reference to `textbuffer_format_rec_free'
/usr/bin/ld: textbuffer.o: in function `textbuffer_destroy':
/home/z00/irssi/src/fe-text/textbuffer.c:57: undefined reference to `textbuffer_format_rec_free'
/usr/bin/ld: textbuffer.o: in function `textbuffer_line2text':
/home/z00/irssi/src/fe-text/textbuffer.c:237: undefined reference to `textbuffer_line_get_text'
/usr/bin/ld: textbuffer-view.o: in function `view_update_line_cache':
/home/z00/irssi/src/fe-text/textbuffer-view.c:275: undefined reference to `textbuffer_line_get_text'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:551: irssi] Error 1
make[3]: Leaving directory '/home/z00/irssi/src/fe-text'
make[2]: *** [Makefile:460: all-recursive] Error 1
make[2]: Leaving directory '/home/z00/irssi/src'
make[1]: *** [Makefile:579: all-recursive] Error 1
make[1]: Leaving directory '/home/z00/irssi'

I think you forgot to add oldname it after the last change you made. ?

**Comment by ailin-nemui** [comment]
if this is an old check out, did you run autoreconf/re-run autogen?

**Comment by timeisflowing** [comment]
> if this is an old check out, did you run autoreconf/re-run autogen?

Yes I make distcleaned and reconfigure compile problem this result.

**Comment by timeisflowing** [comment]
> if this is an old check out, did you run autoreconf/re-run autogen?

İ pulled use latest checkout

**Comment by ailin-nemui** [comment]
please try a fresh check out

**Comment by timeisflowing** [comment]
> please try a fresh check out

Yeahh good working, problem solved thank you! :D
