### ISSUE TITLE
Support numeric 489 as ERR_SECUREONLYCHAN

### ISSUE THREAD

**Issue by mh-source** [irssi/irssi#1193]
This was already discussed shortly on IRC with @ailin-nemui - and per his request i open this issue on it.

Numeric 489 is currently defined only as ERR_VOICENEEDED in Irssi but is used as an error reply (ERR_SECUREONLYCHAN) for non-secure clients trying to join a secure-only channel on several networks.

Right now 489 will be printed in the channel-window and then (with setting autoclose_windows = on) promptly lost with the closed window. It should probably go to the status-window instead/too, as it does with ban, inviteonly, etc.

For reference:
see 489 (and 480) at https://defs.ircdocs.horse/defs/numerics.html
see 489 at https://github.com/ircd-hybrid/ircd-hybrid/blob/master/src/numeric.c

The mode used for this differs between networks, if you are interested in that rabbithole see: https://github.com/ircv3/ircv3-ideas/issues/45 and https://github.com/ircv3/ircv3-ideas/issues/46

Perhaps it would be best to support a "free text" style numeric. but thats just IMHO and without having looked into how numerics are implemented in Irssi: ":%s 489 %s :%s"

**Comment by falsovsky** [comment]
This problem also affects me with ircd-hybrid.

**Comment by mh-source** [comment]
@falsovsky and/or anybody else who might be interested. I made a quick and dirty scripted fix for use in my own testing. while we wait... :-)

[mh_secureonlychan_489.pl.txt](https://github.com/irssi/irssi/files/4622730/mh_secureonlychan_489.pl.txt)

**Comment by falsovsky** [comment]
Thank you, I'm still @ work. But later in the day I'll test and report.

**Comment by falsovsky** [comment]
@mh-source It works!

**Comment by mh-source** [comment]
_If_ this code gets approved (at some point) I am wondering about putting the secureonlychan script on Irssi-scripts so people who might be forced/prefer to use an older version of Irssi can still enjoy the wonderful world of secure only channels in their full glory. And adding a version check to the script, telling people if they don't need it. any opinions (for/against) this idea?

**Comment by mh-source** [comment]
With both a source-code fix in git and a fall-back solution in the form of a script available on irssi.org, i think this issue can be close. Thanks to everyone for your patience and support.
