### ISSUE TITLE
Do we really need to show the TERM?

### ISSUE THREAD

**Issue by klebertarcisio** [irssi/irssi#1215]
Hi everyone

I believe that there is an unnecessary exposure of system information in this case. In this case, we are presenting the user with system information that could be omitted.

What do you think about removing the **"% s"** code snippet from the line **583**?

CWE 497 says that cases like these can be avoided.
https://cwe.mitre.org/data/definitions/497.html

https://github.com/irssi/irssi/blob/f8052b7f571a0d1b54b722890fc15d988921f2b5/src/fe-text/terminfo-core.c#L576-L585

**Comment by ailin-nemui** [comment]
and why would you want to hide it?

**Comment by klebertarcisio** [comment]
No @ailin-nemui, thanks for the replay.

Does the user need to know this information? If the user needs it, ok. Perfect. However, if the user does not need it, I think it would be better to remove it.

**Comment by klebertarcisio** [comment]
Hi @vague666 

I got your point. Thanks for the reply.

**Comment by klebertarcisio** [comment]
Hi @vague666 

I got your point. Thanks for the reply.
