### ISSUE TITLE
clipboard issue while scrolling up

### ISSUE THREAD

**Issue by nsklaus** [irssi/irssi#1216]
i'm seeing a weird issue on irssi, if i attempt to scroll up, i'm getting some character being pasted in the input area over and over as long as i keep scrolling.

this is the some remnants of a previous clipboard entry. but the weird thing is, those character are no longer in any of my clipboards as far as i can tell.
i tested with:
```
xclip -o -sel p
xclip -o -sel c
xclip -o -sel b
and 4 finger / middle click press
```
none of them shows the same string of chars i get pasted into irssi input area.
i recognize that string was something i copied/paste before. but despite not being any longer in my clipbaord, it's being pasted anyway. and also i do not understand why scrolling up action would trigger that. i have separate history buffer for each channel. but that issue manifest itself in any channel i try. 

i'm talking about two finger slide up / mouse wheel up action. 
i understand this, scroll up action,  is not working with irssi to actualy scroll up into the chat history.
but it may happen that i do this by mistake and habit from the browser and everywhere else where this scroll up works. in irssi, to perform that action i need to press page-up/page-down keys.
it's fine. but what is not is that performing that mistake prints a long string of repeatedly pasted chars in my input area.

this issue might be difficult to reproduce, because i tried to select / copy text and reproduce it without success. i do not know how actualy it happens, but it is not the first time i see it.

when i'll learn more about it, i'll update this issue with more info.

**Comment by vague666** [comment]
What happens if you add mouse.pl to your irssi?

**Comment by nsklaus** [comment]
i got the file mouse.pl, i moved it into ~/.irssi/scripts and tried to load it: 
```
/load mouse.pl

 19:50     * Error in script mouse:
 19:50  Your terminal doesn't seem to support this. at /home/klaus/.irssi/scripts/mouse.pl line 136.
```

my terminal is "st" (part of dwm suite of tools)

**Comment by dequis** [comment]
The default action for `/bind ^Y` is yank_from_cutbuffer, which is a weird way to say paste whatever was deleted last by another command (like `^W`, `^U`, `^K`, etc)

Your terminal sends ^E and ^Y on mouse scroll events when the mouse mode is not explicitly activated.

Regarding mouse.pl, either remove that check or add st to the regex in the previous line.

**Comment by nsklaus** [comment]
ah yes i confirm, if i type some stuff in irssi but decide to delete it with ctrl+u, this gets the issue reproducible at all times. so this is where those remnants came from. i see.. thank you for telling.
so what do i need to do to unbind this action "/bind ^Y  yank_from_cutbuffer" ?
