### ISSUE TITLE
Buffer of sprintf

### ISSUE THREAD

**Issue by klebertarcisio** [irssi/irssi#1217]
Hi everyone,

I used a static analysis tool and it reported:

This **'call to sprintf'** operation requires **54 bytes** but the destination is only **20 bytes**.

Can someone help me understand the result? Should this be improved?

https://github.com/irssi/irssi/blob/300cd14a705872df3245cb5235c3d7a84e178b7d/src/fe-text/term-terminfo.c#L320-L336

**Comment by dequis** [comment]
Hello.

```
$ python
Python 3.8.3 (default, May 17 2020, 18:15:42)
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 2**31
-2147483648
>>> '\033[%d8;2;%d;%d;%dm'.replace('%d', '-2147483648')
'\x1b[-21474836488;2;-2147483648;-2147483648;-2147483648m'
>>> len(_)
53
```

Your tool is not looking at the actual possible values and their types, only at the type of %d.

**Comment by klebertarcisio** [comment]
thanks!
