### ISSUE TITLE
Cannot connect to my IRC Server with Server Name, only with the IP and Port....

### ISSUE THREAD

**Issue by v8ive** [irssi/irssi#1218]
The server name is irc.8anon.net, but when i attempt to connect, I get this error...

Irssi: Looking up irc.8anon.net
Irssi: Unable to connect server irc.8anon.net port 6667 [Name or service not known]

Though when I use the IP and Port (Default 127.0.0.1 and 6667), it connects to my IRC Server....but with this error involved....

Irssi: Looking up 127.0.0.1
Irssi: Connecting to 127.0.0.1 [127.0.0.1] port 6667
Irssi: Connection to 127.0.0.1 established
!irc.8anon.net *** Looking up your hostname...
!irc.8anon.net *** Could not resolve your hostname: Request timed out; using your IP address (127.0.0.1) instead.

Any ideas to help???

**Comment by falsovsky** [comment]
First problem, the hostname doesnt exist;

Second problem, that message is from the server, and has nothing to do with irssi;

**Comment by vague666** [comment]
You could add the following to `/etc/hosts`
`127.0.0.1 irc.8anon.net`
or add irc.8anon.net to the existing localhost line, ie
`127.0.0.1 localhost irc.8anon.net`
And as falsovsky wrote, the message is from the server and it's not an error, it just tells you the server was unable to lookup your
hostname from the ip address (which might mean you don't have a `localhost` specified in `/etc/hosts`)

**Comment by vague666** [comment]
Closing issue since not an irssi issue
