### ISSUE TITLE
The stock `colorless` theme does not de-color the vertical window split bar

### ISSUE THREAD

**Issue by nachanon** [irssi/irssi#1220]
_This is a theme bug with no effect on Irssi's functionality._

I have recently been checking out Irssi's default-installed alternative `colorless` theme as an alternative to default theme. However, as soon as I applied it to my horizontally-split Irssi session; I found that the theme does not correctly (de)color the vertical window split bar; which starkly contrasted with the rest of window.

This is more-or-less trivial to fix (with caveat), pull request will follow.

### Exact Steps to Reproduce ###

1. Run `irssi --noconnect`
1. Issue command: `/set theme colorless`
1. Issue command: `/quit`
1. Run `irssi --noconnect`
1. Issue command: `/window new -right split`
1. Issue command: `/1`
1. You would see that vertical window split bar is not colorless, which is against the point of using `colorless` theme...
	
	![(Screenshot)](https://u.cubeupload.com/xwindows/jSkFjv.png)

### Side Notes ###

- My terminal's default foreground/background color combo is `#FFFCDA`/`#000000`.
- This is not the only problem I found in stock `colorless` theme, other notable one is the lack of messages' bold highlights in several places.

### System Information ###

Irssi: 1.2.2 (20190829 0225)  
System: Fedora 32 (GNU/Linux x86_64)

**Comment by ailin-nemui** [comment]
thanks for the issue report, this is an oversight. looking to your PR
