### ISSUE TITLE
Roadmap/plans of 1.2.3 / 1.3?

### ISSUE THREAD

**Issue by diizzyy** [irssi/irssi#1222]
It's almost been a year since last release and many bugs have been fixed etc, are there plans of a new release soon?

**Comment by ailin-nemui** [comment]
which bugs do you have in mind?

**Comment by diizzyy** [comment]
Mixing non SSL and SSL servers (reconnect doesn't work), glib patch would be nice to have integrated (not necessary however), PR 1167 for instance?

**Comment by ailin-nemui** [comment]
none of these seem critical -- 1, do not mix TLS+non-TLS, -- 2, patch it (it's linked on the download page), 3 -- it's very unlikely that anyone is affected by the issue (OpenBSD with Perl built as a module);  by the way it would be much easier if you'd actually link to the pull requests you are talking about. This is easy to do, just write # + number

if there is a 1.2.3, then the glib-patch would obviously be included

**Comment by diizzyy** [comment]
I'll keep that in mind, anyhow I guess that answers the question. Thanks!

**Comment by ailin-nemui** [comment]
1.2.3 has been released now
