### ISSUE TITLE
Compiling fails with capsicum enabled on FreeBSD 12.1 and 13-CURRENT using meson

### ISSUE THREAD

**Issue by diizzyy** [irssi/irssi#1223]
The check seems to be broken, however adjusting L480 in meson.build (https://github.com/irssi/irssi/blob/master/meson.build#L480) to ```nvlist_create_found = libnv.found() and cc.has_function('nvlist_create', dependencies : libnv)``` fixes it.

However the build fails shortly after with ```src/core/meson.build:10:2: ERROR: File fe-capsicum.c does not exist.```

Tested using git checkout hash 561619f

**Comment by ailin-nemui** [comment]
thanks for testing! 

can you try this https://github.com/irssi/irssi/compare/master...ailin-nemui:meson-capsicum

**Comment by diizzyy** [comment]
Works, thanks!
