### ISSUE TITLE
hilight does not respect -priority arg

### ISSUE THREAD

**Issue by balazser** [irssi/irssi#1228]
I have the following `hilight` configuration

```
 /hilight
...
19:34    3 ccc  -line -priority 20 -color %G -actcolor %g
19:34    4 ddd  -line -priority 1 -color %p -actcolor %p
19:34    5 fff  -line -priority 100 -color %k -actcolor %k
```

**Actual:**
After receiving a message containing all the matching words like `ccc ddd fff` the message always gets highlighted according to the first positional match in the config.

**Expected:**
highlight the message according to the `-priority` arg.

**Comment by vague666** [comment]
What do you mean by first positional match?
The order the words appear in the message?
So `fff ddd ccc` would hilight as black? (if I remember my format-codes correctly)

**Comment by balazser** [comment]
the order of the rules. for some reason, it prints green (the first rule).

It takes the first rule (this case `3 ccc  -line -priority 20 -color %G -actcolor %g` ) that matches and does not respect the priority. I would expect if one message contains text that matched by multiple rules then the highest one gets applied which in this case would be `5 fff  -line -priority 100 -color %k -actcolor %k`.

**Comment by vague666** [comment]
@balazser can you try this fix? https://github.com/irssi/irssi/compare/master...vague666:fix_1228.diff
It works for me :shrug:

**Comment by balazser** [comment]
thank you for the super quick fix @vague666 !  I fetched your branch and seems to work on my device. :fireworks:

**Comment by balazser** [comment]
just getting the following but not sure is this an issue:

```
19:12 -!- Irssi: Error in script hilightwin:
19:12 Version of perl module (20011234) doesn't match the version of Irssi library (20011246) at
          /usr/lib/perl5/5.32/site_perl/Irssi.pm line 166.
19:12 Compilation failed in require at (eval 18) line 1.
19:12 BEGIN failed--compilation aborted at (eval 18) line 1.

```

**Comment by vague666** [comment]
You have an older libperl_core.so somewhere, use
`locate libperl_core.so`
to locate all versions and move the old version out of the way
until you know everything works, then you can delete the file
