### ISSUE TITLE
all downloaded scripts got wiped; now (re)installed scripts work, but they don't actually exist within filesystem, only works for current session

### ISSUE THREAD

**Issue by dashishmeister** [irssi/irssi#1257]
OS: macOS Catalina 10.15.7 on 2020 Intel MBP 

So a few days ago I quit Terminal while still in a channel after running the /cubes command (I installed cubes.pl with scriptassist). The next time I opened Terminal and ran irssi, the /cubes command no longer worked. I went into the scripts folder and then I saw ALL of my installed scripts gone. only the defaults. So I ran scriptassist and installed cubes that way. It worked and /cubes worked, but it didn't appear on Finder. /exited session and then restarted, /cubes no longer worked. Installed it manually, still didn't work. Hopefully someone can help

**Comment by ailin-nemui** [comment]
I would try running this command in your terminal

```
ls -laR ~/.irssi
```

also try `/save` inside irssi and check where it saved the files -- it should print out a path

**Comment by vague666** [comment]
Finder might refresh on a timer so new files might not appear instantly, and did you /run or /script load the script after downloading it manually? scriptassist probably runs the script automatically when you install a new script
If you started irssi and the cubes.pl wasn't loaded you probably didn't symlink it to ~/.irssi/scripts/autorun or put the file there
More information is needed if things still don't work :)

**Comment by dashishmeister** [comment]
> I would try running this command in your terminal
> 
> ```
> ls -laR ~/.irssi
> ```
> 
> also try `/save` inside irssi and check where it saved the files -- it should print out a path

printout of terminal cmd

`drwx------   5 [redacted]  staff   160 Nov 27 16:58 .
drwxr-xr-x+ 30 [redacted]  staff   960 Jan 13 23:56 ..
-rw-r-----   1 [redacted]  staff  6791 Nov 27 15:41 config
-rw-r-----   1 [redacted]  staff  8495 Nov 26 18:33 default.theme
drwxr-xr-x   8 [redacted]  staff   256 Jan 13 13:24 scripts

/Users/[redacted]/.irssi/scripts:
total 72
drwxr-xr-x  8 [redacted]  staff    256 Jan 13 13:24 .
drwx------  5 [redacted]  staff    160 Nov 27 16:58 ..
drwxr-xr-x  5 [redacted]  staff    160 Nov 27 17:00 autorun
-rw-r--r--  1 [redacted]  staff   1154 Jan 13 13:24 cubes.pl
-rw-r--r--  1 [redacted]  staff  14017 Nov 27 16:59 dim_nicks.pl
-rw-r--r--  1 [redacted]  staff   7360 Nov 27 16:59 nickcolor.pl
-rw-r--r--  1 [redacted]  staff   6980 Nov 27 16:58 niq.pl
drwxr-xr-x  3 [redacted]  staff     96 Jan 13 13:24 old

/Users/[redacted]/.irssi/scripts/autorun:
total 0
drwxr-xr-x  5 [redacted]  staff  160 Nov 27 17:00 .
drwxr-xr-x  8 [redacted]  staff  256 Jan 13 13:24 ..
lrwxr-xr-x  1 [redacted]  staff   15 Nov 27 17:00 dim_nicks.pl -> ../dim_nicks.pl
lrwxr-xr-x  1 [redacted]  staff   15 Nov 27 17:00 nickcolor.pl -> ../nickcolor.pl
lrwxr-xr-x  1 [redacted]  staff    9 Nov 27 16:59 niq.pl -> ../niq.pl

/Users/[redacted]/.irssi/scripts/old:
total 8
drwxr-xr-x  3 [redacted]  staff    96 Jan 13 13:24 .
drwxr-xr-x  8 [redacted]  staff   256 Jan 13 13:24 ..
-rw-r--r--  1 [redacted]  staff  1154 Jan 13 13:22 cubes.pl.old`
I redacted my username because its my real name

**Comment by dashishmeister** [comment]
<img width="1340" alt="Screenshot 2021-01-14 at 09 51 07" src="https://user-images.githubusercontent.com/75739987/104566606-171ac400-564e-11eb-89da-b85fb88e0f4a.png">

ay yo now this is getting really wack

**Comment by dashishmeister** [comment]
wiped cache, still don't work

**Comment by vague666** [comment]
You are looking in the wrong place. scriptassist puts the scripts in your personal scripts folder, ie /Users/****/.irssi/scripts (although your name can be seen in the screenshot :P

**Comment by ailin-nemui** [comment]
Probably the "scripts" folder you have opened in finder, is NOT the one in /Users/****/.irssi/scripts but another folder that is also named "scripts"

**Comment by vague666** [comment]
We should add that when irssi is packaged on linux the scripts in the screenshot are usually installed to /usr/local/share/irssi/scripts
I would guess brew or however you installed irssi does the same on OSX

**Comment by dashishmeister** [comment]
> You are looking in the wrong place. scriptassist puts the scripts in your personal scripts folder, ie /Users/****/.irssi/scripts (although your name can be seen in the screenshot :P

I searched the whole machine, literally can't find any of them

**Comment by dashishmeister** [comment]
ill uninstall then reinstall and try again

**Comment by ailin-nemui** [comment]
try typing 

`open  /Users/****/.irssi/scripts`

in your terminal

**Comment by dashishmeister** [comment]
> try typing
> 
> `open /Users/****/.irssi/scripts`
> 
> in your terminal

found em
<img width="882" alt="Screenshot 2021-01-14 at 13 30 46" src="https://user-images.githubusercontent.com/75739987/104591292-c1094900-566c-11eb-9547-22cfab30b225.png">

**Comment by ailin-nemui** [comment]
congrats :+1:

**Comment by dashishmeister** [comment]
wait but why don't they pop up when I search in finder

**Comment by dashishmeister** [comment]
ill make a new issue for that

**Comment by vague666** [comment]
Probably because .files(.irssi is a hidden directory) are hidden, Finder probably has a setting to search for hidden files
