### ISSUE TITLE
header filename conflict in term.h

### ISSUE THREAD

**Issue by ailin-nemui** [irssi/irssi#1267]
The `src/fe-text/term.h` may conflict with `/usr/include/term.h` from XCurses.

~in my opinion the meson build should work, but @bsandro reported otherwise while investigating #1238~

The autotools build is currently prone to this issue, as it adds the current folder to `-I`. See #1268 for a fix

The easiest way would be to rename our term.h :/

**Comment by ailin-nemui** [comment]
@dequis @irssi/developers any thoughts?

**Comment by ailin-nemui** [comment]
this is when trying to `#include <term.h>` in order to use the right function declarations

**Comment by mistydemeo** [comment]
Looks like this was fixed by #1268 - can confirm that fixed the conflict for me in #1290.

**Comment by ailin-nemui** [comment]
fixed by #1268
