### ISSUE TITLE
Irssi only stores the parameter input for a line in history, not the theme formatting used to create it

### ISSUE THREAD

**Issue by trilkk** [irssi/irssi#1277]
This bug may also be a feature, or some sort of behavioural change, but it's something that started appearing on the latest irssi 1.3 in FreeBSD.

Previously (at least up until version 1.2), for a line in backlog and history, irssi stored the complete line up to and including the formatting used to create that line. This meant that plugins could capture signals and then use `^format` commands to change the outlook of any particular type of message before passing forward to later handlers. This formatting used would be stored in the history. This gave plugins incredible flexibility on altering the appearance of irssi.

This no longer works. Instead, irssi seems to store only the parameter input for the message lines, and then randomly recreate the lines later using a heuristic I do not completely understand. The lines remain up to a poiint, after which everything, including the history, is redrawn.

Why is this important? For example the old `nickcolor.pl` in `scripts.irssi.org` has stopped working: [nickcolor.pl](https://github.com/irssi/scripts.irssi.org/blob/master/scripts/nickcolor.pl)

There was a similar but more advanced script available in the internet at some point, but I fail to find it right now. Instead, here's an excerpt from my `colored_nicks.pl` I've been using for about 10 years:

```
sub nick_hash_public
{
    my ($server, $param1, $nick) = @_;
    my ($nick, $attr) = extract_attribution($nick);

    my $pad_long = create_padding($nick, $attr, 12);
    my $pad_short = create_padding($nick, $attr, 11);
    my $param_long = create_irssi_nick($nick, $attr, 12);
    my $param_short = create_irssi_nick($nick, $attr, 11);

    $server->command('/^format pubmsg ' . $param_long . '%K$2' .$pad_long . ' {msgtext $1}');
    $server->command('/^format pubmsg_channel ' . $param_long . '%K$3' . $pad_long . ' {msgchannel $1} {msgtext
 $2}');
    $server->command('/^format pubmsg_hilight ' . $param_short . '%K$3' . $pad_short . ' {msgtext_hilight $2}')
;
    $server->command('/^format pubmsg_hilight_channel ' . $param_short . '%K$4' . ' {msgchannel $2} {msgtext_hi
light $3}');
    $server->command('/^format pubmsg_me ' . $param_short . '%K$2' . $pad_short . ' {msgtext_notice $1}');
    $server->command('/^format pubmsg_me_channel ' . $param_short . '%K$3' . $pad_short . ' {msgchannel $1} {ms
gtext_notice $2}');
}

<...>

sub nick_hash_own_private
{
    my ($server, $param1, $nick) = @_;
    my ($nick, $attr) = extract_attribution($nick);

    my $pad_0 = create_padding($nick, $attr, 12);
    my $pad_2 = create_padding($server->{nick}, '', 12);
    my $param_0 = create_irssi_nick($nick, $attr, 12);
    my $param_2 = create_irssi_nick($server->{nick}, '', 12);
    $server->command('/^format own_msg_private ' . $pad_0 . $param_0 . ' {msgtext $1}');
    $server->command('/^format own_msg_private_query ' . $pad_2 . $param_2 . ' {msgtext $1}');
}

Irssi::signal_add_last('message public', 'nick_hash_public');
<...>
Irssi::signal_add_last('message own_private', 'nick_hash_own_private');
```

This script used the formatting to:
* Embed nick coloring into the formatting for every line.
* Color both the nicknames of others and the speaker.
* Use different nickname truncation for hilight messages and regular messages.

I've now modified the script by embedding the colorization into the nickname parameter passed forward from the signal. This is a less powerful method than using formatting directly. Here's why:
* The nickname parameter passed in privmsgs cannot be altered, as they are used for identification in queries and/or direct private messages.
  * => Nicknames in private messages to the user cannot be colorized.
* Nickname of the user is not a parameter in the signal - it could only be colorized by acquiring the nickname from the `$server` struct.
  * => Nickname of the user cannot be colorized in private messages.
* In the signal function, it's impossible to know if the message is going to be hilighted.
  * => Nicknames in public messages cannot have different truncation of nickname length as compared to regular messages in the channel. 
* The regular irssi color codes such as `%g` or `%X54` cannot be passed in the nick parameter and be parsed later.
  * => Colorization is limited to so-called "mIRC colors" that can be embedded into the parameter with `C-c`.

And many similar problems of course. There's a high likelihood of this being what is called a stupid user error, but I'd really like to recreate the theme I've been using for more than a decade There's a few things that could help:
* Extra parameter(s) that can be embedded to the signal that I can use in the theme instead of the regular `$0 - $4` or so.
* Ability to force storing of the format for each line.

Also, I'm relatively certain I cannot be the only one with this issue. There used to be a myriad of scripts using some kind of string hash to colorize and differentiate nicknames. At this point I'm open for anything, really.

**Comment by vague666** [comment]
There is no irssi 1.3 yet. The freebsd packager has made a mistake by releasing a git version before a official release

**Comment by vague666** [comment]
This is probably the PR that breaks some scripts, https://github.com/irssi/irssi/pull/1079 if you want to read about it

**Comment by ailin-nemui** [comment]
also see #1189

**Comment by ailin-nemui** [comment]
I recommend you port your script to use expandos, these will give you a way to add a variable to your /format without having to constantly change the format. That method should remain working with a future Irssi 1.3 release

**Comment by trilkk** [comment]
Thanks you for the explanation. The PRs linked do indeed seem to invalidate the `^format` approach, so a modern way is required.

However, reading [Appendix B: Special Variables and Expandos](https://irssi.org/documentation/settings/#a_b), I don't really understand how to use an expando to execute arbitrary perl code for the parameter, which is required to calculate a hash over it and alter the output to include colorization and/or calculate the required amount of padding.

Would really appreciate a link to an example script.

**Comment by ailin-nemui** [comment]
you can check the nickcolor_expando or the nm2 scripts

**Comment by trilkk** [comment]
Thank you for the tip, was able to modernize my script. Might as well make it public:
[https://github.com/trilkk/irssi-colored-nicks](https://github.com/trilkk/irssi-colored-nicks)

Closing.

**Comment by ailin-nemui** [comment]
hi @trilkk  You can soon replace the `create_color_command_code` with Irssi::format_string_expand, see https://github.com/irssi/irssi/pull/1285
