### ISSUE TITLE
sometimes wrong/useless path set for perl_use_lib

### ISSUE THREAD

**Issue by TheDreamer** [irssi/irssi#132]
And, after much trial and error....its because in 1.70 it switched from List::Util to List::AllUtils and wanting the 'any' method.  Which exists in List::Util, providing its new enough....either from using Perl 5.20 or having Scalar-List-Utils installed.

The problem is on systems where the latter is being done.

Scalar-List-Utils installs a List::Util in SITEARCH to override the base version in ARCH.  And site_perl paths normally come before the base paths in @INC.

However, with irssi, the configure figures out what the INSTALLARCHLIB path is and promotes that to being searched first.  Which causes the older List::Util to get loaded and eventually break things like 'twirssi'. (unable to determine local time zone)

The explanation I gleaned is that its trying to determine where Irssi.pm is going to get installed and making that come first.  Problem is that Irssi.pm goes under INSTALLSITEARCH, which by default is first...

While the work around is to use '/set perl_use_lib ...', it might be nice this wasn't needed or required so much hair pulling....

**Comment by ailin-nemui** [comment]
The configure.ac already has the basic set-up for this, but because cras was fighting with some Perl 5.6 issues I guess this wasn't resolved properly. In a running irssi, **if** your irssi libraries already are in Perl's default search path, you can safely `/set -clear perl_use_lib` and restart to resolve this issue. Maybe it would be possible to extend `configure.ac` in such a way that PERL_USE_LIB is unset if the value calculated by MakeMaker results in a path already in the `@INC` perl sees when run without any `PERL*OPTS` (there is a related `perl_set_use_lib` variable in the configure script)

**Comment by ailin-nemui** [comment]
@TheDreamer  how did you install irssi?

**Comment by ailin-nemui** [comment]
please reopen if you can provide info

**Comment by gedge** [comment]
I am suffering from this problem, on the FreeBSD port of irssi 0.8.19, see http://www.freshports.org/irc/irssi/
- irssi moved a lib in my `@INC` to before `site_perl`
- causing my local versions of modules to be ignored, so modules fail (I'm using http://github.com/zigdon/twirssi)

Symptom:

```[11:06:13] List::Util version 1.45 required--this is only version 1.38 at /usr/local/lib/perl5/site_perl/mach/5.20/Moose/Exporter.pm line 9.
[11:06:13] BEGIN failed--compilation aborted at /usr/local/lib/perl5/site_perl/mach/5.20/Moose/Exporter.pm line 9.```

In irssi:

`@INC` looks like this:
```shell
/script exec use Data::Dumper; print Dumper @INC
[16:02:41] $VAR1 = '/home/gedge/.irssi/scripts';
[16:02:41] $VAR2 = '/usr/local/share/irssi/scripts';
[16:02:41] $VAR3 = '/usr/local/lib/perl5/5.20/mach';
[16:02:41] $VAR4 = '/usr/local/lib/perl5/site_perl/mach/5.20';
[16:02:41] $VAR5 = '/usr/local/lib/perl5/site_perl';
[16:02:41] $VAR6 = '/usr/local/lib/perl5/5.20';
[16:02:41] $VAR7 = '/usr/local/lib/perl5/site_perl/5.20/amd64-freebsd-thread-multi';
[16:02:41] $VAR8 = '/usr/local/lib/perl5/site_perl/5.20';
[16:02:41] $VAR9 = '/usr/local/lib/perl5/site_perl/5.20/mach';
[16:02:41] $VAR10 = '.';
```

The offending line is indicated by VAR3 above, which seems to have been move up, relative to:

```shell
% perl -V
...
  @INC:
    /usr/local/lib/perl5/site_perl/mach/5.20
    /usr/local/lib/perl5/site_perl
    /usr/local/lib/perl5/5.20/mach
    /usr/local/lib/perl5/5.20
    /usr/local/lib/perl5/site_perl/5.20/amd64-freebsd-thread-multi
    /usr/local/lib/perl5/site_perl/5.20
    /usr/local/lib/perl5/site_perl/5.20/mach
    .
```

Happy to help debug more.

**Comment by gedge** [comment]
I put `unset perl_use_lib` into `~/.irssi/startup` and this seems to fix it.  It was `perl_use_lib = /usr/local/lib/perl5/5.20/mach` by default

**Comment by ailin-nemui** [comment]
Can you confirm this issue with a fresh config?

**Comment by gedge** [comment]
@ailin-nemui - I can confirm that (using `irssi --home=newdir`)

**Comment by gedge** [comment]
dropping the FreeBSD port's `configure` option `--with-perl-lib=site` solves the problem, getting:
```shell
21:28 $VAR1 = '/home/gedge/.irssi-test2/scripts';
21:28 $VAR2 = '/usr/local/share/irssi/scripts';
21:28 $VAR3 = '/usr/local/lib/perl5/amd64-freebsd-thread-multi';
21:28 $VAR4 = '/usr/local/lib/perl5/site_perl/mach/5.20';
21:28 $VAR5 = '/usr/local/lib/perl5/site_perl';
21:28 $VAR6 = '/usr/local/lib/perl5/5.20/mach';
21:28 $VAR7 = '/usr/local/lib/perl5/5.20';
21:28 $VAR8 = '/usr/local/lib/perl5/site_perl/5.20/amd64-freebsd-thread-multi';
21:28 $VAR9 = '/usr/local/lib/perl5/site_perl/5.20';
21:28 $VAR10 = '/usr/local/lib/perl5/site_perl/5.20/mach';
21:28 $VAR11 = '.';
```

**Comment by gedge** [comment]
the last part of the output of `./configure --with-perl-lib=site ...` has this line
    `Perl library directory ........... : /usr/local/lib/perl5/5.20/mach`

whereas, without that option to `configure`, we see the below (all other summary lines are the same):

```
Perl library directory ........... : /usr/local/lib/perl5/amd64-freebsd-thread-multi
  - NOTE: This was automatically set to the same directory you gave with
  --prefix. If you want the perl libraries to install to their 'correct'
  path, you'll need to give --with-perl-lib=site option to configure.
  Anyway, installing perl to this directory should work just as well.
```

**Comment by ailin-nemui** [comment]
Hi @gedge, can you evaluate the proposed PR? I attach a configure script for your convenience
[configure.txt](https://github.com/irssi/irssi/files/255273/configure.txt) (you need to rename and chmod it)

**Comment by gedge** [comment]
worked also with `-s` (option to `make`) - looks good

**Comment by eevee** [comment]
FYI, I just this problem for the _first_ time after upgrading to Arch Linux's 0.8.20 package — my `perl_use_lib` (which I've never touched) is `/usr/lib/perl5/core_perl`, which puts `core_perl` _before_ `vendor_perl`, which makes the core `List::Util` override the (later) CPAN-installed `List::Util`, which makes Moose fail to load, which makes twirssi fail to load.

**Comment by ailin-nemui** [comment]
Unfortunate. Can you try the git version? Also, is perl_use_lib explicit in your .irssi/config?
