### ISSUE TITLE
Perl library upgrade on macOS 11.4 (20F71)

### ISSUE THREAD

**Issue by tolsadus** [irssi/irssi#1323]
Irssi installed with brew version 1.2.3
Since the recent upgrade 11.4 (20F71) it seems that some system library has been changed in **/System/Library/Perl/**

The latest version used is 5.30 that doesn't seem compatible with irssi

```
sh-3.2# pwd
/System/Library/Perl
sh-3.2# ls -la
total 0
drwxr-xr-x    5 root  wheel   160 Jan  1  2020 .
drwxr-xr-x  134 root  wheel  4288 Jan  1  2020 ..
drwxr-xr-x  130 root  wheel  4160 Jan  1  2020 5.18
drwxr-xr-x  128 root  wheel  4096 Jan  1  2020 5.30
drwxr-xr-x    4 root  wheel   128 Jan  1  2020 Extras

sh-3.2# irssi
dyld: Library not loaded: /System/Library/Perl/5.28/darwin-thread-multi-2level/CORE/libperl.dylib
  Referenced from: /usr/local/bin/irssi
  Reason: image not found
[1]    7901 abort      irssi

```

Is anything required to force irssi to load the 5.30 instead of trying to find a non-existent 5.28 ?

**Comment by vague666** [comment]
Did you recompile irssi against the new perl?

**Comment by jimmysjolund** [comment]
I have the same issue. Installed Perl with `brew install perl` and then `brew install irssi`, and when trying to run irssi same error message as above. It looks for 5.28 but 5.30 is installed.

**Comment by tolsadus** [comment]
> Did you recompile irssi against the new perl?

Hm not really, I've just installed irssi with `brew install irssi` as @jimmysjolund stated.

**Comment by rprimus** [comment]
Fri May 28 08:38:55 BST 2021

This has been resolved.  See: https://github.com/Homebrew/discussions/discussions/1557

**Comment by jimmysjolund** [comment]
Yes, the update works on my machine now.

**Comment by tolsadus** [comment]
Works here, thanks a lot!
