### ISSUE TITLE
Status bar corruption in urxvt

### ISSUE THREAD

**Issue by ballerburg9005** [irssi/irssi#1334]
As seen in the screenshot, the blue status bar is not blue all the way. In this place the text also doesn't clear, which you notice if you switch channels. If you e.g. switch from a long channel name to a shorter one,  it leaves the "Act" and possibly "Lag" info text from the previous channel in place, and just partially overdraws it with the info from the new channel. The old info appears shifted to the right by as many characters as the channel names differ. Please look at the screenshot:

![corruption](https://user-images.githubusercontent.com/50874674/122833601-8aa3ba00-d2ed-11eb-997f-68b4d3187a2c.jpg)

To make certain the issue occurs in Urxvt only, I tried several other terminal emulators such as gnome-terminal and xterm. I also used "env -i bash" to undo all environment variables, I cleared my .Xdefaults (also via xrdb) and I used a clean ~/.irssi directory. 

I think I noticed this bug first several years ago. But I don't use IRC that often anymore, so I never looked into it. It is annoying and confusing though if the "Act" info is not cleared.

Archlinux 
community/rxvt-unicode 9.26-2
local/irssi-git 1.3.dev.r495.ge31d42b3-1

**Comment by vague666** [comment]
What does your TERM say?
`/eval echo $TERM`
Is this inside tmux or screen?
Also, see this https://github.com/irssi/irssi/issues/753

**Comment by ballerburg9005** [comment]
TERM=xterm
no tmux or screen

**Comment by ballerburg9005** [comment]
> Also, see this #753

This seems to be the problem!

TERM=rxvt-unicode fixes it. I hope that doesn't break other things.

Thanks!

**Comment by vague666** [comment]
If you use tmux or screen you should let them handle TERM, so you shouldn't set it yourself in that case

**Comment by vague666** [comment]
Didn't see the answer above :)
