### ISSUE TITLE
Noob Problem - Configuring IRSSI to access a .onion IRC server

### ISSUE THREAD

**Issue by gmdavis19724** [irssi/irssi#1356]
I've managed to be able to create an IRC server that is hosted on a .onion site. I have been able to use HEXCHAT to log into my IRC server with no problem. I would like to use IRSSI but have not been able to so far. Has anyone used IRSSI to connect to a .onion IRC server? If so can you please advise settings you utilized to achieve it. Thus far, every instance I've tried has been via virtual machines.

**Comment by vague666** [comment]
See if this helps:
irssi[bot] │ vague: tor is https://www.funtoo.org/Irssi_over_tor and/or https://github.com/rofl0r/proxychains-ng
You should use proxychains-ng to connect to tor, it's known to work best. Haven't checked the funtoo wiki so
don't know what it is about

**Comment by gmdavis19724** [comment]
thank you.
