### ISSUE TITLE
Monospace formatting character is visible

### ISSUE THREAD

**Issue by awfulcooking** [irssi/irssi#1370]
I'm trying to use the monospace formatting character so I can still enjoy ASCII art and bar charts while preferring to see chat in a variable width font.

But the character (\x11) displays as a box in irssi, making some users complain :-)

Could irssi skip rendering this character, so we can have cake and eat it?

Regards

https://modern.ircdocs.horse/formatting.html#monospace

**Comment by ailin-nemui** [comment]
> This character is a relatively new addition, and was defined by IRCCloud.

:)

**Comment by awfulcooking** [comment]
> > This character is a relatively new addition, and was defined by IRCCloud.
> 
> :)

\<grawity> remind irssi that they felt it necessary to support _blink_ as a formatting character
