### ISSUE TITLE
Apply human readable formatting to datetime string in banlist

### ISSUE THREAD

**Issue by tommyrot** [irssi/irssi#1451]
RPL_BANLIST (367), which format is described [here](https://modern.ircdocs.horse/#rplbanlist-367), is currently displayed in irssi like:

```
20:30 -!- 6 - #irssi: ban *!*asdsda@182.1.16.* [by helium.libera.chat, 16035635 secs ago]
```

It would be helpful if the timestamp was formatted in a human readable form, as is already the case for e.g. RPL_CREATIONTIME (329) [link](https://modern.ircdocs.horse/#rplcreationtime-329), and RPL_TOPICWHOTIME (333) [link](https://modern.ircdocs.horse/#rpltopicwhotime-333).

Example:
```
20:30 -!- Channel #irssi created Wed May 19 15:51:06 2021
```
and
```
20:30 -!- Topic set by Nei [] [Mon Oct 31 08:28:50 2022]
```

**Comment by dwfreed** [comment]
This has been fixed by #1457
