### ISSUE TITLE
IRSSI does not handle IRC colors only setting a background

### ISSUE THREAD

**Issue by acidvegas** [irssi/irssi#1472]
When parsing colored message, most clients (weechat & others) can parse color codes only setting a background (^C,5)

Here is an example of what I mean: https://i.imgur.com/mokL3cI.png 

This is the [acid ansi](https://github.com/ircart/ircart/blob/master/ircart/ansi/acid.txt) art.

Keep pumps on IRSSI please

**Comment by dwfreed** [comment]
From [the mIRC docs](https://www.mirc.com/colors.html):

> To specify a background color, a foreground color has to be given. So a ^C,8 attribute is not valid and thus ignored.

Since colors were originally specified by mIRC, and mIRC forbids specifying background color only, I don't feel this is an irssi issue.
