### ISSUE TITLE
No NICK/USER after CAP LS

### ISSUE THREAD

**Issue by ircnet-com** [irssi/irssi#1496]
https://ircv3.net/specs/extensions/capability-negotiation.html
```
Upon connecting to the IRC server, clients SHOULD send one of the following messages:
* CAP LS [version] to discover the available capabilities on the server.
* CAP REQ to blindly request a particular set of capabilities.
Following this, the client MUST send the standard NICK and USER IRC commands.
```

I have followed this description and expect NICK/USER after CAP LS/REQ. However, the newest versions of irssi send AUTHENTICATE first.

irssi 1.5+1-dev-177-gf0437566-dirty (20230912 1500)
```
> CAP LS 302
> JOIN :
< :irc.localhost CAP * LS :sasl extended-join 
< :irc.localhost 451 * :You have not registered
> CAP REQ :sasl extended-join
< :irc.localhost CAP * ACK :sasl extended-join 
> AUTHENTICATE PLAIN
```

irssi 1.2.2-1ubuntu1.1 (20190829 0225)
```
> CAP LS.
> NICK patrick.
> USER patrick patrick localhost :patrick
< :irc.localhost 020 * :Please wait while we process your connection..
< :irc.localhost CAP * LS :sasl extended-join 
> CAP REQ :sasl
< :irc.localhost CAP patrick ACK :sasl 
> AUTHENTICATE PLAIN
```

Currently these users get disconnected. Can you tell me which irssi versions are affected and if you are going to fix it?

**Comment by spb** [comment]
If we're taking the strictest possible reading of the spec: it says that the client MUST send NICK and USER at some point after CAP LS. It does *not* say that the client MUST NOT send any other commands in between, nor does it say 'immediately following'.

I agree that the intention of the spec is probably that clients send CAP LS, NICK, USER and then decide whether cap negotiation is supported based on whether the next response is `CAP * LS` or `001`, but I don't agree that the wording of the specification supports disconnecting clients that have found another way to make that decision. As with most things in IRC, the specs aren't as rigorous as they could be and require a bit of flexibility in allowing other clients or servers their interpretations.

**Comment by spb** [comment]
I would further note that if we take the interpretation that nothing else is permitted between CAP LS and NICK/USER, then it would not be possible to use a server password while also attempting to negotiate capabilities.

**Comment by ircnet-com** [comment]
The issue is that I do not have `sptr->user` allocated and no unique identifier assigned to the user before he sends USER.

I have tested the implementation with all irc clients I found so far, this is the first one having problems now. Anyway, I will find a solution.

**Comment by ircnet-com** [comment]
Closed
