### ISSUE TITLE
freenode extbans don't work in /ban

### ISSUE THREAD

**Issue by mauke** [irssi/irssi#150]
On freenode you can use ban masks like `$a:foo` (to ban the account `foo`) or `$r:*bar*` (to ban any realnames containing `bar`). See http://freenode.net/using_the_network.shtml .

irssi doesn't like those: you can't use `/ban $a:foo`. Instead you have to resort to `/mode +b $a:foo`. This is because irssi thinks a ban mask without `!` in it must be a nick, and as `$a:foo` isn't a nick in the channel, irssi silently ignores it.

I propose solving this by extending the check for `!` to also accept something as-is if it starts with `$`.

    src/irc/core/bans.c, ban_get_masks():
            if (**ban == '$' || strchr(*ban, '!') != NULL) {

**Comment by incognico** [comment]
Is it a good idea to only allow this behavior when the server announces support for EXTBAN? Maybe even more dynamically by parsing the EXTBAN arguments?

**Comment by mauke** [comment]
Why bother? Normal nicks can't contain `$` and the alternative (i.e. the current behavior) is to silently do nothing, which I think is worse than just setting a ban.

**Comment by ahf** [comment]
@mauke up for making a PR? I can add this fix myself manually since it's so easy, but I really like to keep track on who's contributing to the project. Up for making the PR yourself? :-)

**Comment by dequis** [comment]
@ahf `git commit --author="name <email@address>"` (i usually have to stalk a bit to get a proper email address, most of the time it's just cloning one of the repos and copying it from `git log`)

**Comment by mauke** [comment]
I've created a pull request at https://github.com/irssi/irssi/pull/218. Does this look right?

**Comment by kaniini** [comment]
An important thing to consider is that Unreal uses `~` for their extban character.

**Comment by dequis** [comment]
Unreal docs: https://www.unrealircd.org/files/docs/unreal32docs.html#feature_bantypes

The most common of those seems to be `~q:*!*@blah.blah.com`, which works, just like the `~n` and `~j` examples because they have `!`

`~c`, `~r` and `~R` will need fixing just like freenode's workaround, I'm afraid.

Do we check for `~` **and** `$` or do we make something more generic?

**Comment by kaniini** [comment]
Unreal also has `~a:` which matches against the account name.

**Comment by ailin-nemui** [comment]
this PR already was merged
