### ISSUE TITLE
DCC SSEND

### ISSUE THREAD

**Issue by uwe-schwarz** [irssi/irssi#165]
Add secure DCC send. Instead of "CTCP DCC SEND" it uses "CTCP DCC SSEND" and the socket should be connected via SSL. kvIRC has this implemented (http://www.kvirc.net/doc/doc_dcc_connection.html)

**Comment by dequis** [comment]
So I decided to check what other clients implement this. My google results in order:

1. KVIrc docs, which mention it's their extension
2. This exact ticket
3. Post from 2012 in mirc.com forums with a mirc script that implements this
4. KVIrc again
5. KVIrc again
6. Polish wikipedia article
7. Eggdrop language file, but it's actually a C-style format string that says `%ssend` (a `%s` and a `send`)
8. KVIrc again
9. Post from 2008 in monkey-pirate.com about the UPP mirc script, which has a regex that is `\sSEND`
10. Post from 2002 in dslreports.com in thread titled "HELp With Mirc" which looks like they typoed `send` as `ssend`.

You get the idea.

@ahf, close this? If someone really wants it, write a script for it.

**Comment by dequis** [comment]
Closing as per my previous comment, since I can now close things.

Again, if someone really wants it, a script or patch can be written for it, and then we'll reconsider that (As I said, it *might* be useful against passive sniffing)

**Comment by ailin-nemui** [comment]
mentioned in chat: https://github.com/irssi/irssi/commit/d8eec70fb3a9aea28b6dc2519ac9ac274b68aef8

**Comment by jansohn** [comment]
> 
> 
> mentioned in chat: [d8eec70](https://github.com/irssi/irssi/commit/d8eec70fb3a9aea28b6dc2519ac9ac274b68aef8)

I'd be interested in this feature.

@dequis the mentioned commit seems like a patch or at least a good starting point for me. Would you reconsider opening this issue?

**Comment by dequis** [comment]
Are you interested in working on the code to make it clean and not a copypaste of the existing dcc code, and submitting a pull request? Otherwise reopening the issue won't change the situation much

**Comment by jansohn** [comment]
My C skills are pretty rusty (and were never really good). Is the existing code that bad?

**Comment by stefan1983** [comment]
So still no one there who's interested to clean and push the code?

**Comment by vague666** [comment]
@stefan1983 maybe you? :) The pool of people interested enough appears to be very small

**Comment by stefan1983** [comment]
I am no software engineer, so would not even know what to do :)
But as a user I would love to see the support if there is anyone willing to
insert the code.

**Comment by stefan1983** [comment]
Is anyone able to provide me a pre-combiled binary / test version for debian 10?
