### ISSUE TITLE
Several segmentation faults

### ISSUE THREAD

**Issue by fser** [irssi/irssi#167]
I sometimes experiment segfault from irssi, but I can't figure out any scenario to reproduce the behaviour.
I'm using irssi 0.8.15 (20100403 1617) under debian 7 and have the following plugins:
 - adv_windowlist.pl (v0.8b2)
 - hilightwin.pl (v0.01 2002-03-04T22:47+0100)
 - rainbow.pl (v1.4)
 - go2.pl (v1.0 2008-02-22)
 - xmpp (vers ?)

I have two coredump (but they contain password so I don't want to make them public). Those coredump were produced thanks to ulimit -c unlimited, irssi is the debian packaged version. I **didn't** recompile it with debug flags or anything.

**Comment by ailin-nemui** [comment]
@fser any update here?

**Comment by fser** [comment]
@ailin-nemui no updates, I'm using the last version of both irssi and xmpp-irssi (at least the last version at that time) and I get no errors.
It was a matter with debian's package's version then.

**Comment by dequis** [comment]
Neat.
