### ISSUE TITLE
-botcmd only works on small channels

### ISSUE THREAD

**Issue by madduck** [irssi/irssi#175]
It's my understanding that `autosendcmd` (`-botcmd`) only works on channels with less than 1,000 users. The reason seems to be that it runs when receiving the output of `/who` and that call seems to be skipped when the channel has a large number of users for obvious reasons.

Could this be made configurable?

Alternatively, maybe there'd be an easy way to enable running of command after `/join` that are not dependent on `/who` results?

**Comment by ailin-nemui** [comment]
@madduck are you interested in evaluating the fix proposed by LemonBoy

**Comment by madduck** [comment]
also sprach ailin-nemui <notifications@github.com> [2016-01-20 04:01 +1300]:
> @madduck are you interested in evaluating the fix proposed by LemonBoy

Sorry, I have not seen the fix… until now. I just left a comment and
will gladly try the patch next week when back at my desk.

Best regards,

-- 
The sender e-mail address used (reply.github.com@pobox.madduck.net)
is valid and specific to our correspondence. It should not indicate any
affiliation with your organisation.
 
Die verwendete E-mail-Adresse (reply.github.com@pobox.madduck.net)
ist gültig und spezifisch für unsere Korrespondenz. Sie soll in keiner Weise
auf eine Verbindung mit Ihrer Organisation hindeuten.
 
Spamtrap: reply.github.com.bogus@pobox.madduck.net

**Comment by madduck** [comment]
I tried the fix and it works. Thanks!

**Comment by ailin-nemui** [comment]
closing via #399
