### ISSUE TITLE
Lots of warning using Clang's static analyzer

### ISSUE THREAD

**Issue by antoinealb** [irssi/irssi#180]
Hello,
Today I tried building Irssi using Clang's static analyzer and it reported 19 warnings (Arch Linux 64bits). I don't know what is this project's policy regarding warning free compilation ? Also I don't know what is the best way to report/fix such issues ? Maybe opening a pull request just to remove a dead assignment feels a bit like overkill.

For those willing to reproduce the static analyzer build, here is how to do it : 

```sh
scan-build ./autogen.sh # Maybe we should add debug flags here
scan-build make
scan-view scan-view /tmp/scan-build-* # Path will be given by previous command
```

**Comment by ailin-nemui** [comment]
closing for now, @antoinealb please report individual issues if you find them
