### ISSUE TITLE
Make it possible for Homebrew to build with Perl support enabled again

### ISSUE THREAD

**Issue by ahf** [irssi/irssi#184]
Let's help them fix this correctly instead of just disabling Perl support in a client where everyone depends upon Perl support...

See: https://github.com/Homebrew/homebrew/issues/34685

**Comment by dequis** [comment]
@ahf seems like they fixed this on their side, close this?

**Comment by DomT4** [comment]
Should have been fixed in https://github.com/Homebrew/homebrew/commit/299739ade9f56d71bdf7ddd45d388ba21d283204.

**Comment by ahf** [comment]
Cool, thanks @DomT4

**Comment by ahf** [comment]
and @dequis :-)
