### ISSUE TITLE
Make using certfp easier

### ISSUE THREAD

**Issue by Mikaela** [irssi/irssi#188]
If I read instructions from [freenode] and [OFTC] correctly, irssi requires you to remove the network and add it again. Another alternative is to edit config file by hand.

[freenode]:https://freenode.net/certfp/certfp-irssi.shtml
[OFTC]:http://www.oftc.net/NickServ/CertFP/#irssi

This makes encouraging people to use CertFP more difficult and it appears to be the only reliable identification method as SASL (#4) isn't supported.

With WeeChat I would use either of the two commands:

* `/set irc.server_default.ssl_cert %h/Mikaela.pem`
    * for all networks
* `/set irc.server.freenode.ssl_cert %h/Mikaela.pem`
    * only for network freenode.

`%h` gets expanded to WeeChat home (config directory) that is usually `~/.weechat/`

**Comment by dequis** [comment]
Closing since this is a problem with the freenode/oftc instructions (which are likely copy-pasted from each other)
