### ISSUE TITLE
server != null checks failing on DCC in disconnected state

### ISSUE THREAD

**Issue by ranieuwe** [irssi/irssi#193]
When you get a DCC msg over a network that you are disconnected from you get the following message:

```Irssi: critical ignore_check: assertion `server != NULL' failed```

Steps to reproduce:
- Connect to a network or server
- Establish a DCC chat (e.g. with Eggdrop)
- Disconnect from network or server
- Send a message to the DCC chat

And the errors appear.

Version is Irssi 0.8.18-head (20141027)

Command to reproduce is (without network configuration or anything): 

```/server ssl.irc.atw-inter.net 6697```

**Comment by ailin-nemui** [comment]
@LemonBoy I can easily reproduce this, just open 2 irssis, /dcc chat someone and disconnect the IRC server
