### ISSUE TITLE
Initial CTCP Action of an query goes into the status window. 

### ISSUE THREAD

**Issue by KindOne-** [irssi/irssi#194]
```Irssi 0.8.18-head (20141216) - http://irssi.org/``` Inside cygwin  (can also replicate in Ubuntu 14.10)

Not quite sure how to describe this, if someone sends me an ```/me ....``` and I do not have a query window with them,  that ```/me ....``` will get placed into the status window and irssi will also open a blank query window with that person.

```/query EvilOne_```
```/me stabes EvilOne_```

![irssi](https://cloud.githubusercontent.com/assets/732655/5591401/a7ba5096-9126-11e4-980e-7517e78fcd3c.PNG)

**Comment by FreeFull** [comment]
The exact same bug happens to me.

**Comment by ailin-nemui** [comment]
thanks for the bug report, this is a regression of 1edfcedda1105d79fa6b92d77a8fb60f296abe1e @dequis

**Comment by dequis** [comment]
oops.

**Comment by ahf** [comment]
Fixed in #204 - thanks!
