### ISSUE TITLE
Merge irssi-otr into the tree

### ISSUE THREAD

**Issue by wilhelmy** [irssi/irssi#196]
Having OTR support in-tree would be nice to have because end-to-end encryption is becoming increasingly important.

**Comment by ahf** [comment]
This is already being worked on outside of the primary repository.

**Comment by wilhelmy** [comment]
Awesome <3
Happy new year!

**Comment by ahf** [comment]
Happy new year to you too. The clean-up work is taking place in the ahf-hax branch at https://github.com/ahf/irssi-otr

**Comment by thejustaguy** [comment]
I agree with wilhelmy, having a stable irssi-otr as part of irssi core is important.

**Comment by ahf** [comment]
This is already being worked on.

**Comment by wilhelmy** [comment]
On Mon, Mar 16, 2015 at 04:56:46 -0700, Alexander Færøy wrote:
> This is already being worked on.

Hm, just curious, what's the status, and can I help somehow? (testing etc.)

**Comment by WouterSioen** [comment]
Any news on this?

**Comment by WouterSioen** [comment]
Any news on this?

**Comment by ahf** [comment]
No. 0.8.18 needs to be out first, then the TLS fixes must go in, then I'll get back to looking at this :-)

**Comment by jvoisin** [comment]
`0.8.20` is out, any news about this?

**Comment by ahf** [comment]
Let's start getting some eyes on this. I've just rebased the `ahf/otr` branch. @dequis - this is a big change, are you up for reviewing it or how do you think we should go on about this? Should I just make a PR with the branch?

**Comment by micah** [comment]
merge it ;)

**Comment by wilhelmy** [comment]
Bump. is there any way I can help?

**Comment by ahf** [comment]
Just brought the OTR statusbar back to life in the ahf/otr branch here.

**Comment by wilhelmy** [comment]
Thanks to everybody involved! :+1:
