### ISSUE TITLE
Close multiple irssi windows with one command

### ISSUE THREAD

**Issue by Xemanth** [irssi/irssi#198]
Command /window close needs multiple windows closing.

For example after chat attack (attacker opens 100 queries) and user needs to close all these windows without a sweat...

Command: /window close 10-110
Expected result : queries windows 10-110 gets closed
Current result: command doesn't do anything

**Comment by dgl** [comment]
Actually there is support for this, but `-` is a separator doesn't work; using `/window close 10 110` works as you desire. Supporting `-` as a separator seems worthwhile.
