### ISSUE TITLE
Subject Alt Names only matches one level deep

### ISSUE THREAD

**Issue by Sp1l** [irssi/irssi#200]
When connecting with chat.eu.freenode.net I get the warning

> warning None of the Subject Alt Names in the certificate match hostname 'chat.eu.freenode.net'

and the connection is dropped when ssl_verify is "yes"
When connecting chat.freenode.net the connection is established without problems
The servers return a certificate with 

> /OU=Domain Control Validated/OU=Gandi Standard Wildcard SSL/CN=*.freenode.net

And these should match 'chat.eu.freenode.net' without problem

**Comment by ailin-nemui** [comment]
See http://en.wikipedia.org/wiki/Wildcard_certificate#cite_ref-2

**Comment by Sp1l** [comment]
So sorry... Then I should raise this with Freenode instead.

**Comment by ahf** [comment]
Remind them about DNSSEC and DANE support! :+1:
