### ISSUE TITLE
Perl Staticlib, warns "signal still has 3 references" on exit 

### ISSUE THREAD

**Issue by ysangkok** [irssi/irssi#201]
Irssi version: 0.8.17.
Perl version: 5.21.7.
Glib version: 2.43.2.

Configure line template:

    LD_LIBRARY_PATH=$HOME/glib-build/lib/ PKG_CONFIG_PATH=$HOME/glib-build/lib/pkgconfig ./configure --prefix=$HOME/irssi-build2

Adding `--with-perl-staticlib` works great (including modules it seems. At least I can load `splitlong`), but if I load a module, then I get this on Irssi exit:

```
GLib warning: signal_free(script destroyed) : signal still has 3 references:
GLib warning:  - module 'perl/core' function 0x4c9980
GLib warning:  - module 'perl/core' function 0x4be900
GLib warning:  - module 'perl/core' function 0x4b6a00
```

Without flags or with `--with-perl-lib=vendor` or with`--with-perl-lib=module` I don't get any problems.

**Comment by ailin-nemui** [comment]
@ysangkok  does that happen regardless of script loaded? did you mean "load a script" or "load a module"?

**Comment by ysangkok** [comment]
@ailin-nemui I mean "load a script". It happens even if I only load [null.pl](https://raw.githubusercontent.com/irssi/scripts.irssi.org/gh-pages/scripts/null.pl).

I am having the same problem with master and glib 2.40.2 and Perl 5.18.2.

**Comment by ailin-nemui** [comment]
ah, thank you. I could reproduce your issue

**Comment by ailin-nemui** [comment]
can you evaluate whether the linked patch fixes your issue? seems to work for me

**Comment by ysangkok** [comment]
@ailin-nemui Yeah, that works, the warnings are gone. Thanks!
