### ISSUE TITLE
Counter for number of ignored messages

### ISSUE THREAD

**Issue by maxnordlund** [irssi/irssi#203]
First let me thank you for this program, it is quite amazing. But I would like to be able to see how many messages has been ignored, perhaps since the last unignored message or a total since coming online.

I would like to know if something is happening, without having to suffer through a flood of spammy messages. It could be added to the channel info displayed just above the input area. I don't think it would be to hard to implement, but I don't know C enough to try to make myself.

What do you think?

**Comment by ahf** [comment]
I think this can be implemented as a Perl script, which would be a lot better than putting it into our core.

**Comment by maxnordlund** [comment]
Probably, but I know even less Perl then C.
