### ISSUE TITLE
Is there a way to disable the multiline paste confirm message?

### ISSUE THREAD

**Issue by fourq** [irssi/irssi#205]
I'd like to either hook into irssi and replace the multipasting with a gist script, or just disable it so I can make a script to handle this. What would be my best approach?

**Comment by GeertHauwaerts** [comment]
You can use `/SET paste_verify_line_count 0` to disable the warning message.

**Comment by fourq** [comment]
:+1:

**Comment by shqear93** [comment]
@GeertHauwaerts 
please explain how to use this configuration, I'm not a MobaXterm
Thank you

**Comment by ranoptimal** [comment]
@GeertHauwaerts 
This is not very useful...how exactly can a user do that?
It is a very annoying dialog.

**Comment by ranoptimal** [comment]
Since the above suggestion does not help, if anyone still needs help with this:
I found that in the MobaXterm.ini, there is a property called WarnBeforePasteMultipleLines.
just set it to 0, restart MobaXterm and you will never have to see that annoying dialog again :)
