### ISSUE TITLE
Clear functionality for /names

### ISSUE THREAD

**Issue by valberg** [irssi/irssi#209]
Sometimes it would be nice to be able to do `/names -clear` to remove all output made by `/names`. Similar to the `/lastlog -clear`.

**Comment by incognico** [comment]
You can use "/SCROLLBACK LEVELCLEAR -level <some level>" where <some level> is the desired level to clear. The /names output is probably CRAP or even NICKS. You need to figure out. "/HELP levels" shows a list of the available levels.

**Comment by valberg** [comment]
`/scrollback levelclear -level CLIENTCRAP` + `/scrollback levelclear -level CLIENTNOTICES` does it.

**Comment by ailin-nemui** [comment]
note that this will (potentially) clear more than the names. you can also try my [clearable](http://anti.teamidiot.de/static/nei/*/Code/Irssi/clearable.pl) script (`/clearable names`). To learn more about levels, the [linebuffer](http://anti.teamidiot.de/static/nei/*/Code/Irssi/linebuffer.pl) script may also be useful (`/dumplines -format -levels`)
