### ISSUE TITLE
Warn if the client certificate is expired

### ISSUE THREAD

**Issue by mineo** [irssi/irssi#211]
At the moment, using an expired client certificate to connect to an IRC server doesn't use the certificate (without a warning or anything) or uses it and the server ignores it. I've tested this on Rizon and I'm not sure which of the two it actually is, but I don't speak much C and OpenSSLs API, so I won't even try to make wild guesses :-) The only thing I've been able to figure out is that none of the checks in https://github.com/irssi/irssi/blob/8bd575df2ec0d4a17b6f59116d555b64f5bb1312/src/core/network-openssl.c#L487-L492 error out. It would be great if irssi would at least show a warning in this case or didn't try to establish a connection to the server at all.

**Comment by dequis** [comment]
Looked a bit into this, tried to find other openssl clients that used client certificates... and none seemed to verify the client certificate in any way. You probably don't want to do the default verification, anyway, since it's self-signed, and that makes it invalid.

```
$ openssl verify mynick.cert
mynick.cert: C = AU, ST = Some-State, O = Internet Widgits Pty Ltd
error 18 at 0 depth lookup:self signed certificate
C = AU, ST = Some-State, O = Internet Widgits Pty Ltd
error 10 at 0 depth lookup:certificate has expired
OK
```

I guess the correct solution is to load the certificate using the X509 openssl functions and manually check for expiration and nothing else.

Also, if it helps anyone, to get an expired cert, do this (set days to -1)

```
openssl req -nodes -newkey rsa:2048 -days -1 -x509 -keyout mynick.key -out mynick.cert
```

**Comment by dequis** [comment]
In #560 @Olathe provides some additional reasons to consider this:

> `SASL EXTERNAL` uses a certificate file to prove who I am to the IRC server. Unfortunately, certificate files can expire. When this happens, the only thing I see when connecting is an uninformative message from the server that SASL failed with no reason why.
> 
> Because this happens out of the blue after SASL has been working properly for weeks or months, it can be quite difficult or even impossible to identify the source of the problem. It would be nice if `irssi` gave an error message if the certificate file had expired.

**Comment by ailin-nemui** [comment]
@ahf any updates here?

**Comment by ahf** [comment]
Nope. Not something I've looked into as of now.

**Comment by ailin-nemui** [comment]
@mineo are you interested in testing this
