### ISSUE TITLE
DCC GET fails when saving to CIFS location

### ISSUE THREAD

**Issue by Revenent** [irssi/irssi#220]
If the download path (dcc_download_path) is set to a location that is mounted with the CIFS filesystem, the GET will fail with a busy error.

According to the bug report @ Debian (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=696963), this is due to temphandle in sig_dccget_connected (dcc-get.c) being left open while other operations are attempted against the file.

The Debian bug report has a patch written by Robert C Jensen at the bottom.

Hoping this gets in soon, since this would be really useful on a Raspberry Pi w/ a backing Windows machine as the NAS.

**Comment by dequis** [comment]
Also references http://bugs.irssi.org/index.php?do=details&task_id=867

Patch:

```diff
Description: Call close() on temporary file descriptor so we don't get ETXTBSY
 when dcc_download_path is an ntfs mount
Author: Robert C Jensen <jensen.r@husky.neu.edu>
--- a/src/irc/dcc/dcc-get.c
+++ b/src/irc/dcc/dcc-get.c
@@ -223,6 +223,8 @@
 		else
 			ret = fchmod(temphandle, dcc_file_create_mode);
 
+		close(temphandle);
+
 		if (ret != -1) {
 			ret = link(tempfname, dcc->file);
 
@@ -246,7 +248,6 @@
 
 		/* close/remove the temp file */
 		ret_errno = errno;
-		close(temphandle);
 		unlink(tempfname);
 		g_free(tempfname);
 
```

**Comment by GeertHauwaerts** [comment]
The patch is applied and FS#867 is closed as well.
