### ISSUE TITLE
Regression in /hilight, it beeps always now.

### ISSUE THREAD

**Issue by dequis** [irssi/irssi#227]
Already mentioned this one on irc but adding it here to not forget about it.

@weedy pointed out a regression with /hilight, which after upgrading to 0.8.17 always beeps.

He uses /hilight to color URLs, like this: `hilights = ( text = "http(s)?://[A-Za-z0-9_/&?=%.;~#)(+-]*"; color = "%G"; act_color = "%n"; )`

I did a bisect and got https://github.com/irssi/irssi/commit/6bbb114046f54a85bed6674011411d4d869ef2fb - that commit says "(It's still possible to use /hilight -actcolor %n to hide hilight/beep)", that doesn't seem to be working

@dgl's reply:

>07:45 < dg> dx: ah, yeah, i think someone else reported that and then i forgot to do a pull request for the fix :(
>07:45 < dg> on phone right now, will look in a bit

**Comment by ailin-nemui** [comment]
@dgl ping

**Comment by dequis** [comment]
Closing now that #233 is merged \o/
