### ISSUE TITLE
RFC: enhancement: native RobustIRC support

### ISSUE THREAD

**Issue by stapelberg** [irssi/irssi#231]
I’m one of the developers of http://robustirc.net/. See http://robustirc.net/docs.html for more details, but in a nutshell, it’s an IRC network written on top of https://raftconsensus.github.io/ which doesn’t suffer from netsplits. To not be affected by network issues between the client and the IRC servers, clients should use the RobustSession protocol which wraps IRC in a connection-independent HTTPS/JSON-based transport, see http://robustirc.net/docs/robustsession.html for details.

Currently, we offer a program called the RobustIRC bridge, which you can configure as a network/proxy server in irssi. The bridge then does the conversion (bridging) from IRC to IRC in RobustSession.

I intend to submit a pull request for irssi to talk RobustSession natively, i.e. without the bridge. Would such a pull request be accepted?

Thank you.

**Comment by ailin-nemui** [comment]
I wonder how feasible it would be to contain your connection in an external module instead, similar to the [ICB/SILC/Quassel](https://github.com/shabble/irssi-docs/wiki/Modules) ones?

**Comment by dgl** [comment]
Yeah, I think a module is the way to go to start with, it also means users of existing versions should be able to use your module and therefore it is more useful in the near term. Then if robustirc sees reasonable adoption we can think about including it with Irssi itself.

**Comment by ahf** [comment]
I love what you guys are working on, but I think this belongs in a module. We cannot take ownership of this code as it is right now, but we'll happily help you if you have a need for it when you start working on your module :-)

**Comment by stapelberg** [comment]
Thanks for the advice, everyone. I’ll investigate the feasibility of putting this into a module over the weekend.

**Comment by stapelberg** [comment]
I’ve pushed the initial commit of a RobustIRC module to https://github.com/robustirc/irssi-robustirc. At the moment, it requires that you patch in pull request #237.

I’m happy to hear any feedback you have, especially with regards to the architecture of the module. The basic functionality works, but I haven’t tested this extensively.

**Comment by kaniini** [comment]
Please be aware that RobustIRC is not robust in any way, and only trades availability for consistency tolerance.  If a RobustIRC user is connected to the partitioned side of the network, they cannot use the network at all until the partition is resolved.  This makes it a robustness downgrade in all cases as availability is the primary quality of an IRC network.

**Comment by stapelberg** [comment]
@kaniini Thanks for your feedback. For the sending side, your concern is already adressed today. For the receiving side, I’ve opened https://github.com/robustirc/robustirc/issues/111 which has an easy fix :).

**Comment by ailin-nemui** [comment]
cool, good luck with your module

**Comment by dequis** [comment]
Closing since there's a module for it.
