### ISSUE TITLE
Add support for IRCv3.2 server-time

### ISSUE THREAD

**Issue by ePirat** [irssi/irssi#236]
Irssi should have built-in support for the [IRC v3.2 server time](http://ircv3.atheme.org/extensions/server-time-3.2) capability in order to display i.e. ZNC playbacks with the correct timestamps

**Comment by dequis** [comment]
We don't even have 3.1 support yet, you know.

**Comment by ePirat** [comment]
Yes, I noticed that, I just wanted to point out that it would be very useful, so that it is considered when implementing IRCv3.2. Specially since this is only optional in the current 3.2 draft.

**Comment by ahf** [comment]
I like this idea. We need to get the CAP patches in firstly though.

**Comment by nmschulte** [comment]
Bump.  What's the status of this?

> ```
> $ irssi --version
> irssi 1.0.2-1 (20170310 1741)
> ```

**Comment by dequis** [comment]
CAP and 3.1 support happened. The rest not yet.

**Comment by darac** [comment]
There is a plugin available which provides server-time capabilities.

https://github.com/arkeet/irssi-server-time

This might be useful for anyone who's waiting for irssi itself to support this.

**Comment by ailin-nemui** [comment]
dear interested users, you can give #1108 a try now

**Comment by ailin-nemui** [comment]
dear interested users, you can give #1108 a try now mass ping @itsjohncs @arkeet @brwyatt @konomikitten @darac @nmschulte @ePirat @beardedlinuxgeek @ordex @JiK
