### ISSUE TITLE
why irssi don't support python plugin?

### ISSUE THREAD

**Issue by chapgaga** [irssi/irssi#239]
att

**Comment by ailin-nemui** [comment]
you can get it at https://github.com/irssi-import/irssi-python (see [INSTALL](https://github.com/irssi-import/irssi-python/blob/master/INSTALL) document)

**Comment by ahf** [comment]
I much love Python over Perl, but we simply don't have the manpower to handle the Python code right now.

If someone really good shows up who is willing to maintain the Python bindings (and probably work on Python 3 support) I'd love to get it in.

**Comment by chapgaga** [comment]
@ahf can irssi be built without the support ot perl?

**Comment by KindOne-** [comment]
@chapgaga  ```./configure --help```

``` 
 --with-perl=yes|no|module  Build with Perl support - also specifies
                          if it should be built into main irssi binary
                          (static, default) or as module
```

**Comment by ahf** [comment]
:1: - I'm closing this for now :-)

**Comment by timkofu** [comment]
This would be nice.
