### ISSUE TITLE
Irssi execute arbitrary command enclosed in backticks

### ISSUE THREAD

**Issue by calve** [irssi/irssi#243]
Hi.

Some of my contacts often send me message containing ``blablab `sudo echo plop` ``, and at this point, irssi prompt me for my sudo password, trying to execute the command enclosed in backticks ! (`` ` ``), and mess up my whole term (see attached screenshot).

I made the following test : 
   + Sent myself ``hello `echo vuln > testfile` `` as an IRC message
   + Open ``testfile``, and see it indeed contains ``vuln``, which proves that at one points, irssi executed the arbitrary command

This is an important issue as I do not want to execute arbitrary command sent by stranger over irc.
Please, let me know if I can provide more information.

![tmp14](https://cloud.githubusercontent.com/assets/4311079/7350736/3aafa2e4-ed01-11e4-9935-a1527b23681e.png)

**Comment by calve** [comment]
Looks like I use the ``knotify.pl`` script, which at some point contains the following line : 

    system("kdialog --title \"Irssi: $title\" --passivepopup \"$text\"");

So this may be the root of the bug

**Comment by calve** [comment]
Changed it to ``system('kdialog', '--title', 'Irssi: $title', '--passivepopup', $text);``.
For reference, it was this script : https://gist.github.com/oskopek/9566780.

Sorry for the noise, hope it helps someone

**Comment by dgl** [comment]
I don't see knotify.pl in the script archive. I'd recommend using scripts from the archive and getting them add if they aren't there. We review scripts there and will usually catch obvious issues like this (there's some older scripts which haven't been as closely reviewed).

**Comment by ahf** [comment]
Jebus this bug made me scared when I just read the title. Glad it turned out it was a script.
