### ISSUE TITLE
Highlight title bar of currently active window.

### ISSUE THREAD

**Issue by sn3twork** [irssi/irssi#244]
I think it would improve the usability of irssi if the title bar of the currently active window were highlighted in a different color than the default. For example, when I have two windows open I somewhat frequently type into the wrong channel because I forget which channel I'm typing into. Currently the main way to tell which channel is my "Active" channel is to look at the channel name in my input bar. It'd be much easier to have the title bar of the active channel/window be highlighted.

**Comment by ailin-nemui** [comment]
you can do that by adding the line `sb_window_bg = "%8";` or `sb_window_inact_bg = "%7";` to the `abstracts` section of your theme

**Comment by sn3twork** [comment]
Ah! Thanks!
