### ISSUE TITLE
@#channel and +#channel logging irregularities

### ISSUE THREAD

**Issue by slowriot** [irssi/irssi#253]
@#channel messages have always logged correctly into the logfile for #channel, but previously +#channel messages went to their own log.  This now appears to be resolved.  

However, it's also possible to combine + and @ prefixes in any quantity and order before a channel name, i.e. +@++++@@@+#channel.  It appears that irssi still checks for file length limits as if it were about to create a new logfile for those messages, even though they would otherwise be logged in-line to the normal #channel log.  Other odd things happen, too.  Example:

### Case 1

    /join #test1234
    /msg @#test1234 test 1

...works correctly and logs to #test1234.log.

### Case 2

    /msg @+@#test1234 test 2
    18:16 <@slowriot:@+@#test1234> test 2

...works correctly - same with any combination of @s and +s following, as long as there are not two @s at the start (see below).  Logs to #test1234.log as expected.

### Case 3

    /msg @@#test1234 test 2
    18:12 -!- Irssi: Starting query in Esper with
          @@#test1234
    18:13 <slowriot> test 2

...or any combination of @s and +s following the initial two @@'s at the start, opens a new query window as if the prefixed channel name was a user - also creates a new log file @@#test1234.log which presumably is not desired behaviour - this will create new log files for received messages for any number of @'s and +'s up to the filename limit, after which it gives the following in the status window:
```18:20 -!- Irssi: Couldn't create log file /home/slowriot/irclogs/Esper/@[snip]@#test1234.log: File name too long```

A user could spam a channel with messages with different combinations of @s and +s after the initial @@, causing a new logfile to be created for each, possibly causing a denial of service for users who are logging.

Some other IRC clients seem see and parse these messages correctly, so the pathological case seems to be the @@...#channel message only, although others may exist that I haven't spotted here.

**Comment by dequis** [comment]
Is this related to #248?

**Comment by slowriot** [comment]
Looks like it - the logic introduced at https://github.com/irssi/irssi/pull/248/files#diff-4a8a512a69fba94dfbab9e521240df5fR82 does not account for the fact that an arbitrary number of channel types can be prefixed to the "#channel", including duplicates.

**Comment by ailin-nemui** [comment]
statusmsgs may need to gain PREFIX support anyway

**Comment by LemonBoy** [comment]
What does the documentation say about this?
I just replicated the existing code in the PR and I'd be happy to fix this problem too.

**Comment by dequis** [comment]
#248 got merged, this should be fixed.

**Comment by ahf** [comment]
Closing.
