### ISSUE TITLE
Rawlog doesn't create folder in filename if folder doesn't already exist

### ISSUE THREAD

**Issue by flaw600** [irssi/irssi#254]
For example in /log, when you type in the destination, if a folder doesn't already exist in the pathname, log creates it for you. /rawlog does no such thing and instead returns bad file descriptor error in v0.8.17. I don't know if this is intentional, but I don't think this should be. Given the convention stated with /log, I believe consistency should be followed and thus folder creation be implemented in /rawlog.

Sorry if this seems trivial, but it was annoying to get a bad file descriptor error and not know what I was doing wrong

**Comment by ailin-nemui** [comment]
rawlog is very bare bones debugging aid. at least, the error message should be better, I guess

**Comment by flaw600** [comment]
I don't understand why rawlog can't implement the /log action of if the path doesn't exist, create it. That's what any method explicitly storing data to disk upon request is supposed to do. It honestly shouldn't be that difficult. I could do it myself, but I don't know C/C++ that well yet (currently learning). If the path exists, it seems to currently mimic /log so it shouldn't be terribly difficult.

**Comment by flaw600** [comment]
*And create it if the path doesn't exist

**Comment by GeertHauwaerts** [comment]
A patch has been applied.
