### ISSUE TITLE
Multiple minor problems in /window commands pt1

### ISSUE THREAD

**Issue by jikuja** [irssi/irssi#255]
#### Documentation
What is difference with `/window move <number>` and `/window number <number>`?

From help `NUMBER:     Move the active window to another position.` and `MOVE:         Move the window.`
No, this should be something like `Number: Swap the active window with window in another position` or even mor descriptive if possible 

Similar question also for `/window move next` and move `/window move right` If user has discontinuous windows numbering should one of those commands move window to nonexistent refnum? Currently both commands seems to skip empty window numbers. Is this a bug or is the only difference in sticky window handling?

#### `/window move <number>` behaviour inconsistent with new window creation when window numbering is discontinuous. Feature or bug?
**Use case:**
**Initial state:**
windows: 1: server/status, 2: #foo, 3: #bar, 4-7:empty 8: #baz 
Active window: 8 

**User's input and result:**
Command: /window move 2
Result: windows: server/status, 2: #baz, 3 #foo 4-7: empty and 8: #bar
vs
Command: /j #new_channel 
Result: windows: server/status 2: #baz, 3 #foo, 4: #new_channel, 5-7: empty and 8: #bar

**Comment by ailin-nemui** [comment]
Hi, please comment on whether #264 would fix your issue.

**Comment by jikuja** [comment]
Fixes documentation code problems still remain if not fixed in other commits.

**Comment by ailin-nemui** [comment]
hi, which code problems do you perceive?

**Comment by dequis** [comment]
@jikuja *poke*

**Comment by dequis** [comment]
FWIW #264 is now closed

**Comment by ailin-nemui** [comment]
@jikuja please reopen if this is still an issue
