### ISSUE TITLE
0.8.17 adding server "-port" flag oddness

### ISSUE THREAD

**Issue by zenbuddhist** [irssi/irssi#256]
v0.8.17; archlinux

Attempted to create a new server entry with:

/server add -ssl -port 6697 -network blah ::1

Server entry created but with port 6667 set.

Repeated above command and proper port (6697) was set without creating new entry.

**Comment by ailin-nemui** [comment]
not saying it makes sense, but the reason for this is that `-port` is for modifying an entry and `<address> <port>` is for adding an entry. Example:

`/server add -network net1 example.com 6697` # add server of network 1
`/server add -network net2 example.com 6698` # add server of network 2
`/server add -port 6667 example.com` # modify port of server in network **2**
`/server add -port 6668 example.com 6697` # modify port of server in network **1**

**Comment by zenbuddhist** [comment]
Oh now it (almost) makes perfect sense...thanks for pointing that out. I see that its setting the default port initially.
