### ISSUE TITLE
request: ctrl+shift+x to reverse order when switching channels/servers in current window

### ISSUE THREAD

**Issue by atomi** [irssi/irssi#260]
Would be nice if we could ctrl+shift+x to reverse order when switching channels/servers in current window.

**Comment by dequis** [comment]
I'm pretty sure terminals don't have the concept of "ctrl+shift+x". Both ctrl-x and ctrl-shift-x are mapped to ^X (ascii 18).

If you want to use some other combination in your config, you can add a keybinding for previous_window_item, like `/bind ^Z previous_window_item` (if you don't care about suspending irssi)

**Comment by atomi** [comment]
I didn't know that. Thanks.
