### ISSUE TITLE
irssi GUI nonfunctional on OS X 10.11

### ISSUE THREAD

**Issue by aw1621107** [irssi/irssi#266]
Running OS X 10.11, irssi 0.8.17 installed through homebrew, and removed .irssi

It's kind of hard to describe this. The short of it is that irssi's GUI completely breaks for me upon attempting to connect to an irc server. Blue bars vanish, part of the history from before irssi was launched shows, and text starts getting printed in odd places. The clock area refreshes each new minute. /reload sort of reloads the GUI, but it still doesn't retain its normal functionality.

Here's a quick demo: http://youtu.be/equTcwREa5k

One time when messing around with this irssi segfaulted on a /connect attempt, but I've never been able to reproduce it.

I checked for /etc/socks.conf, but it doesn't exist. `touch`ing it resulted in irssi "working" -- things acted as they should (and some warnings about an empty socks.conf, but I don't know what to put in there), but the GUI was still a bit wonky. 

I really hope I'm not missing anything obvious or duping another bug. If more information is needed I'll be glad to provide it.

**Comment by dequis** [comment]
What terminal is it? What is the output of `echo $TERM`?

Also, those configure options are terrible. Dante? No openssl? No perl? If you don't need dante, don't build with dante. OpenSSL and perl are sorta essential to use irssi decently, too. I don't think that's relevant to your issue anyway. Or at least I hope it's not.

**Comment by aw1621107** [comment]
iterm2 nightly build, xterm-256color. Don't think the nightly part is the problem, since this has been going on and off for quite a while.

And those are just flags you can use to build with; I didn't use any of them. And I messed with them before, and I don't believe any of the flags made a difference

**Comment by ailin-nemui** [comment]
I'd recommend wipe your irssi *installation* (not `.irssi`) and brew it again. The socks.conf error is a hint that you compiled with dante, but maybe dante wasn't installed correctly on your system.

**Comment by aw1621107** [comment]
I've done that multiple times, with and without dante, with and without openssl/perl, and switching between HEAD and latest stable version. It doesn't seem to change anything. The particular installation in the video should be the stable version without dante and with openssl/perl; any flags used should appear after the "build from source" that `brew info irssi` shows.

**Comment by ailin-nemui** [comment]
in that case maybe it helps to remove dante from your system and reinstall irssi?

**Comment by aw1621107** [comment]
....Yep, that did it. Seems it's a bug on the homebrew side then. Feel kind of silly for not thinking of this before. Thanks though!

**Comment by ailin-nemui** [comment]
maybe you could raise this issue with homebrew, why dante doesn't work, and why there is no explicit switch to enable socks

**Comment by aw1621107** [comment]
Yep, working on it right now. The switch is there, but it looks to me that it never is actually used.
