### ISSUE TITLE
The /version command should be changed

### ISSUE THREAD

**Issue by KonomiKitten** [irssi/irssi#270]
At the moment `/version` outputs both the version of irssi and version information from the server you're connected to. If you do `/script exec Irssi::command(version);` you'll even get an error that you're not connected to a server. I think these two functions should be seperated out. Say `/version` for the server and `/irssiversion` or something along those lines.

**Comment by ailin-nemui** [comment]
`/alias irssiversion echo -level clientnotice Client: irssi $J ($V $versiontime)`

;-)

**Comment by KonomiKitten** [comment]
Oh, that's handy thanks!
