### ISSUE TITLE
Error: Can't locate package Irssi::Nick (Line 1120)

### ISSUE THREAD

**Issue by TheMafia442** [irssi/irssi#271]
When I start IRSSI I keep getting this error. It crashes fairly often after the latest update. Can anyone help me?

05:49 Can't locate package Irssi::Nick for @Irssi::Irc::Nick::ISA at
/media/sdr1/home/username/.irssi/scripts/AutodlIrssi/AutoConnector.pm line
          1120.
05:49
05:49 Can't locate package Irssi::Nick for @Irssi::Irc::Nick::ISA at
/media/sdr1/home/username/.irssi/scripts/AutodlIrssi/AutoConnector.pm line
          1120.

**Comment by ailin-nemui** [comment]
this is a bug in irssi, but you can easily work around it by making and loading a script with this content:

`{ package Irssi::Nick }`

however, it should not be related with any crashes, those have to have another reason/origin

**Comment by dequis** [comment]
@TheMafia442 full list of scripts you're using?

**Comment by ailin-nemui** [comment]
`/script exec $^W=1; print for (Irssi::channels)[0]->nicks`

**Comment by TheMafia442** [comment]
03:26 Irssi::Irc::Nick=HASH(0x3b4dc48)
03:26 Irssi::Irc::Nick=HASH(0x39217e0)
03:26 Irssi::Irc::Nick=HASH(0x3921a50)
03:26 Irssi::Irc::Nick=HASH(0x3b51330)
03:26 Irssi::Irc::Nick=HASH(0x3923e78)
03:26 Irssi::Irc::Nick=HASH(0x3923bc0)
03:26 Irssi::Irc::Nick=HASH(0x3921b88)
03:26 Irssi::Irc::Nick=HASH(0x3b2a7b0)
03:26 Irssi::Irc::Nick=HASH(0x39219c0)
03:26 Irssi::Irc::Nick=HASH(0x39239b0)
03:26 Irssi::Irc::Nick=HASH(0x3707250)
03:26 Irssi::Irc::Nick=HASH(0x3b52f28)
03:26 Irssi::Irc::Nick=HASH(0x3b74e58)
03:26 Irssi::Irc::Nick=HASH(0x3b03118)
03:26 Irssi::Irc::Nick=HASH(0x3b2d6e8)
03:26 Irssi::Irc::Nick=HASH(0x3700e50)
03:26 Irssi::Irc::Nick=HASH(0x3b2dda8)
03:26 Irssi::Irc::Nick=HASH(0x38ce9b8)
03:26 Irssi::Irc::Nick=HASH(0x3b30e98)
03:26 Irssi::Irc::Nick=HASH(0x3b25d38)
03:26 Irssi::Irc::Nick=HASH(0x3b53510)

This was the output from that command you asked me to run.

**Comment by dequis** [comment]
I think that wasn't something you had to run, but a test case to reproduce this bug. I guess it works for you because you have that `{ package Irssi::Nick }` thing suggested before? Because it throws some errors for me.

Also, I was asking for a full list of scripts mostly because of the crashing problem, which may be unrelated to those errors you saw. Does that still happen?

**Comment by TheMafia442** [comment]
Sorry mate, I'm not too experienced with irssi. How do I get a full list if scripts?

**Comment by dequis** [comment]
`/script list`

But if it doesn't crash anymore, we can just pretend the only issue is the "Can't locate package" thing you originally reported.

**Comment by TheMafia442** [comment]
I just had a look. I still get the error during startup:

(xxxxx is my username)

04:49 Can't locate package Irssi::Nick for @Irssi::Irc::Nick::ISA at
/media/sdr1/home/xxxxxxxx/.irssi/scripts/AutodlIrssi/AutoConnector.pm line
          1120.
04:49
04:49 Can't locate package Irssi::Nick for @Irssi::Irc::Nick::ISA at
/media/sdr1/home/xxxxxxxx/.irssi/scripts/AutodlIrssi/AutoConnector.pm line
          1120.

This is what I get when I run the command /script list

04:50 Loaded scripts:
04:50 autodl_irssi
          /media/sdr1/home/xxxxxxx/.irssi/scripts/autorun/autodl-irssi.pl

**Comment by Fugor** [comment]
Same error message for me. I don't have crashes though.

Don't know if this is related but my plugin in Rutorrent doesn't react, whatever i clic. 

Don't know much about it, ask me what you need I'd be happy to help.

**Comment by dequis** [comment]
Did this ever work, btw?

**Comment by ailin-nemui** [comment]
it's a "harmless" warning

**Comment by Fugor** [comment]
Oh ok, thought it was linked to my plugin issue.

**Comment by dequis** [comment]
lol https://github.com/autodl-community/autodl-irssi/blob/1de29939217b8c1ef8e5f411164087a05188ace9/AutodlIrssi/Irssi.pm#L110

**Comment by ailin-nemui** [comment]
well, the less noisy workaround is `{ package Irssi::Nick }`. Just add that to your autodl-irssi.pl
