### ISSUE TITLE
Irssi doesn't pass on special characters in passwords when using 'autosendcmd' 

### ISSUE THREAD

**Issue by flaw600** [irssi/irssi#272]
I try to have irssi auto-send passwords for nick registration and things and I've noticed that it seems to not send some special characters. The one I've noticed is the '$' but I recall it not sending '^' and '&' and ''%' so I think it is all numberpad special characters. I don't know why this happens but if someone could please fix this, that would be great.

**Comment by dequis** [comment]
Put two backslashes before the $, like this: `\\$`

This happens because the command is evaluated twice for variables (when you enter the command, and when autosendcmd is run), which start with `$`

**Comment by flaw600** [comment]
Ah, ok. Ooc, is this in the documentation? I couldn't find it, but I may have missed it.

**Comment by flaw600** [comment]
Solution works. Thanks!
