### ISSUE TITLE
[FEAT] "act" text should take colour of highest prio irssi notification

### ISSUE THREAD

**Issue by purpleidea** [irssi/irssi#273]
If you have > 30+ windows, and there is a notifications of a message in window 40, you don't see it unless you scroll to the right so that the numbers all show. It would be a nice feature if the "act" string would take the colour of the highest prio window.

Make sense?
I'm willing to offer a bounty of a beverage or something similar if this is merged in core within 2 weeks or so.
Thanks!

**Comment by ailin-nemui** [comment]
`/set actlist_sort level`?

**Comment by purpleidea** [comment]
@ailin-nemui this is a pretty cool feature, and thank you for telling me about it, however it is different than what I mentioned above, and I would still like to propose the above feature :)

**Comment by flaw600** [comment]
@ailin-nemui what exactly does that do that purpleidea’s doesn’t? Personally, I don’t see purple’s idea as  time-sensitive at all, namely because who realistically carries 30+ conversations at once? That being said, it’s not a bad idea either, but idk what actlist sort’s values are.

**Comment by ailin-nemui** [comment]
I believe this would otherwise be solvable with a script ;-)

**Comment by flaw600** [comment]
Agreed. Given that most users won’t ever encounter this problem, this seems ideal for a script.

**Comment by purpleidea** [comment]
On Wed, Aug 26, 2015 at 1:35 PM, flaw600 <notifications@github.com> wrote:

> Agreed. Given that most users won’t ever encounter this problem, this
> seems ideal for a script.



Anyone have any skills to write such a script? I would reward them with
internet love, or some beverages when we're in the same city.

**Comment by purpleidea** [comment]
The use case isn't 30+ conversations at once, but rather having 30+
channels open and seeing when someone pings you. If there is a ping at
channel 42, you don't see it unless you scroll all the way over. If
"act" lighted up red, you would know there is something hidden you
might want to scroll to.

**Comment by flaw600** [comment]
I know the use case you are referring to. If you're not actively looking at 30+ conversations at once then there's no need for those windows to be open. If you simply want to hang around there, then a suggestion would be to use a znc until you're ready to actually pay attention. Regardless of which use case is used, the fact is that as has been said before, not everything needs to be in core and in this case most users won't ever encounter the use case in the first place.

That being said, I agree that your idea is a good one and hence why a script would be apt for this. As for who could create such a script, I defer to others who have far more experience than me.

**Comment by purpleidea** [comment]
On Mon, Aug 31, 2015 at 12:51 PM, flaw600 <notifications@github.com> wrote:

> I know the use case you are referring to. If you're not actively looking
> at 30+ conversations at once then there's no need for those windows to be
> open. If you simply want to hang around there, then a suggestion would be
> to use a znc until you're ready to actually pay attention. Regardless of
> which use case is used, the fact is that as has been said before, not
> everything needs to be in core and in this case most users won't ever
> encounter the use case in the first place.
>
I use irssi+screen, see here for details on my setup:
https://ttboj.wordpress.com/2013/10/18/desktop-notifications-for-irssi-in-screen-through-ssh-in-gnome-terminal/
znc doesn't solve my problem. the problem is the irssi display.



> That being said, I agree that your idea is a good one and hence why a
> script would be apt for this. As for who could create such a script, I
> defer to others who have far more experience than me.
>
+1 :) Thanks!

**Comment by ailin-nemui** [comment]
I don't believe it makes sense to add this in core for now
