### ISSUE TITLE
Configure space after completed word/nick

### ISSUE THREAD

**Issue by anlutro** [irssi/irssi#282]
I like to set `completion_char = ""` because I often want to start a line with someone's nickname, without adding the `:`.

However, if I then actually want to type `nickname: hello`, I have to hit backspace before typing the `:`. This is kind of annoying.

Could it be possible to add a setting for adding the space after a completed word/nick? I see references to a boolean-like `want_space` variable in completion.c, but can't see a way to change it from a user perspective.

**Comment by ailin-nemui** [comment]
maybe you could use a script instead? see for example the niq script (which does something different, but also deals with nick completion at the start of a line)

**Comment by vague666** [comment]
You can clear the setting, /set -clear completion_char

**Comment by ailin-nemui** [comment]
or do you mean `/script exec -perm Irssi::signal_add_first('complete word' => sub { &Irssi::signal_continue; ${$_[4]} = 0 })`

**Comment by anlutro** [comment]
@ailin-nemui That does seem to do what I want, cool!

**Comment by ailin-nemui** [comment]
closing as solved with script

**Comment by dequis** [comment]
You forgot to actually close it
