### ISSUE TITLE
clock breaks when hebrew is used

### ISSUE THREAD

**Issue by TomHetmer** [irssi/irssi#328]
Notice the broken time in the line with the hebrew text.

![bez nazvu](https://cloud.githubusercontent.com/assets/5316250/10281459/e44982c4-6b74-11e5-941c-c9957d6c8d65.png)

Alpine Linux 3.2.3 ARM

toto@olx:~/irclogs% uname -a
Linux olx 4.1.6-249 #1 SMP Mon Aug 31 12:34:47 UTC 2015 armv7l Linux
toto@olx:~/irclogs% irssi -v
irssi 0.8.17 (20141011 1044)

**Comment by dequis** [comment]
This is a problem with putty, not with irssi. Other terminal emulators don't have this problem. 

Similar bug report in the weechat tracker: https://github.com/weechat/weechat/issues/261

>I was able to get rid of the problem by disabling bidirectional text display from putty settings.

**Comment by GeertHauwaerts** [comment]
Hebrew is read from right-to-left (RTL), while Irssi was detecting Irssi, it appears to have applied RTL to the clock as well.

This is indeed a bug which needs to be investigated.
