### ISSUE TITLE
Compile error on origin/master

### ISSUE THREAD

**Issue by camponez** [irssi/irssi#329]
configure: --prefix=/usr --with-gc --with-bot --enable-ssl

---------------

../fe-common/irc/libfe_common_irc.a(fe-common-irc.o): In function `fe_common_irc_init':
fe-common-irc.c:(.text+0x6e): undefined reference to `fe_sasl_init'
../fe-common/irc/libfe_common_irc.a(fe-common-irc.o): In function `fe_common_irc_deinit':
fe-common-irc.c:(.text+0xeb): undefined reference to `fe_sasl_deinit'
../irc/core/libirc_core.a(irc-core.o): In function `irc_core_init':
irc-core.c:(.text+0x14a): undefined reference to `cap_init'
irc-core.c:(.text+0x14f): undefined reference to `sasl_init'
../irc/core/libirc_core.a(irc-core.o): In function `irc_core_deinit':
irc-core.c:(.text+0x1a3): undefined reference to `sasl_deinit'
irc-core.c:(.text+0x1a8): undefined reference to `cap_deinit'
../irc/core/libirc_core.a(irc-servers.o): In function `sig_connected':
irc-servers.c:(.text+0xd2b): undefined reference to `cap_toggle'
irc-servers.c:(.text+0xede): undefined reference to `cap_toggle'
collect2: error: ld returned 1 exit status
make[3]: *** [irssi] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Erro no make!

**Comment by dequis** [comment]
`make clean` and try again?

**Comment by ahf** [comment]
We killed GC support a couple of days ago as well.

See: https://github.com/irssi/irssi/commit/29cf546ee4d5c1af1042d6fbeaae150ecc545d4a

**Comment by camponez** [comment]
> make clean and try again?

Nothing.

Now I'm using this as a configure line: --prefix=/usr --with-bot --enable-ssl

Still Nothing.

**Comment by dequis** [comment]
`make distclean`

`git clean -fdx` (will remove absolutely all the unversioned things under the git tree)

If it still doesn't work, what platform?

**Comment by camponez** [comment]
Now it finally worked!!

Thanks.

By the way, I'm using Ubuntu 15.04.

Cheers.
