### ISSUE TITLE
Highlights vs /HILIGHT is confusing

### ISSUE THREAD

**Issue by pleia2** [irssi/irssi#336]
Whenever I go to add a new highlight I spent a couple minutes trying to remember what the command is. The trouble is that the command is /HILIGHT but when the actual highlights are shown they're listed as Highlights:

Is it possible to make these words the same? Probably changing the Highlights: header to the list of highlights would be the easiest and least disruptive.

**Comment by ailin-nemui** [comment]
maybe `/alias highlight hilight` or `/format hilight_header %#Hilights:` could help you

**Comment by pleia2** [comment]
I've already done the alias :) this was my attempt to be good open source citizen by explaining what I've run into so others don't have to do the same work-around.

**Comment by ailin-nemui** [comment]
highlight is a default alias in fresh irssi configurations of new installs. do you think that is enough?

**Comment by pleia2** [comment]
Ah! Good to know. Yes, that's great.
