### ISSUE TITLE
SASL authentication fails if `-sasl_mechanism` isn't specified

### ISSUE THREAD

**Issue by FreeFull** [irssi/irssi#337]
The server will wait for SASL authentication to finish, and once the timeout is reached, fail. `-sasl_mechanism` should probably default to `plain` if not specified.

**Comment by ahf** [comment]
CC: @LemonBoy

**Comment by LemonBoy** [comment]
If `sasl_mechanism` isn't specified irssi won't even start the SASL handshake [1].

[1] https://github.com/irssi/irssi/blob/7ab38f29edb59941281723d7031d41d93fae06bd/src/irc/core/irc-servers-setup.c#L91

**Comment by FreeFull** [comment]
You're right, SASL authentication is never tried if `sasl_mechanism` isn't set. I'm not sure what I was seeing. What do you think about defaulting to `plain` if `sasl_username` and `sasl_password` get set? It's what I intuitively expected, before I found out setting `sasl_mechanism` was needed too.
