### ISSUE TITLE
No proxy username 

### ISSUE THREAD

**Issue by vivekanand1101** [irssi/irssi#339]
Hi,
I am working behind a proxy server and wanted to set up irssi. I saw the [documentation](www.irssi.org/documentation/startup) for help and found that it didn't specify proxy user id  but did have settings for `proxy_password`. My proxy server prompts for user id and password. I assume irssi takes user id from some place else. It would be great if any body could guide me on how to set up settings for proxy.

**Comment by MilosD** [comment]
Hi vivekanand1101,
You can try to set http_proxy environment variable, and then run irssi. Example:
```
export http_proxy=http://username:password@proxy_server_ip:3128/
irssi
cat /proc/$(pidof irssi)/environ - (http_proxy environment variable should be present)
```
Hope that helps.

**Comment by dequis** [comment]
>You can try to set http_proxy environment variable

Fairly sure that won't work at all... zero mentions in the source code.

**Comment by ailin-nemui** [comment]
You need to manually form a Proxy-Authorization header, that is the Base64 representation of the proxy username:password, and include it in the proxy_string setting separated with \r\n

**Comment by vivekanand1101** [comment]
can you give me an example, please?

**Comment by ailin-nemui** [comment]
something like:
```
/EVAL SET proxy_string CONNECT %s:%d HTTP/1.0\nProxy-Authorization: dXNlcm5hbWU6cGFzc3dvcmQ=\n\n
```
whereby `dXNlcm...` is retrieved by running `/exec - echo -n username:password | base64`

**Comment by ailin-nemui** [comment]
please reopen if the info does not resolve your issue
