### ISSUE TITLE
irssi + tmux buffering issue

### ISSUE THREAD

**Issue by danobi** [irssi/irssi#349]
When using irssi with tmux, irssi will only update the very last line in chat when there are new messages / notifications. For example, if 5 people sent messages, you would only see the very bottom line in the chat box display the 5th person's message. The other 4 would be absent. A workaround is to switch to a different window in irssi and switch back to the original window. Then everything will be properly displayed.

The issue is not seen with irssi running solo (without tmux). 

Seen with Arch Linux running tmux 2.1 and irssi 0.8.17.

**Comment by vague666** [comment]
The problem is most likely with your TERM env var. In tmux it should be screen[-256color], you can test what irssi thinks TERM is with /eval echo $TERM

**Comment by danobi** [comment]
Ah, my bad. I thought I had done that but I didn't restart my tmux window.
