### ISSUE TITLE
`mute` command

### ISSUE THREAD

**Issue by Qix-** [irssi/irssi#356]
So we have `/ignore`, which completely ignores someone.

However, I'm in a room with a slightly smaller signal:fuzz ratio (lots of bots). I don't want to completely ignore the bots, because they have some useful info, but I would like to be able to see real people talking too.

`/mute` would essentially dim out the output from whatever user, allowing normal users (unmuted users) to speak with regular colors.

Here's an example of the fuzz.

<img width="1485" alt="screen shot 2015-11-18 at 00 47 55" src="https://cloud.githubusercontent.com/assets/885648/11235378/55bf06c8-8d8e-11e5-9193-eaf013fc7af5.png">

**Comment by vague666** [comment]
You could use trigger.pl to color those messages, I use the following to color urls
/trigger add -publics -regexp '(http://[^ ]+)' -replace '\x0310,2$1\x03'
trigger takes a -mask argument so you can specify which users to match

**Comment by Qix-** [comment]
so just

```
/trigger add -publics -mask BotName!*@* -replace '\x0310,2$1\x03'
```

?

**Comment by vague666** [comment]
I gave that as an example so no, it's not correct, something like
/trigger add -publics -masks bot!*@* -regexp '^(.*)$' -replace '\x03<the color of your choice$1\x03'

**Comment by vague666** [comment]
Maybe this can be continued in #irssi?

**Comment by Qix-** [comment]
Sure, though is this something that would otherwise be considered for irssi or should this be closed in lieu of trigger.pl?

**Comment by vague666** [comment]
I doubt this would be accepted but I'll let the developers answer that pit of snakes

**Comment by Qix-** [comment]
Yeah trigger.pl looks incredibly useful. Didn't realize such a thing existed. That should suffice.

Thanks @vague666!
