### ISSUE TITLE
Server passwords doesn't start with colon with spaced password

### ISSUE THREAD

**Issue by kyrias** [irssi/irssi#362]
If the server password to be sent contains spaces, the argument has to have a colon prefixed to it so that the whole password is recognized as a single argument by the server, otherwise a password containing a space should be interpreted as having multiple arguments, which is nonsensical since the `PASS` command only takes one. irssi currently just sends `PASS <password>` instead.

**Comment by ailin-nemui** [comment]
does it work if you simply include the : in your password?

**Comment by kyrias** [comment]
It does.

(For reference: znc/znc#1188)

**Comment by ailin-nemui** [comment]
I wonder how other IRC servers handle password when they are prefixed with :. We also have to consider the case where some IRC servers "extended" the protocol by allowing additional parameters to be sent in PASS, which can happily be done by abusing the client password field if it does **not** auto-quote

**Comment by ailin-nemui** [comment]
I think requiring users to manually quote the password is one possible outcome. @ahf ?

**Comment by dequis** [comment]
I think we should do the same thing weechat did: https://github.com/weechat/weechat/commit/4fca6c58c8d817363a20da6691c1e9705f6234f1

If someone is abusing a bug in our implementation, they don't get to complain when we fix it.

Unless someone can point out some major server implementation that actually requires this.

**Comment by ahf** [comment]
Never quote me out of context, but I think what weechat did there is sensible.

**Comment by ailin-nemui** [comment]
depending on the server a password starting with : will either be interpreted correctly or incorrectly
