### ISSUE TITLE
No scroll in pure tty

### ISSUE THREAD

**Issue by kosc** [irssi/irssi#366]
When running irssi without X Window System, it has no scroll, every new message just replacing last chat line.

**Comment by ailin-nemui** [comment]
maybe you set the `TERM` environment variable wrong

**Comment by incertia** [comment]
I can scroll normally with PageUp/PageDown in my tty environments.

**Comment by kosc** [comment]
Yes, it was wrong TERM variable - change it from "xterm-256color" to "linux" and scroll works well, thank you!
