### ISSUE TITLE
Hilights non-functional outside trivial public messages

### ISSUE THREAD

**Issue by ilbelkyr** [irssi/irssi#388]
irssi/irssi@deb6ca1 appears to have broken hilights except for ordinary public messages. In particular, hilights do not work in CTCP ACTION (/me), notice, or various other message types I've checked.

Reverting deb6ca1 seems to fix this issue (see ilbelkyr/irssi@49395c5), but that also undoes the improvement made in the commit. I'm afraid I'm insufficiently familiar with the irssi codebase to immediately provide a better patch.

**Comment by ailin-nemui** [comment]
thanks for testing our crap. can you try https://github.com/ailin-nemui/irssi/commit/c6a85721a6e9d5a6f67f76f0062c750146c6805f ?

**Comment by ilbelkyr** [comment]
Works for me.
