### ISSUE TITLE
Segmentation fault when using wrong-version Irssi.pm / Irssi.so

### ISSUE THREAD

**Issue by laiti** [irssi/irssi#391]
I get a segmentation fault with my config when using the latest irssi from git. This doesn't happen with clean config. That /etc/localtime exists and is a valid file.

Strace ends like this and doesn't help me that much:

```
stat("/home/users/laiti/irssi-crash/scripts/File/Spec/Unix.pmc", 0x3d1a61213b0) = -1 ENOENT (No such file or directory)
stat("/home/users/laiti/irssi-crash/scripts/File/Spec/Unix.pm", 0x3d1a6121300) = -1 ENOENT (No such file or directory)
stat("/home/users/laiti/.local/share/irssi/scripts/File/Spec/Unix.pmc", 0x3d1a61213b0) = -1 ENOENT (No such file or directory)
stat("/home/users/laiti/.local/share/irssi/scripts/File/Spec/Unix.pm", 0x3d1a6121300) = -1 ENOENT (No such file or directory)
stat("~/.local/lib/perl/5.8/File/Spec/Unix.pmc", 0x3d1a61213b0) = -1 ENOENT (No such file or directory)
stat("~/.local/lib/perl/5.8/File/Spec/Unix.pm", 0x3d1a6121300) = -1 ENOENT (No such file or directory)
stat("/etc/perl/File/Spec/Unix.pmc", 0x3d1a61213b0) = -1 ENOENT (No such file or directory)
stat("/etc/perl/File/Spec/Unix.pm", 0x3d1a6121300) = -1 ENOENT (No such file or directory)
stat("/usr/local/lib/perl/5.14.2/File/Spec/Unix.pmc", 0x3d1a61213b0) = -1 ENOENT (No such file or directory)
stat("/usr/local/lib/perl/5.14.2/File/Spec/Unix.pm", 0x3d1a6121300) = -1 ENOENT (No such file or directory)
stat("/usr/local/share/perl/5.14.2/File/Spec/Unix.pmc", 0x3d1a61213b0) = -1 ENOENT (No such file or directory)
stat("/usr/local/share/perl/5.14.2/File/Spec/Unix.pm", 0x3d1a6121300) = -1 ENOENT (No such file or directory)
stat("/usr/lib/perl5/File/Spec/Unix.pmc", 0x3d1a61213b0) = -1 ENOENT (No such file or directory)
stat("/usr/lib/perl5/File/Spec/Unix.pm", 0x3d1a6121300) = -1 ENOENT (No such file or directory)
stat("/usr/share/perl5/File/Spec/Unix.pmc", 0x3d1a61213b0) = -1 ENOENT (No such file or directory)
stat("/usr/share/perl5/File/Spec/Unix.pm", 0x3d1a6121300) = -1 ENOENT (No such file or directory)
stat("/usr/lib/perl/5.14/File/Spec/Unix.pmc", 0x3d1a61213b0) = -1 ENOENT (No such file or directory)
stat("/usr/lib/perl/5.14/File/Spec/Unix.pm", {st_mode=S_IFREG|0644, st_size=7510, ...}) = 0
open("/usr/lib/perl/5.14/File/Spec/Unix.pm", O_RDONLY) = 15
ioctl(15, SNDCTL_TMR_TIMEBASE or TCGETS, 0x3d1a6121090) = -1 ENOTTY (Inappropriate ioctl for device)
lseek(15, 0, SEEK_CUR)                  = 0
read(15, "package File::Spec::Unix;\n\nuse s"..., 8192) = 7510
brk(0x45c4000)                          = 0x45c4000
read(15, "", 8192)                      = 0
close(15)                               = 0
read(14, "", 8192)                      = 0
close(14)                               = 0
brk(0x45e5000)                          = 0x45e5000
brk(0x45e4000)                          = 0x45e4000
open("/home/users/laiti/irssi-crash/default.theme", O_RDONLY) = 14
close(14)                               = 0
open("/home/users/laiti/irssi-crash/default.theme", O_RDONLY) = 14
read(14, "# When testing changes, the easi"..., 4000) = 4000
read(14, "es\n  ##\n\n  # the basic styling o"..., 4000) = 4000
read(14, "\n  #topicsbend = \"{sbend $*}\";\n\n"..., 4000) = 473
read(14, "", 4000)                      = 0
close(14)                               = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=1883, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=1883, ...}) = 0
--- SIGSEGV (Segmentation fault) @ 0 (0) ---
+++ killed by SIGSEGV +++
Segmentation fault
```

**Comment by ailin-nemui** [comment]
copy of that config may help...

**Comment by laiti** [comment]
That config contains a lot of personal stuff – it takes a lot of work to clean it up. But I’ll do that as a last resort.

Also, it seems that if keepnick.pl or tmux_away.pl is in scripts/autorun, it crashes.

**Comment by ailin-nemui** [comment]
does it crash with the script only and a fresh config? does it crash with your config and not those scripts? at the bare minimum, get a gdb backtrace. See https://github.com/irssi/irssi/blob/master/docs/crash.txt

**Comment by laiti** [comment]
Nope, it requires the whole setup. If I disable those scripts, it starts and connects to the server but then crashes.
Thanks for the gdb tip.

**Comment by laiti** [comment]
Here's the gdb output. Looks like I found a third script that also causes a segfault: autorealname.pl. The JOIN of nick Hoffe caused a call to that script.

[bt.log.txt](https://github.com/irssi/irssi/files/79832/bt.log.txt)

**Comment by ailin-nemui** [comment]
please supply some more information by running the following command:
```
/script exec use Irssi; print for "Irssi Information:", "Perl " . $^V, "Exe path: " . $^X, "Base Module: " . $INC{"Irssi.pm"}

**Comment by laiti** [comment]
ke154348 Irssi Information:
 ke154348 Perl v5.14.2
 ke154348 Exe path: /home/users/laiti/.local/bin/irssi
 ke154348 Base Module: /usr/lib/perl5/Irssi.pm

**Comment by ailin-nemui** [comment]
would it be possible that you are trying to combine the wrong versions of Irssi's perl modules and binary? /usr/lib/perl5/Irssi.pm sounds like it would belong to /usr/bin/irssi. I suspect that one is of a different version than ~/.local/bin/irssi? Mismatching irssi version and bindings would explain such crashes

**Comment by laiti** [comment]
That was my thought too after I posted that comment. But how can I have the ~/.local/bin/irssi to use the modules under ~/.local instead of /usr?

**Comment by ailin-nemui** [comment]
how did you configure and install Irssi?

try:
```
export PERL5LIB=/home/users/laiti/directory/where/Irssipm/is
irssi

**Comment by laiti** [comment]
export PERL5LIB="/home/users/laiti/.local/lib/perl5/x86_64-linux-gnu-thread-multi" helped. Thanks!


How I compile irssi is
    CONFPARAMS="--enable-maintainer-mode --prefix=${HOME}/.local --enable-ipv6 --with-proxy --with-bot --enable-true-color --with-perl=yes"
    ./autogen.sh ${CONFPARAMS}
    ./configure ${CONFPARAMS}
    make && make install

I am pretty sure that either autogen or configure is redundant there, but it hasn’t hurt to have them both in the compile script.

**Comment by ailin-nemui** [comment]
is there a `perl_use_lib` entry in your ~/.irssi/config ?

**Comment by laiti** [comment]
yes, and it actually looks deprecated:

 ke160550 perl_use_lib = ~/.local/lib/perl/5.8

**Comment by ailin-nemui** [comment]
try removing that line altogether and see if irssi figures out the correct perl_use_lib on next start?

**Comment by laiti** [comment]
Yes, that fixes the situation too.

**Comment by ailin-nemui** [comment]
Can you try to recreate your issue using https://github.com/ailin-nemui/irssi/tree/prepare/0.8.18 (with unfortunate perl_use_lib in your config) and check if that will detect the issue early on?

**Comment by laiti** [comment]
Tested, it seems that the issue is reproducible with that source too.

**Comment by ailin-nemui** [comment]
sorry I have to make sure: you did git clone https://github.com/ailin-nemui/irssi.git; git checkout prepare/0.8.18; ./autogen.sh; ... ? And it still segfaulted? The idea is that it would print an error message instead

**Comment by laiti** [comment]
Oh, right. I forgot to do the checkout part. I did it now and now it works as you meant it to:

to0852   -!- Irssi: Error in script logresume:
to0852   Attempt to reload Irssi.pm aborted.
to0852   Compilation failed in require at (eval 48) line 1.
to0852   BEGIN failed--compilation aborted at (eval 48) line 1.
