### ISSUE TITLE
Built-in SASL authentication (IRCv3.1)

### ISSUE THREAD

**Issue by dequis** [irssi/irssi#4]
SASL based authentication is a required extension for IRCv3 compliance (CAP and multi-prefix are required too). This approach solves many of the caveats of methods like "nickserv", and is required in some cases, such as connecting to freenode through tor.

This is currently implemented with third party scripts. I believe it should be a built-in feature (or at the very least, include the script with the default distribution)

Description of the current script based approach: https://freenode.net/sasl/sasl-irssi.shtml

The script itself: https://freenode.net/sasl/cap_sasl.pl

Spec: http://ircv3.org/extensions/sasl-3.1

IRCv3 general information: http://ircv3.org/ (irssi is notably missing from the "Compliant Software" section)

**Comment by LemonBoy** [comment]
As of today, with the deprecation of the DH-{AES,BLOWFISH} and the introduction (?) of SCRAM-SHA-256, what is the minimum set of mechanisms to support that provides the most compatibility and security ?
For the simplicity sake I'd say that PLAIN over SSL is enough for most, if not all, the use cases, but I'm not a security expert nor very knowledgeable about the recent SASL developments so my word should be taken with a grain of salt.

**Comment by Mikaela** [comment]
I have no idea what is SCRAM-SHA-256, but currently Atheme supports

* SASL PLAIN
* SASL EXTERNAL
* SASL ECDSA256-CHALLENGEAUTH
    * but on \#irc3 kaniini has said that it's already dead and that is why znc won't be implementing it if I understood correctly.

There is also already [IRCv3.2 SASL](http://ircv3.net/specs/extensions/sasl-3.2.html) which features SASL REAUTH which allows SASL to be used after the initial connection e.g. when you have connected  to splitted servers or services were down. Before it the only way to automatically identify in that case was CertFP. I think that irssi should also get it implemented.

**Comment by LemonBoy** [comment]
Well, IRCv3.2 isn't a priority right now since not even IRCv3.1 is supported, getting in some solid CAP and SASL support is a big step in the right direction (and it's being done in #222).
I was referring to this[1] which is listed here[2] among the other "common" mechanisms, while the ECDSA256-CHALLENGEAUTH isn't listed at all, this makes me question the usefulness of that list.
But since you state the aforementioned mechanism is 'dead' I'm inclined to add support for PLAIN and EXTERNAL only since it's a safe bet those won't go away anytime soon

[1] https://tools.ietf.org/html/draft-hansen-scram-sha256-02
[2] http://ircv3.net/docs/sasl-mechs.html

**Comment by kaniini** [comment]
What she is saying is that SASL REAUTH should be considered for implementation at the same time as the rest of it to ensure it actually gets done.  REAUTH is essentially just a clarification that authentication could be implemented after registration, and can be done on 3.1 servers (assuming that they have gotten patched to allow it).

**Comment by dequis** [comment]
#278 is now merged, with SASL PLAIN and EXTERNAL support. Huge thanks to @LemonBoy for contributing this and addressing the issues that were brought up during the review... some of which may have been *a bit* nitpicky.

Things left out of the scope of that pull request, to be addressed before the release:

* Signals to allow scripts to implement additional mechanisms (such as the ECDSA one)
* Compatibility with the existing cap_sasl.pl script (bug #279)
* SASL REAUTH. That would require something like a command to manually reauthenticate, the current implementation only does it automatically during connection registration.
* sasl-3.2 (and cap-3.2 / cap-notify), and SASL REAUTH through CAP NEW

**Comment by Mikaela** [comment]
> (such as the ECDSA one)

A little offtopic, but in case you are interested, ZNC won't be implementing it, because of the log at https://github.com/znc/znc/issues/746#issuecomment-119274435.

**Comment by dequis** [comment]
That's good to know. Basically the same reason ahf doesn't want it, nist curves. But still good to allow scripts to implement it since some people currently use it through cap_sasl.pl.

**Comment by Neustradamus** [comment]
Dear all,

I wish you a Happy New Year 2025!

Good news to all: @patrick-irc has added the SCRAM supports, thanks a lot!

It is not a joke: "Posted on April 1st 2024"
- https://irssi.org/2024/04/01/sasl-scram-sha-support/

It solves my initial request done 2020-04-20:
- https://github.com/irssi/irssi/issues/1178

Merged PR:
- https://github.com/irssi/irssi/pull/1500

Merged commits:
- https://github.com/irssi/irssi/commit/b18832bf3bcf3634373bcb5b46f33842762a09bb
- https://github.com/irssi/irssi/commit/f2b97631e1209d60e77f2a918809c88bd37fdd04
- https://github.com/irssi/irssi.github.io/commit/e54ff06fd0907e4dcccb9a064476cf0021375e12

Linked to:
- https://github.com/scram-sasl/info/issues/1
- https://github.com/irssi/irssi/issues/4
- https://github.com/irssi/irssi/issues/1331

cc: @dequis, @ircnet-com.
