### ISSUE TITLE
/names list isn't lined up properly if nicks are in UTF-8

### ISSUE THREAD

**Issue by andrewshadura** [irssi/irssi#40]
`fe-common/core/fe-channels.c:display_sorted_nicks()` isn't wide-character aware; thus, columns in `/names` list won't be properly aligned if any nicks have wide characters in them.

(Copied from the old bugtracker: FS#575)

**Comment by ailin-nemui** [comment]
care needs to be taken to use the wcwidth functions for screen alignment on terminals

**Comment by ailin-nemui** [comment]
@andrewshadura please test

**Comment by andrewshadura** [comment]
Cool, thanks, will test.

**Comment by ailin-nemui** [comment]
we believe this issue is now fixed, please reopen otherwise
