### ISSUE TITLE
Timeouts not copying variables

### ISSUE THREAD

**Issue by fullmetal1** [irssi/irssi#400]
running the code
```perl
use Irssi;

my $value = 1;
Irssi::timeout_add_once(1000, sub {Irssi::print"$value" }, []));
$value = 2
```
recreates the issue.

While I think everyone who uses this will expect and desire 1 to be printed out, instead, 2 will be printed. I suspect that this could have further ranging issues (segfaults or some shit if the variable gets dereferenced).

The obvious workaround
```perl
use Irssi;

my $value = 1;
my $temp = $value;
Irssi::timeout_add_once(1000, sub {Irssi::print"$temp" }, []));
$value = 2
```
works, and so that's what I've been using.

**Comment by LemonBoy** [comment]
Looks correct to me, the sub isn't evaluated until the timer fires and when that happens the value of `$value` is `2`.

**Comment by ailin-nemui** [comment]
sorry bro, that's how the programming language works

**Comment by ailin-nemui** [comment]
just in case you're still puzzled, the sub will never copy the variable. it will look into the value of `$variable` at the time it is run
