### ISSUE TITLE
Problem Irssi Fish

### ISSUE THREAD

**Issue by bibidinu** [irssi/irssi#403]
this is the problem when load script 
Irssi: Error loading module fish/fish: /root/.irssi/modules/libfish.so: undefined symbol: ischannel

**Comment by ailin-nemui** [comment]
replace `ischannel(...)` in the source code with `server_ischannel(server, ...)`

**Comment by ailin-nemui** [comment]
This is not an Irssi issue, you should take this issue to FiSH-irssi. Updates to Irssi require updates to modules.

**Comment by falsovsky** [comment]
Im currently working on this

**Comment by bibidinu** [comment]
tnx falsovsky!

**Comment by bibidinu** [comment]
i have changed ischannel to server_ischannel but now i have another error 
undefined symbol: mr_compare

**Comment by falsovsky** [comment]
My guess is that youre not using my maintained FiSH-irssi version, and using the older and unsupported that required miracl.

The newer one only uses OpenSSL and uses cmake for the build.

https://github.com/falsovsky/FiSH-irssi/

I'm currently trying to fix this bug.

**Comment by falsovsky** [comment]
Its fixed. Thanks to @ailin-nemui

**Comment by bibidinu** [comment]
ok try bro

**Comment by bibidinu** [comment]
with your version i have this problem on load 
 Irssi: fish/fish is ABI version 0 but Irssi is version 1, cannot load

**Comment by falsovsky** [comment]
I'm working on that one at the moment. Wait a few more minutes :-)

**Comment by falsovsky** [comment]
Just to report to you that I already fixed this. Thanks!
