### ISSUE TITLE
Allow reloading shell config

### ISSUE THREAD

**Issue by bitofhope** [irssi/irssi#418]
Running a program with /EXEC doesn't work if irssi is started before the command path is added in .${SHELL}rc
It would be good to have a way to reload the appropriate shell's environment.

**Comment by ailin-nemui** [comment]
you could start irssi after loading your shell profile, or make a wrapper script that first loads it and then starts irssi

**Comment by dequis** [comment]
Reloading the shell "config" requires a shell script interpreter. It's not something irssi should do.
