### ISSUE TITLE
How to use irssi via a proxy

### ISSUE THREAD

**Issue by TommyJerryMairo** [irssi/irssi#424]
Hello.
I have read the proxy.txt in doc file. 
But it is something about set up a proxy.
I have noticed that in the config file of irssi, 
there are something like "proxy_address","proxy_port","use_proxy".
So, I believe that irssi can connect to irc server via proxy.
But, socks5 http https proxies are not what it need.

I guess that the proxy is a bouncer, isn't it?
But, a bouncer can be connected directly.
So, I wander what the proxy is?
And whether the proxy is the proxy set up by another irssi?

And, finally, how to make a socks5 proxy as a irssi origin proxy, with hooks or LD_PRELOAD ?

**Comment by vague666** [comment]
The proxy settings in irssi refer to http proxies, if you want to use irssi with socks5 then you need to compile irssi with the --with-proxy compiler flag, configure dante on your system to connect to the socks5 proxy, and then start irssi with socksify irssi (or similar)

**Comment by ailin-nemui** [comment]
https://irssi.org/documentation/startup/#proxies-and-irc-bouncers explains how to use the proxy settings

the easiest way to use socks5 is to use the [proxychains-ng](https://github.com/rofl0r/proxychains-ng) LD_PRELOAD wrapper. Otherwise as vague explained, if you compile irssi with --enable-socks, it will respect your /etc/socks.conf

**Comment by ailin-nemui** [comment]
https://github.com/irssi/irssi/blob/master/docs/proxy.txt explains about the proxy-bnc module which turns irssi into a bnc

**Comment by ysangkok** [comment]
irssi master from today reports `configure: WARNING: unrecognized options: --enable-socks`

**Comment by ailin-nemui** [comment]
Please use proxychains-ng unless someone contributes native proxy support

**Comment by frozen-cdn** [comment]
Why is this marked closed?
Has this project been abandoned?

**Comment by vague666** [comment]
@ailin-nemui has done some work which might help with socks proxies, you are welcome to try https://github.com/irssi/irssi/pull/1603
