### ISSUE TITLE
Can irssi be compiled against non-openssl ssl library targets?

### ISSUE THREAD

**Issue by geekpete** [irssi/irssi#433]
Such as 
- libressl
- polarssl
- boringssl

?

**Comment by geekpete** [comment]
Seems installing libressl from source masquerades as openssl for compatibility, so after that irssi didn't throw an error. I'll post my instructions here after I confirm.

**Comment by dequis** [comment]
LibreSSL is mostly compatible.

BoringSSL broke backwards compatibility intentionally which is the main reason it's a fork, and it's not really intended to be used by the general public outside of google products.

PolarSSL is an unrelated library and has a different API.

**Comment by ailin-nemui** [comment]
what's the point of this question?

**Comment by geekpete** [comment]
People might want alternatives to using openssl due to security flaws that will continually keep arising due to design and legacy code in that library.

Are alternatives to using openssl tested/supported?

Seems the only real alternative is libressl and it fails to compile for me, failing at the perl part of the make.

**Comment by dequis** [comment]
>it fails to compile for me, failing at the perl part of the make.

Error message?

**Comment by geekpete** [comment]
I'm on OSX, so probably a missing library or something I could snag the source for and install (like perl):

```
Making all in perl
for dir in common irc ui textui; do \
	  cd $dir && \
	  if [ ! -f Makefile ]; then \
	    /usr/bin/perl Makefile.PL ; \
	  fi && \
	  (/Applications/Xcode.app/Contents/Developer/usr/bin/make CC="gcc" CCFLAGS="-arch x86_64 -arch i386 -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -g -O2 -Wall -I/usr/local/include" CCCDLFLAGS="-fPIC" || \
	   /Applications/Xcode.app/Contents/Developer/usr/bin/make CC="gcc" CCFLAGS="-arch x86_64 -arch i386 -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -g -O2 -Wall -I/usr/local/include" CCCDLFLAGS="-fPIC") && \
	  cd ..; \
	done
Making all in fe-text
  CCLD     irssi
Undefined symbols for architecture x86_64:
  "_tgetent", referenced from:
      _terminfo_core_init in terminfo-core.o
  "_tgetflag", referenced from:
      _terminfo_core_init in terminfo-core.o
  "_tgetnum", referenced from:
      _terminfo_core_init in terminfo-core.o
  "_tgetstr", referenced from:
      _terminfo_core_init in terminfo-core.o
  "_tputs", referenced from:
      _term_set_bracketed_paste_mode in term-terminfo.o
      __set_fg in terminfo-core.o
      __set_bg in terminfo-core.o
      _terminfo_cont in terminfo-core.o
      _terminfo_stop in terminfo-core.o
      __move_cup in terminfo-core.o
      __move_pa in terminfo-core.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [irssi] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by dequis** [comment]
Does it build fine if you don't do anything weird related to ssl?

**Comment by geekpete** [comment]
I'll grab openssl source and compile/install and see if it still breaks.

**Comment by dequis** [comment]
You don't need the openssl source to build irssi...

**Comment by geekpete** [comment]
Did a make clean, then ./configure
Then make fails with:
```
network-openssl.c:28:10: fatal error: 'openssl/crypto.h' file not found
#include <openssl/crypto.h>
```

**Comment by dequis** [comment]
You need the openssl headers, not the source. I'd recommend to use homebrew for builds unless you know exactly what's needed.

Anyway this isn't really related to irssi and I don't even use OSX myself, so I'm closing this. Ask on irc if you have more questions.
