### ISSUE TITLE
Window input history works strangely with window history cleared

### ISSUE THREAD

**Issue by vague666** [irssi/irssi#462]
to reproduce:
- join a new channel or issue /window history -clear
- enter text but don't press enter
- press arrow up
- return to the text you entered... you would assume you'd get to it by arrow down but you are now at 
  the start of the history buffer and have to press up to get to the text which is a bit confusing

not sure if this can be improved though, maybe arrow up should be 'stopped' if there's no more items in history?

**Comment by LemonBoy** [comment]
Have a look at how the `over_counter` field in `HISTORY_REC` is used in `command_history_prev`, I do agree the current behaviour is confusing and not very useful

**Comment by ailin-nemui** [comment]
additional information it seems to work "right" when the history isn't empty
