### ISSUE TITLE
can't compile irssi -- ./configure fails

### ISSUE THREAD

**Issue by ticklemynausea** [irssi/irssi#469]
Hi. I can't figure out why this is happening. When running `./configure` the following happens and the process stops:

```
...
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking sys/utsname.h usability... yes
checking sys/utsname.h presence... yes
checking for sys/utsname.h... yes
checking regex.h usability... yes
checking regex.h presence... yes
checking for regex.h... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for library containing socket... none required
checking for library containing inet_addr... none required
checking for socklen_t... yes
checking size of int... 4
checking size of long... 8
checking size of long long... 8
checking size of off_t... 8
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.7... yes
checking for GLIB - version >= 2.16.0... yes (version 2.32.4)
checking for SSL... yes
configure: checking "location of ncurses.h file"...
Found ncurses on /usr/include/ncurses.h
checking for initscr in -lncurses... yes
checking for setupterm... yes
checking for working Perl support... ok
checking that generated files are newer than configure... done
configure: creating ./config.status
.in'ig.status: error: cannot find input file: `
```

Running debian 8.

**Comment by dequis** [comment]
How did you download the source code?

**Comment by ticklemynausea** [comment]
fresh git clone from default branch

**Comment by ailin-nemui** [comment]
then you shouldn't even have a ./configure

**Comment by ailin-nemui** [comment]
please provide full log for example `./autogen.sh 2>&1 | tee configure.logfile`

**Comment by ticklemynausea** [comment]
What do you mean? The configure script is generated after running
`./autogen.sh`

On Mon, Apr 18, 2016 at 12:10 PM, ailin-nemui <notifications@github.com>
wrote:

> then you shouldn't even have a ./configure
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/irssi/irssi/issues/469#issuecomment-211332231>
>



-- 
Cumprimentos,
Mário Carneiro

http://mariocarneiro.info

**Comment by ticklemynausea** [comment]
As requested:
https://gist.github.com/ticklemynausea/279a62ac54f92170fc486caa8412079d

On Mon, Apr 18, 2016 at 12:11 PM, ailin-nemui <notifications@github.com>
wrote:

> please provide full log for example ./autogen.sh 2>&1 | tee
> configure.logfile
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/irssi/irssi/issues/469#issuecomment-211332904>
>



-- 
Cumprimentos,
Mário Carneiro

http://mariocarneiro.info

**Comment by ailin-nemui** [comment]
ok weird error haven't seen that before and cannot find anything about it on google. can you please provide additional info: `autoreconf --version`, a copy of config.log and irssi-version.h, and the output of `export`

**Comment by dequis** [comment]
I just got a clean debian 8 docker container and installed it in there without issues ([unedited shell history](http://dump.dequis.org/wqz2U.txt))

Google seems to suggest that this kind of error is due to the configure script having DOS style newlines. Which makes sense for cygwin but not here. Are you using a weird filesystem, like fat, ntfs, cifs, or something fuse based?

**Comment by ailin-nemui** [comment]
may also be helpful: `git status` output

**Comment by ticklemynausea** [comment]
This is happening on an environment I've used for ages, updating irssi from
source without any kind of issues up to this one.

My filesystem is ext4.

Here are config.log and irssi-version.sh:
https://gist.github.com/ticklemynausea/2fe77b434582e070de2f07b0b2cdea18


````
$ autoreconf --version
autoreconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html
>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
````


````
$ git status
# On branch master
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       configure.logfile
nothing added to commit but untracked files present (use "git add" to track)
````

````
$ export
declare -x HOME="/home/mario"
declare -x LANG="en_US.UTF-8"
declare -x LANGUAGE="en_US:en"
declare -x LOGNAME="mario"
declare -x
LS_COLORS="rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:"
declare -x MAIL="/var/mail/mario"
declare -x
NODE_PATH="/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript"
declare -x OLDPWD="/home/mario/sources"
declare -x
PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/mario/.scripts:/home/mario/.bin:/home/mario/.composer/vendor/bin"
declare -x PWD="/home/mario/sources/irssi"
declare -x SHELL="/bin/bash"
declare -x SHLVL="2"
declare -x STY="4604.startup"
declare -x TERM="screen-256color"
declare -x TERMCAP="SC|screen-256color|VT 100/ANSI X3.64 virtual terminal:\\
        :DO=\\E[%dB:LE=\\E[%dD:RI=\\E[%dC:UP=\\E[%dA:bs:bt=\\E[Z:\\
        :cd=\\E[J:ce=\\E[K:cl=\\E[H\\E[J:cm=\\E[%i%d;%dH:ct=\\E[3g:\\
        :do=^J:nd=\\E[C:pt:rc=\\E8:rs=\\Ec:sc=\\E7:st=\\EH:up=\\EM:\\
        :le=^H:bl=^G:cr=^M:it#8:ho=\\E[H:nw=\\EE:ta=^I:is=\\E)0:\\
        :li#66:co#274:am:xn:xv:LP:sr=\\EM:al=\\E[L:AL=\\E[%dL:\\
        :cs=\\E[%i%d;%dr:dl=\\E[M:DL=\\E[%dM:dc=\\E[P:DC=\\E[%dP:\\
        :im=\\E[4h:ei=\\E[4l:mi:IC=\\E[%d@:ks=\\E[?1h\\E=:\\
        :ke=\\E[?1l\\E>:vi=\\E[?25l:ve=\\E[34h\\E[?25h:vs=\\E[34l:\\
        :ti=\\E[?1049h:te=\\E[?1049l:us=\\E[4m:ue=\\E[24m:so=\\E[3m:\\
        :se=\\E[23m:mb=\\E[5m:md=\\E[1m:mr=\\E[7m:me=\\E[m:ms:\\
        :Co#8:pa#64:AF=\\E[3%dm:AB=\\E[4%dm:op=\\E[39;49m:AX:\\
        :vb=\\Eg:G0:as=\\E(0:ae=\\E(B:\\

:ac=\\140\\140aaffggjjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~..--++,,hhII00:\\
        :Km=\\E[M:k0=\\E[10~:k1=\\EOP:k2=\\EOQ:k3=\\EOR:k4=\\EOS:\\
        :k5=\\E[15~:k6=\\E[17~:k7=\\E[18~:k8=\\E[19~:k9=\\E[20~:\\
        :k;=\\E[21~:F1=\\E[23~:F2=\\E[24~:kb=:kB=\\E[Z:kh=\\E[1~:\\
        :@1=\\E[1~:kH=\\E[4~:@7=\\E[4~:kN=\\E[6~:kP=\\E[5~:kI=\\E[2~:\\
        :kD=\\E[3~:ku=\\EOA:kd=\\EOB:kr=\\EOC:kl=\\EOD:km:"
declare -x USER="mario"
declare -x WINDOW="4"
declare -x
XDG_SESSION_COOKIE="3ccf46fa2a98cfd0541f14ba51d4b40d-1460576446.33268-2023681712"

````

On Mon, Apr 18, 2016 at 12:28 PM, ailin-nemui <notifications@github.com>
wrote:

> may also be helpful: git status output
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/irssi/irssi/issues/469#issuecomment-211338727>
>



-- 
Cumprimentos,
Mário Carneiro

http://mariocarneiro.info

**Comment by dequis** [comment]
The log says you have gcc 4.7.2 which is the version from debian 7, while debian 8 includes 4.9.2

Also I just noticed

```
checking for GLIB - version >= 2.16.0... yes (version 2.32.4)
```

That's the version from debian 7 too

**Comment by ailin-nemui** [comment]
if the problem persists may I recommend reinstalling your computer. feel free to post `bash -x ./config.status >confistatus.trace 2>&1`  and I'll take a glimpse but I've no idea where things go wrong on your system

**Comment by dequis** [comment]
Maybe upload the whole configure and config.status files so i diff them with the ones generated by this clean install? Or just tar and upload the whole build tree.

I've got this in line 1163, while the error log points at line 1164.

```
	   as_fn_error 1 "cannot find input file: \`$ac_f'" "$LINENO" 5;;
```

No idea what that part even does. Autoconf works in mysterious ways.

**Comment by ticklemynausea** [comment]
Pardon me, I do have debian 7, not 8.

configure and config.status:
https://gist.github.com/ticklemynausea/0ed0094cb82e1d4ab24be439fb92b764

The config.status trace:
https://gist.github.com/ticklemynausea/975d9f230e352ac31e4d4f7e7db81a71


On Mon, Apr 18, 2016 at 1:51 PM, dx <notifications@github.com> wrote:

> Maybe upload the whole configure and config.status files so i diff them
> with the ones generated by this clean install? Or just tar and upload the
> whole build tree.
>
> I've got this in line 1163, while the error log points at line 1164.
>
>        as_fn_error 1 "cannot find input file: \`$ac_f'" "$LINENO" 5;;
>
> No idea what that part even does. Autoconf works in mysterious ways.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/irssi/irssi/issues/469#issuecomment-211367411>
>



-- 
Cumprimentos,
Mário Carneiro

http://mariocarneiro.info

**Comment by ticklemynausea** [comment]
>if the problem persists may I recommend reinstalling your computer.

I'm sorry, but my system is fine

**Comment by dequis** [comment]
Mine: [config.status](http://dump.dequis.org/Nqj4E.txt), [configure](http://dump.dequis.org/jnOPs.txt)

Where did you get that automake 1.14 from? Debian 7 has 1.11 only.

That configure file does have DOS-style newlines. How did that even happen? There's also a few random `\r` characters embedded in list of files.

**Comment by ailin-nemui** [comment]
those \r characters are ultimately your issue here but it's quite suspicious that we cannot reproduce this issue on plain Debian installs, so I'm afraid to say that but all hints point to something peculiar on your system

**Comment by ticklemynausea** [comment]
Good catch on those CR characters. I actually solved this by doing `git config --global core.autocrlf false` before cloning the repository. How this setting got there in the first place, I don't know.

Thanks!

**Comment by ailin-nemui** [comment]
glad you could solve the issue
