### ISSUE TITLE
.gitignore missing some files in docs?

### ISSUE THREAD

**Issue by justinsteven** [irssi/irssi#470]
After configure and make, git is worried about some untracked files in docs:

```
% git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        docs/help/in/Makefile
        docs/help/in/Makefile.in

nothing added to commit but untracked files present (use "git add" to track)
```

Should .gitignore be updated to include them?

**Comment by ailin-nemui** [comment]
weird, I don't see that. what's your git version? (2.8.1 here). Makefile and Makefile.in are already listed in .gitignore

**Comment by justinsteven** [comment]
https://github.com/irssi/irssi/blob/0e5a32fb624892131b6138652061bd1611c11db8/.gitignore#L31 then seems to unignores files in docs/help/in

I'm not 100% on precedence of gitignore rules

I'm on git 2.8.0.rc3 (Debian)

Do those files in docs/help/in exist in your local repo?

**Comment by ailin-nemui** [comment]
see 5cee349 in https://github.com/git/git/compare/v2.8.0-rc3...v2.8.0 so I'll close this as a git bug
