### ISSUE TITLE
*** glibc detected *** irssi: corrupted double-linked list: 0x09e4d538 **

### ISSUE THREAD

**Issue by RogerCageot** [irssi/irssi#483]
When pushing a special line on public or private msg, clients are killed.

Issue occur on v.0.8.15 & maybe on other versions.

No issues on v.0.8.17.

Regards

**Comment by LemonBoy** [comment]
If the issue is not reproducible on the latest version (which is `0.8.19`) then the bug report is invalid.

**Comment by ailin-nemui** [comment]
What special line?

**Comment by RogerCageot** [comment]
A crafted ANSI line.

**Comment by ailin-nemui** [comment]
Can you send me the line to ailin AT devio DOT us so I can verify?

**Comment by ailin-nemui** [comment]
hi, it does not crash my irssi.

can you share more info:
- how was your irssi compiled?
- which distribution?
- loaded plugins (output of /load),
- loaded scripts (output of /script),
- was it enough to send this line, or any other steps involved?
- does it crash every time or just sometimes?

thanks

**Comment by RogerCageot** [comment]
* Was compiled with regular installation instructions without any special configure options
* Debian 8.4
* Module               Type    Submodules
  core                    static    core irc fe fe-irc fe-text
  dcc                     static     irc fe-irc
  flood                   static     irc
  notifylist              static     irc fe-irc
  perl                     static     core fe
  fish                     dynamic core
* Loaded scripts:
  dispatch        /home/****/.irssi/scripts/autorun/dispatch.pl
* No other steps involved, only this line
* It crash every time

**Comment by dequis** [comment]
>fish

**Comment by ailin-nemui** [comment]
can you try if it crashes without fish @RogerCageot ?

**Comment by falsovsky** [comment]
Probably youre using an older version of FiSH. Please try the one that I maintain.

If its fish related, post an issue there.

https://github.com/falsovsky/FiSH-irssi

**Comment by RogerCageot** [comment]
@ailin-nemui : i ve tested without fish & it don t crash so it s seems it s fish related.

@falsovsky : seems it s fish related, let me post the issue

**Comment by dequis** [comment]
New ticket is https://github.com/falsovsky/FiSH-irssi/issues/39
