### ISSUE TITLE
perl version mismatch

### ISSUE THREAD

**Issue by jimerickson** [irssi/irssi#497]
Version of perl module (20011220) doesn't match the version of Irssi library (20011217) at /usr/local/lib64/perl5/Irssi.pm line 165.

getting this error at start of irssi 0.8.20-head (fd371cc) on fedora 24 rc 1.2. if i fall back to irssi 0.8.20-g0e5a32f (20160407 1233) it works flawlessly. can anyone help with this?

**Comment by ailin-nemui** [comment]
you need to install the correct Perl module version together with Irssi. make install usually takes care of that. To manually clean out incorrect modules, `find -name Irssi -o name Irssi.\* -exec rm -fr {} +`  may help
