### ISSUE TITLE
What happened to irssi_0_8_12_setup_2.exe?

### ISSUE THREAD

**Issue by fratertenc** [irssi/irssi#502]
There used to be, on the main irssi page, a Windows binary installer. I still have it and am re-hosting it on my own server... but why isn't it on your server anymore? Maybe it's dated but it still works and should be at least available for people who don't want to go through the living hell that is Cygwin...

Thanks.

**Comment by q3aql** [comment]
@fratertenc I have my own Irssi builds that don't require Cygwin, but I haven't managed to compile support for perl.

* [irssi-0.8.19-win-32bit-build1.7z](https://github.com/q3aql/irssi-win/releases/download/v0.8.19/irssi-0.8.19-win-32bit-build1.7z)
* [irssi-0.8.19-win-64bit-build1.7z](https://github.com/q3aql/irssi-win/releases/download/v0.8.19/irssi-0.8.19-win-64bit-build1.7z)

https://github.com/q3aql/irssi-win

**Comment by ailin-nemui** [comment]
As far as I know - correct me if wrong - that installer includes a mini cygwin. For this reason we would prefer strongly that people just installed the *most recent* irssi from cygwin's setup.exe

**Comment by q3aql** [comment]
@ailin-nemui Exactly, this package includes a "mini cygwin" to run irssi.

**Comment by ailin-nemui** [comment]
so as far as I can tell, that is not much different from using cygwin's setup.exe and only selecting the mintty+irssi packages in the package installer step

**Comment by q3aql** [comment]
@ailin-nemui If you select mintty + irssi, cygwin not only will install 2 packages, will install much more libraries and packages and the installing will have more than 300MB on hard-disk. With this package you have irssi with 10MB (decompressed).

**Comment by ailin-nemui** [comment]
Afaik Perl itself is ~160MB and personally I like being able to extend irssi with scripts, so the size issue quickly becomes moot

**Comment by fratertenc** [comment]
@q3aql - Thank you, I appreciate it. Here's where I also found the specific .exe I mentioned online.
[http://files.bluecrow.net/irc/irssi/](http://files.bluecrow.net/irc/irssi/)
@ailin-nemui I'm not sure about scripts per say in the one which q3 has made, or the one I'm talking about which I installed and use fine, but themes do work just so you know. /set theme <themename>
