### ISSUE TITLE
/help SERVER ADD -port and -! examples incorrect

### ISSUE THREAD

**Issue by johannes87** [irssi/irssi#519]
To reproduce:

```
/network add hackint
/server add -ssl -network hackint -port 9999 irc.hackint.org
/connect hackint
```

Irssi then connects to irc.hackint.org on port 6667. Tested with irssi 0.8.19 on OS X 10.11.

**Comment by dequis** [comment]
Quoting from #256:

>not saying it makes sense, but the reason for this is that `-port` is for modifying an entry and `<address> <port>` is for adding an entry. Example:
>
>`/server add -network net1 example.com 6697` # add server of network 1
>`/server add -network net2 example.com 6698` # add server of network 2
>`/server add -port 6667 example.com` # modify port of server in network **2**
>`/server add -port 6668 example.com 6697` # modify port of server in network **1**

**Comment by johannes87** [comment]
Thanks. Still, the documentation seems to be wrong. It lists the following command in the examples:

`/SERVER` ADD -! -auto -host staff.irssi.org -port 6667 -4 -network Freenode -noproxy orwell.freenode.net`

This suggests that "-port" does set the initial port. At least the example should be changed to remove the "-port 6667" IMHO:

`/SERVER` ADD -! -auto -host staff.irssi.org -4 -network Freenode -noproxy orwell.freenode.net 6667`

**Comment by ailin-nemui** [comment]
the help is totally wrong
