### ISSUE TITLE
/set expand_escapes ON doesn't handle double-escaping ("\\n")

### ISSUE THREAD

**Issue by tjt263** [irssi/irssi#520]
`/set expand_escapes = ON` is great. 
It allows things like line-breaks to be embedded in regular messages (with `\n`) for instance.

The issue is that it currently cannot be double-escaped (`\\n`) to prevent expansion, as is the common convention. (i.e. `\\n` should render as simply `\n` and so on).

That is all. 
Cheers.

**Comment by ailin-nemui** [comment]
developer info: handling of expand_escapes in  `src/core/misc.c` is intermingled with parse_special_string (which does the `\\` replacement), need to be careful when untangling that
