### ISSUE TITLE
Kill bell_beeps setting (or make it a no-op)

### ISSUE THREAD

**Issue by dequis** [irssi/irssi#524]
It doesn't do what people think it does.

People enable it expecting it to enable beeps when they get highlighted. It's not for that.

It's for beeping when anyone in any window sends a ^G character (ascii bell) - and that's without changing the activity level of the window in which it happened.

It's dumb and only trolls ever use it. Also, plenty of guides suggest people to turn it on, ignoring the real effect of doing so.

Any objections to nuke it? Any useful purpose for this setting that I'm missing?

**Comment by vague666** [comment]
Why not rename it to beep_on_ascii_bel or similar? Maybe somebody finds it useful for some reason?

**Comment by dequis** [comment]
I really doubt it can be useful ever. A "maybe" isn't enough. I'm looking for concrete use cases, if they even exist.

Also, even that name is ambiguous. For example, in one of the pages that suggests enabling this, someone tried to explain how enabling this setting is a bad idea, by saying "It actually does something far worse. It makes the beep control code send a beep to your terminal", and the author of the post replied:

>How is that worse? That’s what I wanted personally – it’s (AFAIK) the only way a console app can make a sound!

To be fair, it wasn't the best explanation of the issue, but it was ambiguous in the same way that `beep_on_ascii_bel`  is.

**Comment by ahf** [comment]
I'm fine with killing it.

**Comment by jimenezrick** [comment]
This is a bit of arcane UNIX convention but it's handy when a terminal program can send the bell signal and you can use that in different ways. I personally let my terminal raise the urgent flag so my window manager notifies there is activity in that window:
```
URxvt.urgentOnBell:     true
```

Are we losing this functionality then? Because I think this is a mistake.

**Comment by madduck** [comment]
I'm with @jimenezrick and certainly appreciate the urgency flag being set on specific activity. However, I think this should only be done on specific activity, and certainly not by trolls with `^G`.
