### ISSUE TITLE
+channel

### ISSUE THREAD

**Issue by bw1** [irssi/irssi#531]
> /j +test
> **15:54 < test_u:+test> hallo**
> 15:55  * test_u hello

[e480b9b]

[http://bugs.irssi.org/index.php?do=details&task_id=160&project=5&pagenum=7]

**Comment by LemonBoy** [comment]
What irssi version are you using? Does this happen with the latest one from git? Can you please show us the `STATUSMSG` and `CHANTYPES` for this server ?

**Comment by bw1** [comment]
Irssi v0.8.19
irssi 0.8.20-g17f4bd2

ircnet
> RFC2812 PREFIX=(ov)@+ CHANTYPES=#&!+ MODES=3 CHANLIMIT=#&!+:42 NICKLEN=15 
>          TOPICLEN=255 KICKLEN=255 MAXLIST=beIR:64 CHANNELLEN=50 IDCHAN=!:5 
>          CHANMODES=beIR,k,l,imnpstaqr are supported by this server

**Comment by dequis** [comment]
Uh.. what is the issue here? The ticket from the old tracker doesn't seem relevant to the STATUSMSG changes at all

**Comment by LemonBoy** [comment]
Can you please check if #533 solves the problem for you ?

**Comment by bw1** [comment]
thx dequis 

solved!
