### ISSUE TITLE
A command that sends a message to a specific server/channel

### ISSUE THREAD

**Issue by hannsen** [irssi/irssi#536]
Hey, so I am a beginner to irssi.

I was wondering if there was a command to send to a specific server and channel.

what I am trying to do is that trigger.pl can send a message to this specific server, even if it is not the one triggering it.

or maybe one could edit this basic /hello script:

```
# Usage: /HELLO [<nick>]
sub cmd_hello {
# data - contains the parameters for /HELLO
# server - the active server in window
# witem - the active window item (eg. channel, query)
#         or undef if the window is empty
my ($data, $server, $witem) = @_;

if (!$server || !$server->{connected}) {
  Irssi::print("Not connected to server");
  return;
}

if ($data) {
  $server->command("MSG $data Hello!");
} elsif ($witem && ($witem->{type} eq "CHANNEL" ||
					$witem->{type} eq "QUERY")) {
  # there's query/channel active in window
  $witem->command("MSG ".$witem->{name}." Hello!");
} else {
  Irssi::print("Nick not given, and no active channel/query in window");
}
}

Irssi::command_bind('hello', 'cmd_hello');
```

I know it should be easy somehow, but I am not accustomed to perl nor irssi api.

**Comment by hannsen** [comment]
solved with 
/msg #CHANNELNAME blablabla

**Comment by hannsen** [comment]
when it do /msg -SERVER #channel blalblabla

it works when I do it, but when I let triggers.pl do it, it just creates a new #channel with me as op and posts there

**Comment by dequis** [comment]
You'll get faster answers if you use the irc channel instead of the bug tracker

**Comment by ailin-nemui** [comment]
is this still an issue?
