### ISSUE TITLE
CHANTYPES not properly supported

### ISSUE THREAD

**Issue by kaniini** [irssi/irssi#545]
Seems Irssi does not properly support `CHANTYPES` from 005.

On a server where for example `CHANTYPES` includes `>`, doing `/join >moo` does not work, and you have to do `/quote join >moo`.  An example of this can be seen by installing charybdis 4 and loading the `extensions/chantype_dummy` module which defines the `>` channel type.

**Comment by LemonBoy** [comment]
Could you please provide the irssi version you're using, a raw dump of the `005` command that's sent and explain how it "does not work" exactly ?

**Comment by kaniini** [comment]
15:48 -!- Irssi: Client: irssi 0.8.17 (20141011 1044)
15:48 -!- CPRIVMSG CNOTICE ETRACE KNOCK SAFELIST ELIST=CTU MONITOR=100 FNC WHOX CHANTYPES=#&> EXCEPTS INVEX are supported by this server

0.8.19 works though, so closing.
