### ISSUE TITLE
Reconnect failures create screen garbage

### ISSUE THREAD

**Issue by Olathe** [irssi/irssi#549]
If I use `/reconnect` repeatedly on a server that's down, I get something like the following:

    15:37 -!- Irssi: Looking up 10.40.40.40
    
    15:37 -!- Irssi: Reconnecting to 10.40.40.40 [10.40.40.40] port 7070 - use /RMRECONNS to abort
    15:37 -!- Irssi: Unable to connect server 10.40.40.40 port 7070 [No route to host]
    15:38 -!- Irssi: Removed reconnection to server 10.40.40.40 port 7070
    15:38 -!- Irssi: Looking up 10.40.40.40
    
    15:38 -!- Irssi: Reconnecting to 10.40.40.40 [10.40.40.40] port 7070 - use /RMRECONNS to abort
    15:38 -!- Irssi: Unable to connect server 10.40.40.40 port 7070 [No route to host]

When I use `/redraw`, the lines are redrawn without the empty lines:

    15:37 -!- Irssi: Looking up 10.40.40.40
    15:37 -!- Irssi: Reconnecting to 10.40.40.40 [10.40.40.40] port 7070 - use /RMRECONNS to abort
    15:37 -!- Irssi: Unable to connect server 10.40.40.40 port 7070 [No route to host]
    15:38 -!- Irssi: Removed reconnection to server 10.40.40.40 port 7070
    15:38 -!- Irssi: Looking up 10.40.40.40
    15:38 -!- Irssi: Reconnecting to 10.40.40.40 [10.40.40.40] port 7070 - use /RMRECONNS to abort
    15:38 -!- Irssi: Unable to connect server 10.40.40.40 port 7070 [No route to host]

A similar problem happens when the screen is filled (a quick way to get this is to do something like `/server help`) and I do the same thing.

    15:42 -!- Irssi: Removed reconnection to server 10.40.40.40 port 7070
    15:42 -!- Irssi: Looking up 10.40.40.40
    [(status [nickname] [1:network (change with ^X)]
    15:42 -!- Irssi: Reconnecting to 10.40.40.40 [10.40.40.40] port 7070 - use /RMRECONNS to abort
    15:42 -!- Irssi: Unable to connect server 10.40.40.40 port 7070 [No route to host]
    15:42 -!- Irssi: Removed reconnection to server 10.40.40.40 port 7070
    15:42 -!- Irssi: Looking up 10.40.40.40
             [nickname] [1:network (change with ^X)]
    15:42 -!- Irssi: Reconnecting to 10.40.40.40 [10.40.40.40] port 7070 - use /RMRECONNS to abort
    15:42 -!- Irssi: Unable to connect server 10.40.40.40 port 7070 [No route to host]

Note the extraneous lines aren't blank, but are copies of the contents of the status bar. Again, `/redraw` fixes the issue, removing the lines completely.

My irssi version is `irssi 0.8.19 (20160323 0008)`. I'm using it within tmux 2.1.

**Comment by dequis** [comment]
Probably mismatching $TERM, like TERM=xterm inside tmux or TERM=screen outside tmux, or whatever.

**Comment by Olathe** [comment]
`TERM` is set to `screen`, and the actual terminal is tmux 2.1.

I figured out the problem. It was running inside `torsocks` and that gives an error message to `stderr` when an unsupported system call, like a DNS query,  is made. When I run `irssi` outside of `torsocks`, everything is fine.

It can be fixed by running `torsocks` with the environment variable `TORSOCKS_LOG_LEVEL` set to `1`.
