### ISSUE TITLE
g_hash_table_lookup assertion on connection to network

### ISSUE THREAD

**Issue by MarioPereira** [irssi/irssi#553]
I'm using irssi 0.8.20 (20160914 1355) on Debian testing and started having the following errors when trying to connect to a network:

```
[ptirc] -!- Irssi: Looking up irc.ptirc.org
[ptirc] -!- Irssi: Connecting to irc.ptirc.org [91.92.109.25] port 6697
[ptirc] -!- Irssi: Connection to irc.ptirc.org established
[ptirc] -!- Irssi: Connection lost to irc.ptirc.org
-!- Irssi: critical g_hash_table_lookup: assertion 'hash_table != NULL' failed
-!- Irssi: critical g_hash_table_lookup: assertion 'hash_table != NULL' failed
```

The command that I use is ```/connect -ssl irc.ptirc.org```

Connections to other networks work without problem.

I'm able to connect if using other client, and do not know how long this could be happening because I keep irssi running inside a screen and rarely need to start it.

**Comment by ailin-nemui** [comment]
I have no troubles connecting to the irc.ptirc.org with irssi 0.8.20. could this be related to #466 ? can you try to obtain a rawlog. You can enable rawlog on connect with the following command:

     /script exec -perm Irssi::signal_add("server connected" => sub { $_[0]->command("rawlog open $_[0]{tag}.rawlog") })

**Comment by MarioPereira** [comment]
Well, I run your command and tryed to connect... It connected without error.
For what is worth, here is the raw log.

[ptirc.rawlog.txt](https://github.com/irssi/irssi/files/500927/ptirc.rawlog.txt)

Maybe it was some hicup of the network.

**Comment by ailin-nemui** [comment]
tell us more if you encounter the issue again. the "critical" is a warning that can be safely ignored for the moment
