### ISSUE TITLE
Consider switching to libucl

### ISSUE THREAD

**Issue by ahf** [irssi/irssi#561]
It looks like libucl have got support for keeping comment nodes in memory after parsing the config file so that they can be put back into the file when serialising the config back into a file.

The initial support was added in https://github.com/vstakhov/libucl/issues/65

Would be useful if someone could do a small research project to see if it was suitable for us to use!

**Comment by dequis** [comment]
Do we still want this? IIRC this was originally about throwing away the current config parser to replace it with a more robust one, not maintained by us, but the current one got enough fuzzing already imo.

**Comment by ahf** [comment]
I think unifying (outsourcing) our configuration file format to a "more" standardised library can still make sense - it is not a priority though.
