### ISSUE TITLE
I think I am asking a silly question

### ISSUE THREAD

**Issue by evilxyz** [irssi/irssi#566]
When I use 
```bash
/msg ChanServ mode #Channel +k password
```
set password to channel, and exit, then password lose efficacy... I have to set password again and stay at channel all time to make it efficacy... I have no idea to fix it ... asked google and #irssi channel.

**Comment by dequis** [comment]
>asked google and #irssi channel.

```
04:22 -!- evilxyz [~xyz@123.456.789.123] has joined #irssi
04:24 < evilxyz> guys, when i exit irssi, mode +k was lose efficacy... How to fix it
04:26 < evilxyz> guys, when i exit irssi, mode +k was lose efficacy... How to fix it ?
04:31  * evilxyz CRY
04:31 < evilxyz> Hello?
04:37 -!- evilxyz [~xyz@123.456.789.123] has left #irssi []
```

Next time wait more than 15 minutes before leaving the channel, especially when it's in the middle of the night of most european/american timezones.

Your question isn't specific to irssi but to the network you're using. In freenode (and most networks i'm in) there's no "mode" chanserv command. In the networks that do have a "mode" command, that syntax is incorrect. If you're not getting any error messages from using that command that way, ask in the help channel of the irc network you're using.

**Comment by evilxyz** [comment]
yeah, I write it wrong... but i run it right. This is what i want to write...
`/mode #Channel +k password`

but when i exit irssi, Channel password not working... and i dont know why and how to fix it .

I asked #freenode already... but nobody notice me...  

BTW You are a good guy :+1:

**Comment by deltab** [comment]
In standard IRC, a channel is created automatically when the first user joins it, and deleted when the last user leaves it. My guess is that your channel becomes empty after you disconnect, and so it gets deleted, including any modes set on it.

What you can do about this depends on the network. On some networks all you can do is keep a client (e.g. a bot) connected at all times. Other networks (including freenode) allow a channel to be registered with a network-run bot called ChanServ, which can then set modes automatically, or even stay in the channel permanently. Use `/msg chanserv help` to ask it for more details.

**Comment by evilxyz** [comment]
haha, I got it !  thx a lot !
```
/msg ChanServ SET ##evilxyz GUARD ON
```

**Comment by dequis** [comment]
Neat
