### ISSUE TITLE
Netjoins not shown in git versions

### ISSUE THREAD

**Issue by dequis** [irssi/irssi#567]
Netjoins are no longer visible after upgrading my production irssi to 538150c (from c8630ac)

Haven't done a regression test yet, but blaming #465 anyway.

**Comment by ailin-nemui** [comment]
@LemonBoy

**Comment by LemonBoy** [comment]
Wild guess, could it be [this](https://github.com/irssi/irssi/blob/master/src/fe-common/irc/fe-netsplit.c#L255) needs the `=` changed to `&` ?

**Comment by ailin-nemui** [comment]
@dequis can you test

**Comment by ailin-nemui** [comment]
was this confirmed fixed?

**Comment by dequis** [comment]
Yeah
