### ISSUE TITLE
CMake support in the future?

### ISSUE THREAD

**Issue by omtcyfz** [irssi/irssi#575]
Is CMake going to be supported at some point?

Along with numerous other advantages it would help to setup Clang-based tooling I'm used to. The way Clang-based tools treat project is a compilation database, which is generated via `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=On`. Without CMake I can't do that.

**Comment by ahf** [comment]
I don't believe this is a priority, no.

**Comment by dequis** [comment]
Calling it "not a priority" would be too generous IMO. My interest in switching build systems is not zero, it's negative.

**Comment by omtcyfz** [comment]
Alright...

**Comment by dequis** [comment]
BTW, you might be interested in https://github.com/rizsotto/Bear to generate the compilation database
