### ISSUE TITLE
Set a default irssi windows limit

### ISSUE THREAD

**Issue by juhanurmi** [irssi/irssi#582]
Hi,

Yesterday an attacker opened 1000+ private msg windows and my irssi completely froze for several minutes when I tried to close even one of these msg windows. When I tried to close many of them at once with `/window close 50 100` command irssi consumed 100% of CPU and didn't seem to recover even after one hour.

Because it's inconvenient that the attacker is able to open 1000+ pm msg windows and it is impossible to close them would it be possible to set some default limit to number of windows?

For instance, 100 by default and when number of windows reach 90 irssi will say "hey, you can lift window limit from 100 to 200 by typing `/window limit=200`.

Thanks,
Juha

**Comment by ahf** [comment]
I think first and foremost we should fix the weird `O(n^2)` (or was it worse?) behaviour we have for certain operations on our window list, if possible.

**Comment by mrc0mmand** [comment]
I have the exactly same problem. Yesterday, the OFTC network was under a botnet attack and my irssi ended up with ~3.5k query windows. Apart from the fact, that it froze every ten seconds, closing the first ~170 windows caused the same situation - the irssi just froze completely, kept using 100% CPU and apparently did nothing at all (even strace didn't show any activity).

I'm not sure about the window limit idea, you would have to somehow notify the other side about the fact, that the query window couldn't be opened (or the message would be lost forever). I'd like to know, why the irssi got stuck when doing such, let's say 'primitive' operation. Maybe fixing that would be a better solution.

**Comment by spaam** [comment]
i had the same issue yesterday. after waiting 30min i looked at the irssi process with strace. it was showing a lot of stat syscalls to /etc/localtime.
