### ISSUE TITLE
ircd-hybrid's challenge.pl (old rsa oper challenge) doesn't react to enter

### ISSUE THREAD

**Issue by dequis** [irssi/irssi#584]
Regression between 0.8.17 and 0.8.18, bisect says #283 (Clear the ICRNL flag), poke @LemonBoy 

**Steps to reproduce:**

1. Load [challenge.pl](https://tomaw.net/~tom/challenge.pl)

2. Build [respond.c](https://raw.githubusercontent.com/oftc/oftc-hybrid/develop/tools/rsa_respond/respond.c) with `gcc $(pkg-config --cflags --libs openssl) respond.c -o rsa_respond`

3. `/set challenge_rsa_path /path/to/that/rsa_respond`

4. `(echo 001 a; read; echo '386 a :a'; read) | nc -l -p 6667`

5. `/connect localhost`

6. `/cr aa`

7. Press enter in netcat

8. At the "Enter passphrase for challenge:" prompt, press enter.

**Expected result:**

* Input is cleared
* netcat receives `challenge +Could not open the private keyfile.` or similar

**Actual result:**

* Door stuck.

**Workaround:**

* Press CTRL-J instead of enter.

**Other notes:**

The script is terrible, does awful things, has stale crypto (RSA PKCS#1 v1.5), and totally deserves being broken like this. Justice has been served. Except not really, just kidding. Before discovering the CTRL-J workaround today, they were handling this by killing the child process because irssi appeared to be hung.

It is not in s.i.o but seems to be included in the debian and ubuntu irssi-scripts package (even though it's useless by itself without the external C program). It also seems to be distributed internally by opers of networks that support this feature.

It's hard to tell which networks other than oftc support this - ratbox (one of the biggest forks of hybrid) added an incompatible challenge method using the numeric 740 `RPL_RSACHALLENGE2` as opposed to hybrid's 386 `RPL_RSACHALLENGE`, but it looks the same from outside. So, for example, freenode doesn't use this.

Reverting this change would suck and I'm not sure if fixing the script is enough.

How about doing something like `/set term_icrnl` defaulting to OFF just like we did with term_appkey_mode?

My idea of fixing is calling `stty`. Better ideas welcome. It gets stuck in the `getpass()` C function. Rewriting it to not call an external C program would be cool too, but can't say i'm willing to go that far.

**Comment by ailin-nemui** [comment]
as you noted the script is broken in several ways. having one additional ctrl key binding available in irssi seems useful. The respond program could just set and restore terminal state. It would be nice if irssi could detect when a program is shelled out to so it could do the re-setting, but I don't see that particularly feasible. I don't think we need even more settings

**Comment by LemonBoy** [comment]
Uh, this sucks, but I think the workaround isn't that bad (at least not as bad as the script itself) and could be mitigated by adding a note to use `^J` instead of `Enter`.
Do we have any real-world user of this script ?

**Comment by tomaw** [comment]
It's used by some OFTC staff and possibly opers on other networks that use similar auth.

**Comment by ChristophBerg** [comment]
I'm using it, thanks for tracking down why it doesn't work on my notebook...

**Comment by ailin-nemui** [comment]
shouldn't be that hard to add the save,set,restore code into the respond program

**Comment by ahf** [comment]
Wont it need to be replicated for every version of the respond program? If this origins from ircd-hybrid, then quite a lot of ircd's might ship with it?

**Comment by ailin-nemui** [comment]
it is also easy to fix it in the script. ``my $irssi_stty = `stty -g`; `stty icrnl`;``, shell out, `` `stty $irssi_stty`;``

**Comment by dequis** [comment]
Yeah I'm leaning to fix the script with stty, give tomaw the fixed one, and forget about it. (Well, also poke rhonda to include the fix in the ubuntu/debian package)

**Comment by Ganneff** [comment]
Me being the original author of this script, I may point at the version number. It is alpha.
It's possible crap and can be written in tons of nicer ways. Feel free to. :)

Yet, it gets its job done since 2006, basically unmodified since then.

And now, modified, the stty suggestions make it somewhat more ugly, but work again.

I put it over there: http://kosh.ganneff.de/~joerg/paste/2016-12-12-x1KdYNsEgRE/challenge.pl

**Comment by dequis** [comment]
Thanks! And sorry for the harsh words against the script.

Also thanks for filing the debian bug. I poked rhonda about it but she's the maintainer of irssi, not irssi-scripts, so not sure if that helps at all.

I think this can be considered done, right?

**Comment by Ganneff** [comment]
Bah, no need to be sorry. That script is a hack. Shelling out to another binary has a load of problems (forget to answer the challenge a little and irssi loses its connections, for one), and someone with time could probably write a nicer implementation in pure perl. Or redo the whole thing (ie also server side) with something that doesnt limit your key length to irc message length...

Still, it is nicer (IMO!) than plain /oper.

But it goes as hacks go: They live the longest. (Also, not so many users in total. Just a (sub) set of opers). So i bet it will run another 10 years, until the next change in irssi that needs some hack added. :)

And yes, this issue can be closed.

**Comment by ChristophBerg** [comment]
Cf. oftc/oftc-tools@b9573d1b77e579b5f639676d9fab085494d158ca.

**Comment by ailin-nemui** [comment]
@ChristophBerg please also reset stty in case of an exception
