### ISSUE TITLE
When reconnecting, authenticate/set vhost before rejoining channels

### ISSUE THREAD

**Issue by Yannik** [irssi/irssi#595]
In case of reconnecting due to temporary lost connection, irssi rejoins channels before authenticating with nickserv using `autosendcmd` (and therefore setting your accounts vhost to hide your own ip/hostmask), effectively openly broadcasting your ip to every channel due to `user xxx at ip has joined #channel` messages. Adding `;wait 2000` to your `autosendcmd` seems to work when initially connecting to the network, but not for rejoining after losing connection.

How can this be circumvented/fixed?

**Comment by dequis** [comment]
In the future please use #irssi in freenode for support questions.

This is an inherent flaw with nickserv, either add a "; wait 5000" to your autosendcmd and hope it's enough, or if the network supports it, switch to SASL which doesn't have this problem.

**Comment by Yannik** [comment]
@dequis I have just added this to my initial posting, `wait 5000` does work for the inital connection, but not for reconnecting after losing connection. Any pointers for this?

**Comment by dequis** [comment]
Works for me. Increase the time.

**Comment by Yannik** [comment]
I did not get it to work by increasing the time. Fortunately the network supports sasl, so switching to that solved this for me right now.

**Comment by mailinglists35** [comment]
i still experience this despite having sasl enabled
