### ISSUE TITLE
Regression in tab completion of setting values (`/set <name> <space><tab>`)

### ISSUE THREAD

**Issue by dequis** [irssi/irssi#609]
Pointed out by vague. 1.0.0 bad, 0.8.20 good. Someone bisect this later.

**Comment by vague666** [comment]
Initially reported by varazir although his problem wasn't exactly the same
jan 06 22:27:59       varazir ┃ befor I could do /set beep_msg_level<space><tab> and current value of that setting was presented 
jan 06 22:28:55       varazir ┃ now I get "-net username"

**Comment by LemonBoy** [comment]
@ailin-nemui is the chosen one, using `wordstar[-1]` as separator [here](https://github.com/irssi/irssi/blob/master/src/fe-common/core/completion.c#L194) is what causes this problem.

**Comment by ailin-nemui** [comment]
thanks
