### ISSUE TITLE
locale: plz make '**' disappear for libc that does not provide default alias to common words such as 'Usage'

### ISSUE THREAD

**Issue by xhebox** [irssi/irssi#617]
Since irssi changed the cli-parser to the one in glib, now if `LANG!=C`, then
```
*****
  -?, --help                  ******

*******
```
the output from strace:
```
open("/share/locale/zh.utf8/LC_MESSAGES/irssi.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
```
The best way to solve the problem and prepare for the possible localization in the future, i think, is add a dump irssi.mo for all languages.
OR, you could just set the 'LANG=C'  before the parser, and get user's default value back after the parser if you don't want to support more languages?

**Comment by ailin-nemui** [comment]
I cannot reproduce this?

**Comment by xhebox** [comment]
@ailin-nemui LANG=zh_CN.UTF-8 is needed, locale-related

**Comment by ailin-nemui** [comment]
I do:

LANG=zh_CN.UTF-8 irssi --help

not ***, just regular 
```
Usage:
  irssi [OPTION...] 

Help Options:
  -?, --help                  Show help options

Application Options:
  --config=PATH               Configuration file location (~/.irssi/config)
  --home=PATH                 Irssi home dir location (~/.irssi)
  -c, --connect=SERVER        Automatically connect to server/network
  -w, --password=PASSWORD     Autoconnect password
  -p, --port=PORT             Autoconnect port
  -!, --noconnect             Disable autoconnecting
  -n, --nick                  Specify nick to use
  -h, --hostname              Specify host name to use
  -v, --version               Display irssi version
```

**Comment by xhebox** [comment]
This file ` //usr/lib/gconv/gconv-modules` is provided as a default alias, but musl has no such file.

**Comment by ailin-nemui** [comment]
so it's a musl bug?

**Comment by xhebox** [comment]
I'm not sure, i will report this to the author of musl. But all other apps provide their default .mo files, this issue still is not meaningless in my view, just for better compatibility, not so bad? :D

**Comment by ailin-nemui** [comment]
Irssi does not use mo, glib will search for mo but should fall back to provided C default

**Comment by xhebox** [comment]
@ailin-nemui thk you for reminding me about the fallback, i've gone through the whole program why it will show me **,  i now know what happened!

First, in `src/fe-text/irssi.c`, args were parsed by glib, and glib try to translate some messages of them. Then it use setlocale(LC..,NULL) to get the env. And for glibc, glib get the correct result because glib will `excute setlocale()` before the parser(i don't know the specific time). 

But, according to the man page:
>On startup of the main program, the portable "C" locale is selected
as default.  A program may be made portable to all locales by
 calling:

so, irssi should not depend on glibc to provide the init for the parser, instead, irssi should move setlocale() in front of the parser, like:
```
	setlocale(LC_ALL, "");
 	args_execute(argc, argv);
```

**Comment by xhebox** [comment]
@ailin-nemui patch: arg parser is affected by setlocale()
```
--- a/src/fe-text/irssi.c	2017-01-03 13:36:46.000000000 +0000
+++ b/src/fe-text/irssi.c	2017-01-03 13:36:46.000000000 +0000
@@ -269,6 +269,17 @@
 	};
 	int loglev;
 
+	/* setlocale() must be called at the beginning before any calls that
+	   affect it, especially regexps seem to break if they're generated
+	   before this call.
+
+	   locales aren't actually used for anything else than autodetection
+	   of UTF-8 currently..
+
+	   furthermore to get the users's charset with g_get_charset() properly
+	   you have to call setlocale(LC_ALL, "") */
+	setlocale(LC_ALL, "");
+
 	core_register_options();
 	fe_common_core_register_options();
 	args_register(options);
@@ -291,17 +302,6 @@
 	SOCKSinit(argv[0]);
 #endif
 
-	/* setlocale() must be called at the beginning before any calls that
-	   affect it, especially regexps seem to break if they're generated
-	   before this call.
-
-	   locales aren't actually used for anything else than autodetection
-	   of UTF-8 currently..
-
-	   furthermore to get the users's charset with g_get_charset() properly
-	   you have to call setlocale(LC_ALL, "") */
-	setlocale(LC_ALL, "");
-
 	loglev = g_log_set_always_fatal(G_LOG_FATAL_MASK | G_LOG_LEVEL_CRITICAL);
 	textui_init();

```
now it works:
```
[xhe@xhe-PC ~]$ irssi --help
用法：
  irssi [选项...] 

帮助选项：
  -?, --help      
```

**Comment by xhebox** [comment]
@ailin-nemui not irssi's bug, sorry to trouble you, but thx for your help!
