### ISSUE TITLE
irssi-1.0.0 perl extension fails to build 

### ISSUE THREAD

**Issue by matzeri** [irssi/irssi#623]
When building on a separate tree from source the 
 `require "../Makefile_silent.pm"`
on several Makefile.PL.in fails to pull the right file.
Attached patch solved issue on cygwin build

[irssi-1.0.0-1.src.patch.txt](https://github.com/irssi/irssi/files/711665/irssi-1.0.0-1.src.patch.txt)

**Comment by ailin-nemui** [comment]
thanks, see #602
