### ISSUE TITLE
/window goto should take incomplete names

### ISSUE THREAD

**Issue by madduck** [irssi/irssi#630]
Since `/window goto foo` should go to the window named "foobar" if that's unique, i.e. one should not be expected to enter the full name (despite tab completion).

Furthermore, maybe `/window goto bar` could go to the window with the "#barcamp" channel, if there is no other window matching /^bar/ and the match with "#barcamp" is also non-ambiguous.

Thank you!

**Comment by madduck** [comment]
Note I just found out that `go.pl` basically does this.

**Comment by vague666** [comment]
If you want to go without scripts then you can use this alias, it also supports going to channels on different networks
`/alias go script exec use List::Util 'first'\; ($$tag,$$chan)=(qq($0) =~ /^#/ ? (Irssi::active_server->{tag}, qq($0)) : (qq($0), qq($1)))\; $$s=Irssi::server_find_tag(first { /$$tag/i } map { $$_->{tag} } Irssi::servers)\; $$s->channel_find((first { /$$chan/i } split ',', $$s->get_channels) // return)->window->set_active if $$s;`

Use it as `/go fr #ir` to go to the first channel matching #ir that's on the first network matching fr, in my case it would be #irssi on freenode
It also understands `/go #ir` to go to the first channel starting with #ir on the active server

**Comment by madduck** [comment]
Especially given https://github.com/irssi/scripts.irssi.org/pull/337, I am closing this issue.
