### ISSUE TITLE
WINDOW GOTO should match case-sensitive

### ISSUE THREAD

**Issue by madduck** [irssi/irssi#633]
I am in the process of trying out a new window management approach in which each of the letter keys combined with `meta` switches to the window by that name, e.g. `meta-h` goes to the window "h".

As this only gives me direct access to 26 windows (in addition to the numbers, of course), I'd like to use uppercase letters too.

However, when I create a window named "H" and add the according `meta-H` keymapping, then `meta-h`  (as well as `meta-H`) takes me to *that* window, i.e. it doesn't respect the case of the window name.

I don't see any reason why the window name needs to be matched case-insentitively, and I think it'd be good if this were to at least be made configurable.

**Comment by ailin-nemui** [comment]
just choose some case-insensitive-unique names...

**Comment by dequis** [comment]
>I don't see any reason why the window name needs to be matched case-insentitively

IRC channels aren't case sensitive.

**Comment by madduck** [comment]
No @dequis, channel and query names are not case-sensitive, but we're quite free to treat windows however we like. Anyway, I don't really care about this nearly enough to try to convince you two… ;)
