### ISSUE TITLE
Use an IRSSI_HOME environment variable?

### ISSUE THREAD

**Issue by OJFord** [irssi/irssi#640]
Requests to use the XDG config directory keep getting shot down (cf. #511; #157; #51)- but how about an environment variable `$IRSSI_HOME` or similar?

It's not going to cause problems for anybody that wants nothing to do with it, since they won't have it set.

XDG people can set it to `$XDG_CONFIG_HOME/irssi`, and anyone else can set it to `wherever/they/like`.

If the environment variable doesn't exist, continue as normal with `$HOME/.irssi`.

I don't mind contributing the PR, but I though I'd get a sounding first.

**Comment by dequis** [comment]
Have you seen `irssi --home=...`?

**Comment by OJFord** [comment]
I had not, thank you!

Adding an alias for `irssi="irssi --home=$XDG_CONFIG_HOME/irssi"` now. I'm not too bothered what the default as long as I can set it to be where I want it 🙂.
