### ISSUE TITLE
Usage issues with multiple-key keybindings

### ISSUE THREAD

**Issue by madduck** [irssi/irssi#644]
Consider a keybinding such as `meta-d-meta-g` —

This has a number of consequences:

1. `meta-d` by itself has become inaccessible
1. Once I pressed `meta-d`, there is no way for me to undo that, i.e. I have to press another key, which then gets swallowed
1. There is no UI-feedback here

All of the above lead to situations where it's quite easy to get Irssi to do something you didn't intend.

Please consider the following proposals:

1. Provide  UI indicator that shows the current buffer if a multikey-binding is in the process of being triggered
1. Allow e.g. `ESC` to clear that buffer. This might just be a bindable action so that it's configurable (e.g. `escape_multikey`)
1. Time-out if a complete sequence isn't entered within $configurable seconds, which has the same effect as `escape_multikey`.

Thanks!

**Comment by dequis** [comment]
#645
