### ISSUE TITLE
autosendcmd are not running on reconnect

### ISSUE THREAD

**Issue by oullah** [irssi/irssi#648]
When irssi reconnects to a server, the `autosendcmd` for that network is not run again. This means that my nickserv reg and other registration activities aren't performed after a reconnect.

**Comment by dequis** [comment]
Uh, works for me, and for many others. If this was broken it would be happening to at least half of the users.

**Comment by oullah** [comment]
It isn't working for me, that is why I filed an issue. What does the team
need to debut the issue?

**Comment by oullah** [comment]
Hmm, looks like the issue is actually that it is using my backup username on reconnect. I'll do more debugging and reopen if necessary.
