### ISSUE TITLE
Unkill bell_beeps setting

### ISSUE THREAD

**Issue by jimenezrick** [irssi/irssi#650]
Regarding: https://github.com/irssi/irssi/issues/524

This is a bit of arcane UNIX convention but it's handy when a terminal program can send the bell signal and you can use that in different ways. I personally let my terminal raise the urgent flag so my window manager notifies there is activity in that window:
```
URxvt.urgentOnBell:     true
```

Are we losing this functionality then? Because I think this is a mistake.

**Comment by vague666** [comment]
bell_beeps is only used when somebody on irc sends an ascii BEL

**Comment by ailin-nemui** [comment]
please do not open issues without giving an actual use case

**Comment by jimenezrick** [comment]
Ah ok, I see my confusion now, this doesn't make sense, closing.
