### ISSUE TITLE
Problem to parse options with captial letters with Irssi::command_parse_options

### ISSUE THREAD

**Issue by varazir** [irssi/irssi#651]
Hello, 

I have this code in my script 

```perl
command_set_options('join_msg' => '+title +deviceId +deviceIds +deviceNames +url clipboard +smsnumber smstext +priority noencrypt +tasker text debug');

my ($join_args, $join_rest) = Irssi::command_parse_options('join_msg', $data);

ref $join_args or return 0
```

It doesn't return a error if the options has a uppercase like above. 
If I change the options to lowercase I get a error if the +options are missing a argument

IRSSI: Client: irssi 1.0.1 (20170203 2046)

data dump 
https://gist.github.com/varazir/03ac68bba36c197def700cbb66116fcc

**Comment by LemonBoy** [comment]
I'm still not sure about what the problem is here, can you show how you're invoking `join_msg` and also what you're seeing and what you expect it to show?

**Comment by varazir** [comment]
Close this, it's working as it should now.

**Comment by LemonBoy** [comment]
Perhaps you're hitting the problem #652 solves where `/join_msg -deviceNames -text` shows a warning about the missing argument but `/join_msg -text -deviceNames` doesn't (and `deviceNames` is set to `''`) in the hash.

**Comment by varazir** [comment]
I build a workaround in my script. checking that the argument isn't 0  length
