### ISSUE TITLE
Run on MSYS2 with Perl 5.24 failed

### ISSUE THREAD

**Issue by duytrung** [irssi/irssi#657]
Hi, 

I tried to use the IRSSI in MSYS2 for windows using "pacman -S irssi" to install. The installation was successful but I could not run the program as it said the file perl dll was not loaded. Perl was installed in the MSYS2 but newer version. How can I link the newer dll to irssi.

Thanks

**Comment by dequis** [comment]
You're using this thing, right? http://www.msys2.org/

Bugs for their packages have to be reported here https://github.com/alexpux/msys2-packages/issues

**Comment by ailin-nemui** [comment]
@duytrung does it work now

**Comment by dequis** [comment]
Going to assume it's fixed, the linked ticket is closed with a new upload, and the comment that closes it has a +1 reaction from OP.
