### ISSUE TITLE
Twitch IRC messages outputted into status window but not channel window

### ISSUE THREAD

**Issue by Svenskunganka** [irssi/irssi#674]
Joining a channel on Twitch outputs the messages to the status window and not the channel window.

Here's how the messages are displayed in the status window

```
21:52 [Twitch] -!-
@badges=broadcaster/1;color=#FF0000;display-name=Svenskunganka;emotes=;id=c7bc0b1a-786f-4859-9a8c-69d7d30a68f3;mod=0;room-id=26559750;sent-ts=1489438344162;subscriber=0;tmi-sent-ts=1489438347003;turbo=0;user-id=26559750;user-type= :svenskunganka!svenskunganka@svenskunganka.tmi.twitch.tv PRIVMSG #svenskunganka :test
```

And the message (which is the string `test`) should show up in the channel but it doesn't. Everything else works fine in the channel, like `/names` and sending messages, but *receiving* messages does not show up.

### To reproduce:
1. Create an account on https://twitch.tv
2. Use this tool to get an OAuth token: http://twitchapps.com/tmi/ (should look something like `oauth:abcdefghijklm1234...`)
3. Add Twitch server to Irssi (take note to the capabilities negotiation & oauth token)
```
/network add -autosendcmd '/^quote CAP REQ :twitch.tv/membership twitch.tv/tags twitch.tv/commands Twitch'
/server add -network Twitch irc.chat.twitch.tv 6667 oauth:abcdefgh12345
```
4. Make sure your nick is the same as your Twitch username.
5. Head over to your web chat at https://twitch.tv/username/chat (replace `username` with yours)
6. Conect to your channel:
```
/connect Twitch
/join #username
```
7. Write something in the web chat. It should not show up in the channel window in Irssi but in the status window above.

I'm not sure if this is a bug with Twitch IRC servers or Irssi or just a simple configuration issue, but I've been looking for hours now not finding anything related.

**Comment by ailin-nemui** [comment]
well do not request tags. irssi doesn't support them

**Comment by Svenskunganka** [comment]
@ailin-nemui Thank you, now I feel really stupid...

For future reference, remove `twitch.tv/tags` from the network: `/network add -autosendcmd '/^quote CAP REQ :twitch.tv/membership twitch.tv/commands Twitch'`

**Comment by skiironmask** [comment]
First time IRSSI user here, I'm having this same issue with all channel text going into the channel window in IRSSI. I'm not requesting tags however and am still experiencing this issue. This may be a configuration issue in my IRSSI but I'm not sure how to separate the status window from the joined channels.
