### ISSUE TITLE
/help connect still says -ssl instead of -tls

### ISSUE THREAD

**Issue by ailin-nemui** [irssi/irssi#684]

**Comment by paultownsend** [comment]
The help file was updated at the same time that SSL was renamed to TLS in 1.0.0, I'm not sure how this has ever been an issue?

**Comment by ailin-nemui** [comment]
https://github.com/irssi/irssi/blob/master/src/core/chat-commands.c#L152

**Comment by paultownsend** [comment]
Ah, my apologies - I hadn't noticed the syntax substituter. I will take a look at this one.
