### ISSUE TITLE
Windows malfunction, cannot navigate to previous/next window consistently

### ISSUE THREAD

**Issue by ailin-nemui** [irssi/irssi#689]
GLib 2.46

reported by @dhduvall

he cannot navigate through windows with Ctrl-N/Ctrl-P or otherwise.
window_refnum_next returns the current refnum, except for windows 2 and 7 where it actually works.

**Comment by ailin-nemui** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=755496

**Comment by dhduvall** [comment]
I can confirm that patching glib2 with https://git.gnome.org/browse/glib/patch/?id=2d7817887a9f0624f73492d04b2a992545f0beb9 does indeed solve the problem. Thanks!
