### ISSUE TITLE
[Can't assign requested address : 52.193.79.145]

### ISSUE THREAD

**Issue by LdBeth** [irssi/irssi#691]
when I run `/server irc.rizon.net` I got this error message:
```
00:51 -!- Irssi: Looking up irc.rizon.net
00:51 -!- Irssi: Connecting to irc.rizon.net [104.155.215.37] port 6667
00:51 -!- Irssi: Unable to connect server irc.rizon.net port 6667 [Can't assign requested address: 52.193.79.145]
```

But  something like `/server 104.155.215.37` can establish connection successfully.

Info:
```
irssi: stable 1.0.2 (bottled), HEAD
OS: Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64 (macOS 10.12.4)
Scripts: adv_windowlist.pl dim_nicks.pl@     splitlong.pl
```

**Comment by LemonBoy** [comment]
Uhh, this happens because something errors out with a `EADDRNOTAVAIL`, did you set the `own_host` field for the rizon chatnet?

**Comment by LdBeth** [comment]
Right. The port is in `TIME_WAIT` stat. And after restarted machine I get this worked.
