### ISSUE TITLE
output of any CAP command not shown

### ISSUE THREAD

**Issue by ailin-nemui** [irssi/irssi#704]
like cap ls etc.

**Comment by ailin-nemui** [comment]
there is a `cap.pl` script

**Comment by LemonBoy** [comment]
That's a design decision, all your CAPs are belong to the irssi api we expose.
If one wants to list all the supported CAPs a simple alias suffices:
`CAP = "script exec print 'Supported CAPs: ' . join(', ', Irssi::active_server->{cap_supported}->@*)";`

**Comment by dequis** [comment]
Ew no. We just forgot the `fe-` part of sasl, hook their signals and print stuff

**Comment by ailin-nemui** [comment]
it may have been a design decision but I disagree. we should show the output of /cap ls -- but we can hook it like we do for the internal WHO/BANLIST/etc functions so that it is not output during the automated connection/negotiation (where the cap details are really supposed to be handled by irssi)
