### ISSUE TITLE
24-bit colours don't seem to reset properly

### ISSUE THREAD

**Issue by darac** [irssi/irssi#710]
I'm trying to write a theme that mimics the "Powerline" system. I have a [working version in 16-colour mode](https://github.com/darac/irssi-powerline), but I have been [asked](https://github.com/darac/irssi-powerline/issues/9) to extend it to 256-colour or 24-bit colour mode.

So, I have rearranged my theme to pre-define the colours, which I can then call on in the abstracts. The problem I'm having is that in 24-bit mode, I can't seem to switch from black-on-yellow to yellow-on-default without a blank space in between.

https://gist.github.com/darac/bed7e46141db6f0def5b44c9228a6796 is a minimal theme in 16-colour mode which *only* styles `ownmsgnick` (so it will look a little odd). This produces a correct line (timestamp in black-on-white, then a white-to-yellow chevron, then user mode in white-on-yellow, then nick in black-on-yellow, then a yellow-to-default chevron, then the message).

https://gist.github.com/darac/2d0465588d91197741866bac5efd6094 is the same theme in 24-bit-colour mode. The issue I have is on the last chevron. Where I have `{solf_yellow }`, this should produce a yellow-to-default (transparent) chevron. However, it *only* does so if there is (unstyled) text beforehand. That is, abutting the expandos doesn't seem to work correctly.

For reference, I am running:
 * "irssi 1.0.2-1 (20170310 1741)" with `colors_ansi_24bit = "yes";`
 * inside tmux 2.3 (inner `TERM=tmux-256color`, Tc bit added to terminfo)
 * inside mintty 2.7.4 (outer `TERM=xterm-256color`)

which should give me full 24-bit colour support, I think.

I'd appreciate if you could confirm if this is a bug in irssi, or in my theming code.

**Comment by ailin-nemui** [comment]
fun, seems to be a bug

**Comment by ailin-nemui** [comment]
can you try the proposed patch?

**Comment by darac** [comment]
> can you try the proposed patch?

Yes, that fixes it. Thank you for the quick response.
