### ISSUE TITLE
Warnings on start up: invalid time '-1'

### ISSUE THREAD

**Issue by copywrong** [irssi/irssi#716]
After upgrade to v1.0.3, these warnings showed up:
```
WARNING **: settings_get_time(server_reconnect_time) : Invalid time '-1'

WARNING **: settings_get_time(server_connect_timeout) : Invalid time '-1'

Irssi: warning settings_get_time(lag_max_before_disconnect) : Invalid time '-1'
```
The latter warning is shown without interruption.

![bug](https://user-images.githubusercontent.com/6815768/26936922-88b43ba2-4c5f-11e7-8f4f-b29e7fe9521c.png)

Is there a way to disable these settings? "-1" used to work.

**Comment by ailin-nemui** [comment]
I'm afraid I introduced this bug into irssi 1.0.3 when merging #706 and would recommend you revert this patch on top of 1.0.3 if you depend on the now broken functionality https://github.com/irssi/irssi/commit/d5bdf00ba6f3125e8348d3aed02667c71c8d2ccf 
until we fix this bug.
