### ISSUE TITLE
simplifying irssi

### ISSUE THREAD

**Issue by wavecollapser** [irssi/irssi#724]
i would like to see:
 No version number in top of irssi main screen on launch
no irssi asciiart, it takes the fun away of making your own ascii art... over sensitation to ascii art whe nyou see it every day, 10 times a day...
no irssi homepage url or text on startup in console

zero text there

just irssi in top left corner

do i have to compile my own to get it like i want it. Oldschool.

**Comment by dequis** [comment]
`/help statusbar`. `/help format`, edit the theme file

**Comment by wavecollapser** [comment]
it seems to be hardcoded. I skimmed both these now. Nothing found. Maybe I overlooked it, there were many lines, but tried double reading them.

It is the status window, irssi ascii art... seems hardcoed, no?

**Comment by vague666** [comment]
Edit the config for some of the statusbar items

**Comment by dequis** [comment]
The ascii art banner is not in themes etc, but it's not shown if there are servers configured to automatically connect. Everything else you mentioned is in statusbar, formats, or the theme file.

**Comment by ailin-nemui** [comment]
maybe we could add a #define to disable the banner, but that would also mean you need to compile it.. so for now just remove it from src/fe-text/irssi.c
