### ISSUE TITLE
tab completion miscounts characters 

### ISSUE THREAD

**Issue by ailin-nemui** [irssi/irssi#752]
report by wodim

> if you type (| is the caret)

> ññññññññ | hello

> and type the first letters of a nick and  then tab, the caret moves to the end of the line
> instead of staying at the end of the nick

**Comment by LemonBoy** [comment]
I guess this happens in `key_completion` because `pos` is a byte offset and, from what I can see, `gui_entry_set_pos` accepts a offset counted in the ucs4 array.
