### ISSUE TITLE
ncurses/terminfo 6.0-20170729 broke statusbar bg drawing in some terminals

### ISSUE THREAD

**Issue by dequis** [irssi/irssi#753]
Most likely not our fault but putting this here so it's not forgotten. Arch linux (which bundles ncurses and terminfo) got an update of the ncurses package a couple of weeks ago, so we might start seeing this more often.

It looks like this (note the background color of the statusbar is not all blue)

![](http://dump.dequis.org/r4bP-.png)

Reported by:

* mefistofeles - yakuake and konsole with `TERM=xterm-256color`
* aftix - st, termite and urxvt with `TERM=xterm`
* ville - left the channel before mentioning what terminal

Doesn't happen to:

* Most things that aren't `TERM=xterm`, like
    * urxvt with `TERM=rxvt-unicode`
    * st with `TERM=st`
    * screen or tmux
* The real xterm or uxterm with `TERM=xterm`

It's mostly about the `TERM=xterm` definition in terminals that aren't exactly xterm. That value seems to be the default for konsole, in other cases that's done because the terminfo entry is not available in all servers.

I bisected and found that 6.0-20170722 is the last good release and 6.0-20170729 is the first bad release

Changelog for that ncurses version: http://invisible-island.net/ncurses/NEWS.html#t20170729

Diff of that version against the previous one: https://github.com/ThomasDickey/ncurses-snapshots/commit/8a51b044a723e15adb3460c362831d90d17df4b8

**Comment by ailin-nemui** [comment]
I tried, gnome-terminal  also does not emulate xterm properly

**Comment by josephbisch** [comment]
FWIW, I also experience this with gnome-terminal and `TERM=xterm-256color`, though Nei already mentioned gnome-terminal.

**Comment by ailin-nemui** [comment]
for gnome-terminal try TERM=gnome-256color or TERM=vte-256color

**Comment by josephbisch** [comment]
Thanks, both work.
