### ISSUE TITLE
The /statusbar documentation is bad

### ISSUE THREAD

**Issue by dequis** [irssi/irssi#758]
The whole thing is just not great at explaining how statusbars and statusbar items work, it's not helpful if you don't already know how to manipulate them.

The existing text has some conceptual errors too. Most glaring mistake is that `/STATUSBAR <name> ADD <item>` does not actually add statusbars, but items. I think enabling means adding statusbars, disabling means removing, unless it's a builtin statusbar

There's more text here https://irssi.org/documentation/startup/#statusbar - certainly better than the /help text.

A quadpoint-style illustrated explanation in a separate page of the website would definitely be cool.

Also the process of writing these docs will highlight what parts of statusbars themselves are bad.

**Comment by ailin-nemui** [comment]
is this fixed now?

**Comment by dequis** [comment]
Yeah, I was asking a bit too much in the description, that PR is good enough
