### ISSUE TITLE
Assertion failure on bitlbee server using “self messages”

### ISSUE THREAD

**Issue by corsac-s** [irssi/irssi#759]
Hi,

[first, sorry for hijacking issue #528]

I'm using irssi on a bitlbee server (IRC to XMPP gateway). I recently updated to Debian Stretch on both sides (so irssi 1.0.2 and bitlbee 3.5.1) and I'm now experiencing some assertion failures in irssi.

Bitlbee supports so-called “self messages”, where messages from yourself are also copied to you, so all messages end up on all clients (see https://wiki.bitlbee.org/SelfMessages).

In irssi, it somehow triggers a wrong code path. Windows 1 has the following output:

```
[17:23:23] -!- Irssi: critical privmsg_get_query: assertion 'nick != NULL' failed
[17:23:23] -!- Irssi: critical query_find: assertion 'nick != NULL' failed
[17:23:23] [jabber] [msg()] test
```

and the rawlog looks like:

```
>> :Corsac!yap@localhost PRIVMSG test :test
```
for a message sent using a different client (gajim on my desktop) to the user 'test' in my roster list.

**Comment by dequis** [comment]
Yeah, that error is definitely different from the other ticket.

Can't repro.

Try with a clean profile, `irssi --home=~/.irssi-test`

**Comment by corsac-s** [comment]
Ok, sorry for the wrong report. It's indeed linked to a script (autorealname) I had. Sorry for that, I'm closing the bug and will report to the script author.
