### ISSUE TITLE
ignore overwrites

### ISSUE THREAD

**Issue by swiniopas** [irssi/irssi#78]
I don't know if I'm missing something here (new user), but after ignoring, say,  messages that contain 'lol' only like this: /ignore -regexp -pattern "^[lL][oO][lL]$" * PUBLIC, when trying to /ignore * JOINS PARTS QUITS, the two entries get merged without the regexp pattern and I end up ignoring all public messages. If I add the ignore rules in opposite order or edit config manually it seems to work fine.

**Comment by ailin-nemui** [comment]
@swiniopas would you be interested in testing that patch?

**Comment by ailin-nemui** [comment]
please reopen if this is still an issue in 0.8.18-beta2 or later
