### ISSUE TITLE
IRSSI sends user's real name to all joined servers by default (originally: real_name defaults to actual name on OSX)

### ISSUE THREAD

**Issue by softwareengineerprogrammer** [irssi/irssi#785]
This is a heinously bad default. It's equivalent to your web browser sending a header with your actual name to every site you visit, but worse. I visited a server/channel where I would have *strongly* preferred nobody know my real name (as I would for practically any IRC channel/server,  but *especially* this one), yet discovered to my extreme dismay that `/whowas` revealed it! How on earth is this the default??!

**Comment by dwfreed** [comment]
Irssi simply uses the gecos field for the current user as the default.  (The IRC realname field is also variously referred to as the gecos field.)  This is completely independent of the OS used to run irssi, and so you'd see the same behavior on Linux if your real name is set as the gecos for your user.  This behavior is as intended, and I find it highly unlikely to change.

**Comment by softwareengineerprogrammer** [comment]
Here's a suggestion: when starting `irssi` for the first time, include a prompt that says "By default irssi will send your real name to every IRC server you connect to? Press 1 to change this behavior." What percentage of users do you think would press 1?

**Comment by blakjaknz** [comment]
Just blasted my real name across a large IRC network without really intending to. It'd be nice to see this behaviour change.

**Comment by vague666** [comment]
@blakjaknz this is shown on first start of irssi.

<img width="1078" height="674" alt="Image" src="https://github.com/user-attachments/assets/d7aa5338-3c5e-465b-a8f2-e3190c32e041" />

It's important to pay attention

**Comment by blakjaknz** [comment]
"it's important to pay attention" wasn't necessary.  I've been running irssi on servers for 20-some years so out of habit I start irssi with -c and I don't see irssi's startup screen. Further - I run much older irssi versions than you do, thanks to Ubuntu LTS and debian oldoldstable being my current breeds.

Your post did prompt me to go dig out https://irssi.org/documentation/settings/ which ... wasn't entirely helpful.. but I did then look at 'man irssi' which showed me the --config option which told me what the default config file was and what do you know, the fields are configurable there, so yes, I can edit the values.

The original post I found here talks about _default_ behaviours and mine was a brand-new installation which had picked up the real name from my passwd file and used it to set the value of real_name - which is indeed, dumb as a default in almost all cases. 
And I don't know if in my 20+ years of using irssi i've ever had to modify the default config file before today.

So for anyone else who picks up on this thread - ensure you modify your ~/.irssi/config file before you connect to anything where this _default_ behaviour is not ideal ??

Cheers.
