### ISSUE TITLE
/hilight generating garbage when passed with multiple -network parameters

### ISSUE THREAD

**Issue by AstroSnail** [irssi/irssi#787]
EDIT: the bug turns out to be unrelated to the number of `-network` parameters passed, read comments below.

---

I haven't tested whether this happens only with `/hilight` and only with `-network`.

I wanted to set a hilight on two networks, and instead of passing the networks comma-separated in one `-network` parameter, I unwittingly passed two `-network` parameters, and irssi crashed.

_Uh oh_

I reopened irssi and ran the command again, and this time irssi didn't crash, but the echo of the command contained garbage in the `-network` parameter.

Found on irssi v1.0.5

Here I run the same command shown on the input bar a number of times.
![2017-11-03-123839_swaygrab](https://user-images.githubusercontent.com/15970994/32374711-c3b1c746-c096-11e7-8be5-b9a82520281f.png)

**Comment by josephbisch** [comment]
Can't reproduce it on v1.0.5. Seems for me, it just uses the last `-network` parameter specified and I don't get any crashes or displaying of garbage. Maybe there is something about your irssi config that explains why you get this issue, but I'm not able to reproduce it.

**Comment by AstroSnail** [comment]
OK, it indeed appears to be something in my config, I tried a fresh config and it didn't happen, and copying the old config to it again crashed with
> *** Error in `irssi': double free or corruption (fasttop): 0x0000558c553e8a30 ***
> Aborted (core dumped)

I'll try to make a minimum config that exibits this bug

**Comment by josephbisch** [comment]
Since it says `Aborted (core dump)`, you should have a file named `core` or `core.1234` where 1234 is the pid of the irssi instance that crashed. You can see [the crash.txt document](https://github.com/irssi/irssi/blob/master/docs/crash.txt) for how to get a backtrace, which may be helpful to allow us to see where the crash is actually occurring. Though if it isn't a build with debug symbols that might not be too informative.

Here are the relevant steps from crash.txt, once you find the core file.

```
 gdb irssi core
 set logging file bt.log
 set logging on
 bt
 set logging off
 quit

Provide the bt.log file.
```

**Comment by AstroSnail** [comment]
I have a fairly minimal crash case now, the config only contains
```
hilights = (
  {
    text = "@AstroSnail";
    nick = "yes";
    fullword = "yes";
    servertag = "AstroZNC-BitlBee,BitlBee";
  }
);
```
and I run
`/hilight -network BiltBee @AstroSnail`

**Comment by josephbisch** [comment]
Thanks reproduced it.
