### ISSUE TITLE
Web-client

### ISSUE THREAD

**Issue by skyway22** [irssi/irssi#798]
Nowadays i'm trying to find a confortable solution for my irc needs.
Irssi has been the greatest, untill i bought my Raspberry Pi and decided to host my own irc client.
Options like [The Lounge](https://www.google.ro/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&cad=rja&uact=8&ved=0ahUKEwiS5cWuqITYAhXHLVAKHWuVAuYQFgheMAM&url=https%3A%2F%2Fgithub.com%2Fthelounge%2Flounge&usg=AOvVaw1UwOrvks8Yu8F7-Dna20u-) or [Shout](https://www.google.ro/url?sa=t&rct=j&q=&esrc=s&source=web&cd=7&cad=rja&uact=8&ved=0ahUKEwib1bDBqITYAhXDI1AKHbpuDnkQFghjMAY&url=http%3A%2F%2Fshout-irc.com%2F&usg=AOvVaw2QIHz1rE89zdTha09jnoed) or [Glowing Bear](https://www.google.ro/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiayPDVqITYAhXHmLQKHXHYBZUQFggnMAA&url=https%3A%2F%2Fgithub.com%2Fglowing-bear%2Fglowing-bear&usg=AOvVaw1KwFm4yxw9ynxizmaHRxPl) have been taken into consideration. Either one looks great, but none of them have the skills that irssi has, or the functionality. Maybe it's time you guys take web-client into consideration? Some initial projects have been made by a guy [here](http://wouter.coekaerts.be/webssi/).. who knows, maybe this will came to life! 
Have a nice day.

**Comment by skyway22** [comment]
some details about the package? I see it's glowing bear.. But need some advice in connecting

**Comment by ailin-nemui** [comment]
after unpacking the file, e.g into ~/.irssi/scripts, `/run teddy-nu` from inside irssi and connect to the address it indicated (http://localhost:9001). Make sure the form values in the browser match (localhost and port)

**Comment by skyway22** [comment]
```8:44 [teddy]
18:44 ipw_cert = 
18:44 ipw_clientdata = 
18:44 ipw_connectmsg_delay = 10min
18:44 ipw_custom_xform = 
18:44 ipw_dehilight = ON
18:44 ipw_docroot = /home/rock64/.irssi/scripts/teddy/client
18:44 ipw_enable_quit = OFF
18:44 ipw_host = localhost
18:44 ipw_key = 
18:44 ipw_password = ****
18:44 ipw_port = 9001
18:44 ipw_rawlog = ON
18:44 ipw_ssl = OFF
18:45 -!- Irssi: Script teddy-nu not found
18:45 -!- Irssi: Script teddy_nu not found
```
Loaded it manually but, don't find anything on my url..

**Comment by ailin-nemui** [comment]
should be http://localhost:9001

but normally you should have a message such as
-!- teddy: 
Server available at http://localhost:9001.

on screen...

**Comment by skyway22** [comment]
```20:10 -!- Irssi: Loaded script teddy_nu
20:10 -!- teddy: 
20:10 Server available at https://localhost:9001.```
Still no go! but my irssi seems to make some troubles, maybe it's that.

**Comment by ailin-nemui** [comment]
I would first try with /set ipw_ssl off. and maybe you're firewalled? are you running irssi on the same computer as where you are trying to open the web site?

**Comment by skyway22** [comment]
No, irssi is running on rock64 in LAN. So firewall is out. I'll try ipw_ssl off
