### ISSUE TITLE
irssi fails to close when launched embedded in a terminal

### ISSUE THREAD

**Issue by ghost** [irssi/irssi#828]
`uxterm -e irssi`

![output2](https://user-images.githubusercontent.com/11262717/35299003-3ae59766-0084-11e8-9181-837734e15987.gif)

**Comment by dequis** [comment]
So this is urxvt is sending SIGHUP (and nothing else) and irssi reloads config on SIGHUP. I don't know what to say here. Maybe urxvt should be trying a bit harder?

**Comment by hhiru** [comment]
I'm sorry, I misspelled. I meant uxterm

**Comment by dequis** [comment]
Maybe uxterm should be trying a bit harder?

**Comment by ailin-nemui** [comment]
works fine in my uxterm, I just tried. maybe it's urxvt after all? otherwise it seems to be specific to your system and not related to irssi. HUP to irssi -> reload config, that works as intended. but your "x" should not send HUP (probably)

**Comment by ailin-nemui** [comment]
`uxterm -e irssi` indeed "x" sends sighup. however, from irssi perspective it is working as intended, hup -> reload config.

**Comment by ailin-nemui** [comment]
maybe we should change that or offer a setting. can't seem to reliably rewire signals from scripts

**Comment by ailin-nemui** [comment]
proposed solution: /set quit_on_hup ON/OFF

**Comment by Pinguin1234** [comment]
I am working on it in PR #1169 .

**Comment by Pinguin1234** [comment]
I think this could be closed now.

**Comment by ailin-nemui** [comment]
thanks @Pinguin1234
