### ISSUE TITLE
Add <Shift><Tab> completion

### ISSUE THREAD

**Issue by g-elfling** [irssi/irssi#829]
Add <Shift><Tab> completion because pressing only `<Tab>` to complete the commands is allowed. `<Shift><Tab>` is not allowed, it doesn't do anything. For example in `/q<Tab>` cycles through commands `/query`, `/quit`, `/quote`, and `/Q`. So if one would type `/qu<Tab>` to complete to `/query` and then press `<Shift>` to cycle next to `/quit`. After that pressing `<Shift><Tab>` it would complete back to `/query`.

**Comment by ailin-nemui** [comment]
in fa
