### ISSUE TITLE
Freedesktop Base Directory Compile Flag

### ISSUE THREAD

**Issue by SoniEx2** [irssi/irssi#847]
I'd like a compile flag to enable freedesktop base directory compliance.

**Comment by vague666** [comment]
Nothing stops you from starting irssi with --home ~/.config/irssi

**Comment by SoniEx2** [comment]
That's not what it's for.

My distro already has `python` = 3, for example. It would be nice to have XDG as the default, too, even if the official devs and every other distro would prefer non-XDG by default.

**Comment by ailin-nemui** [comment]
it's more complicated, .irssi would have to be split into local/share, config and cache

**Comment by ailin-nemui** [comment]
Duplicate of #51  #157  #511

**Comment by SoniEx2** [comment]
Yes, so get a compile flag.
