### ISSUE TITLE
Conform to popular behavior when joining many channels

### ISSUE THREAD

**Issue by spaghetti2514** [irssi/irssi#879]
I've recently gotten the opportunity to test many different irc clients against a bot that joins clients to thousands of channels at once. Nearly every client responds to this by locking up, failing to continue drawing its UI, and eventually crashing. This behavior is so common among irc clients that it is undoubtedly a de facto standard

However, irssi does not conform to this behavior, and instead opts to gracefully handle all the joins without crashing or disconnecting. I request that this behavior be changed to more closely match that of other common clients.

**Comment by dequis** [comment]
lol
