### ISSUE TITLE
New release including OTR 

### ISSUE THREAD

**Issue by varac** [irssi/irssi#881]
It would be great to have a new release that includes the [merged OTR plugin](https://github.com/irssi/irssi/issues/196). Thanks !

**Comment by ge-fa** [comment]
Yeah... :)

**Comment by claucece** [comment]
Completely agree on this ;)

**Comment by vague666** [comment]
The OTR code still has problems with dcc chats which would be great to have fixed before including it in a release, see https://github.com/irssi/irssi/issues/872

**Comment by anarcat** [comment]
@vague666 i don't know if I would block on such a corner case, personally - I know I haven't used DCC chat in ages and I don't quite see the use case here... it probably never worked with the contrib plugin anyways, so just getting this out the door would be a great improvement already...

**Comment by ailin-nemui** [comment]
note that this is mostly "just" the contrib plugin, now included

**Comment by varac** [comment]
I didn't even know what [DCC chats](https://en.wikipedia.org/wiki/Direct_Client-to-Client) were up till now. Agree with @anarcat that it would be nice to fix this after a release.

**Comment by ge-fa** [comment]
What @varac said..

**Comment by dequis** [comment]
...did someone post this to HN or something? Weird amount of activity for an issue.

**Comment by ahf** [comment]
I'm not convinced that the DCC issue is a blocker either :-) I agree that it should be fixed though.

**Comment by anarcat** [comment]
@dequis no one is discussing Signal yet, so I'd say HN is unlikely. :p

**Comment by wilhelmy** [comment]
Is it going to be enabled by default in autoconf?

**Comment by wilhelmy** [comment]
Also where do I send the thank-you beers?

**Comment by traumschule** [comment]
According to #irssi @ahf works on it, probably #885 is blocking.

**Comment by ahf** [comment]
We have written a bit about the migration path here https://irssi.org/2019/02/12/irssi-1.2.0-otr-migration-path/
