### ISSUE TITLE
Remove background color limitation

### ISSUE THREAD

**Issue by klopsi** [irssi/irssi#882]
As documented in doc/formats.txt, messages specifying bright background colors have them mapped to darker colors:
               foreground (fg)     background (bg)
   -------------------------------------------------------
    0          white               light gray   + blinking fg
    4          light red           red          + blinking fg
    8          yellow              orange       + blinking fg
    9          light green         green        + blinking fg
    11         light cyan          cyan         + blinking fg
    12         light blue          blue         + blinking fg
    13         light magenta       magenta      + blinking fg
    14         gray                black        + blinking fg 
    15         light gray          light gray

It would be welcomed to have a flag to disable this remapping, and instead see foreground and background colors as the message creator intended (and as other clients display them).

Today's git clone, tested on debian linux, 24-bit truecolor x, with lxterm, urxvt, termit, konsole, xfce-terminal.  tput colors shows 256.

**Comment by ailin-nemui** [comment]
what

**Comment by dequis** [comment]
what

**Comment by dequis** [comment]
How does this look for you?

![scrot_gimp](https://user-images.githubusercontent.com/94108/40756205-77547f36-6458-11e8-9909-3e9a7de17f08.png)

Download [this file][1] and `/cat` it or just

    /exec curl -s https://dump.dequis.org/K5DmS.txt

[1]: https://dump.dequis.org/K5DmS.txt

**Comment by klopsi** [comment]
[](https://files.catbox.moe/sbffpv.png)

The colors are mapped as shown in formats.txt
https://files.catbox.moe/sbffpv.png

**Comment by klopsi** [comment]
ah the fix is:
 /set mirc_blink_fix  off
