### ISSUE TITLE
Document and/or automate migration from irssi-otr to builtin

### ISSUE THREAD

**Issue by dequis** [irssi/irssi#885]
> 22:29 < dx> hmm we should probably test the process of upgrading from 1.1 with irssi-otr to git with builtin otr
> 22:36 <+ahf> it requires some manual work in the config files if you want to keep your keys for the networks
> 22:37 <+ahf> irssi-otr uses $nick@$server as key for the mapping between connection and secret key, where the built-in version uses $network as key
> 22:39 < dx> oh. i had no idea
> 22:40 < dx> can't we automate that?
> 22:40 <+ahf> i'm not sure. it uses gcrypt's s-expr like config language iirc
> 22:40 < dx> brutal
>

**Comment by dequis** [comment]
> 14:21 <+ahf> it's the textual strings you need to change
> 14:22 <+ahf> you need to fix your otr.key file's "ahf@chat.freenode.net" to "Freenode"
> 14:22 <+ahf> and the same for your fingerprint files

**Comment by ahf** [comment]
This is documented here now: https://irssi.org/2019/02/12/irssi-1.2.0-otr-migration-path/
