### ISSUE TITLE
/lastlog for numbers is broken

### ISSUE THREAD

**Issue by emilfihlman** [irssi/irssi#887]
Okay so first of all, /lastlog 595 should _not_ dump the last 595 lines. Assuming that is just silly.

Secondly, /lastlog -regexp 595 should absolutely _not_ dump the last 595 lines but use 595 as the regexp. Not having a forced argument for -regexp is absolutely an ux bug.

@ahf opened an issue on this 1.5 years ago here https://github.com/irssi/irssi/issues/558 but that's only for enhancement and doesn't mention -regexp.

**Comment by emilfihlman** [comment]
Not to mention that /lastlog '595' and /lastlog "595" also dump the last 595 lines

**Comment by dequis** [comment]
Please add this in the comments of #558, it really is just a duplicate

**Comment by emilfihlman** [comment]
You need to at least change the label of #558 from enhancement to bug since it _is_ a bug.
