### ISSUE TITLE
/topic after topic is unset still shows topic as set

### ISSUE THREAD

**Issue by horgh** [irssi/irssi#888]
After a topic is unset, running `/topic` shows it as set. It says it is blank but still shows who unset it. I'd expect it to show "No topic set".

Example:

First `/topic`:

```
02:12 -!- No topic set for #test
```

Someone sets a topic:

```
02:12 -!- will__ changed the topic of #test to: test one two
```

Look at it with `/topic`:

```
02:12 -!- Topic for #test: test one two
02:12 -!- Topic set by will__ [~will@192.168.1.6] [Fri Jun 22 02:12:15 2018]
```

Someone unsets it:

```
02:12 -!- Topic unset by will__ on #test
```

Run `/topic` (I would expect it to say "No topic set"):

```
02:12 -!- Topic for #test: 
02:12 -!- Topic set by will__ [~will@192.168.1.6] [Fri Jun 22 02:12:20 2018]
```

Cycle and run `/topic`:

```
02:12 -!- test [~test@192.168.1.6] has left #test []
02:12 -!- test [~test@192.168.1.6] has joined #test
02:12 -!- Irssi: Join to #test was synced in 0 secs
02:12 -!- No topic set for #test
```

Not particularly important, but seems a little weird. I wondered if the server had a bug!

**Comment by ailin-nemui** [comment]
rawlog might help

**Comment by horgh** [comment]
There's not much there:

```
>> :test!~test@localhost TOPIC #test :test one two
>> :test!~test@localhost TOPIC #test :
```

I'd guess it's a bookkeeping thing client side that we could tweak.

**Comment by ailin-nemui** [comment]
is there no difference in the irc protocol between an empty topic and unset topic?

**Comment by horgh** [comment]
I don't think so. RFC 1459 doesn't specify this, but RFC 2812 says:

> If the <topic> parameter is an empty string, the topic for that channel will be removed.
