### ISSUE TITLE
Use GNU Readline for line editing

### ISSUE THREAD

**Issue by ryvnf** [irssi/irssi#889]
Hello!

GNU Readline is a library used for line editing across many command line tools, like bash.

It is very customizable, it is possible to use vi-like bindings in it, and the user can customize their key mappings using the configuration file `~/.inputrc`.

I notice that irssi implements some default bindings from Readline like META-B and META-F, but not others like CTRL-B, CTRL-F, META-U, and many others.

I think it would be cool if irssi could link to Readline and use it for command line editing. That way, irssi does not have to reimplement editing functionality, and the users get access to many line editing bindings which does not exist currently. It will also make irssi more consistent with other command line tools.

**Comment by dwfreed** [comment]
I doubt that Readline plays well with applications that draw the whole screen, and need to know exactly what's going on so they can draw properly (as irssi does).  Furthermore, there would be a licensing conflict with distributing irssi with both OpenSSL (at least until they finish relicensing to Apache 2.0, and irssi can use the relicensed version) and Readline, as Readline is GPL, not LGPL, and lacks the OpenSSL exception.  (This is why Debian's socat package does not link against Readline.)

**Comment by rwuwon** [comment]
As infrequently as I dare use it, I can see Ctrl-B interfering with making text bold (which has a valid use for certain activities such as setting /topics, etc).

**Comment by dequis** [comment]
>I notice that irssi implements some default bindings from Readline like META-B and META-F, but not others like CTRL-B, CTRL-F, META-U, and many others.

You can do some of these things with `/bind`, see `/help bind`, `/bind -list` for available actions and `/bind` for currently used keybindings

^B and ^F can be done with `/bind ^B backward_character` and `/bind ^F forward_character` (neither of them are bound, but as the previous comment says, ^B is normally used for bold on irc). meta-u can be done with `/bind meta-u upcase_word`, which is normally bound to `change_window 17`.

And so on, for every binding you want and isn't in the defaults or is used for something else.

vi mode seems to be possible with https://github.com/shabble/irssi-scripts/tree/master/vim-mode

**Comment by ryvnf** [comment]
Thanks! I will close this issue now. Appears there are valid reasons (both technical and juridical) of why this has not been implemented.
