### ISSUE TITLE
Lines matching NO_ACT ignores are hidden by /window hidelevel HIDDEN

### ISSUE THREAD

**Issue by dwfreed** [irssi/irssi#890]
I have several NO_ACT ignores for various bots.  Between 1.1 and b382bd1, lines matching these ignores have become hidden when /window hidelevel is set to HIDDEN.

**Comment by vague666** [comment]
Only place where that error can stem from comes from this: https://github.com/vague666/irssi/blob/ba2554dd1485259b95b4b37f281c989086b24739/src/core/ignore.c#L84
I can't see anything else that might be the culprit

**Comment by vague666** [comment]
The logic in that #define is tricky
