### ISSUE TITLE
/save replaces symlinks with regular files

### ISSUE THREAD

**Issue by meribold** [irssi/irssi#906]
The `/save` command behaves differently on master (I tested 85df01d1338e759b7cac18414ff98a7dce98e2c4) than in 1.1.1: `/save` now replaces symbolic links in `~/.irssi/` with regular files. The new behavior is annoying for people that keep their dotfiles in a VCS repository and mostly use symlinks in `$HOME`.

8deb6182c692904733544568479035b31fe1007e may be the commit that changed the behavior.

**Comment by meribold** [comment]
I confirmed that b2b1ac670879ed49ebf87acc4e33212a21e8df66 behaves in the same way as 1.1.1 (symlinks are preserved) and that symlinks are replaced in 8deb6182c692904733544568479035b31fe1007e .

**Comment by meribold** [comment]
What do you think @dequis?

**Comment by dequis** [comment]
Welp
