### ISSUE TITLE
security contact email bounces

### ISSUE THREAD

**Issue by coypoop** [irssi/irssi#908]
I get:

This is the mail system at host mx1.forwardmx.io.
...
<exg@irssi.org> (expanded from <staff@irssi.org>): User unknown in virtual
    alias table

**Comment by dequis** [comment]
It's just exg, one of the forward targets, it still forwards to the rest. Someone should fix it though.

@ahf?

**Comment by dequis** [comment]
Speaking of bounces, my reply to you bounced:

>```
><co***@sd*.org>: host mx.sd*.org[205.***.***.***] said: 451 4.7.1 Greylisting in
>    action, please come back later (in reply to RCPT TO command)
>```

So I'll just copy it here:

>They look harmless security-wise, main risk is the compiler optimizing
>stuff away due to undefined behavior. You can send this as a normal
>public PR.
