### ISSUE TITLE
CHANTYPES support

### ISSUE THREAD

**Issue by nyuszika7h** [irssi/irssi#93]
Irssi appears to only treat channels with a prefix of `#`, `&`, `+` or `!` as channels, ignoring `CHANTYPES` from the `005` numeric. This causes issues with ZNC, as the `partyline` module uses `~` as channel prefix to avoid name clashes. ZNC sends the correct `CHANTYPES`, but irssi ignores it.

Here's an example `005` from the server containing `CHANTYPES`:

```
21:35:21 freenode --> :wilhelm.freenode.net 005 nyuszika7h CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=freenode KNOCK STATUSMSG=@+ CALLERID=g :are supported by this server
```

**Comment by dequis** [comment]
Since #248 is merged, I believe this is fixed.

**Comment by ahf** [comment]
Closing.
