### ISSUE TITLE
Perl not loading

### ISSUE THREAD

**Issue by tmczar** [irssi/irssi#950]
Linux Mint. Problem exists on package manager version and on clone/compile version.
Irssi does not recognize perl. Standard command:
`/load /usr/lib/x86_64-linux-gnu/libperl.so.5.22`
Returns enigmatic:
 `Irssi: perl/perl is ABI version 0 but Irssi is version 17, cannot load`

**Comment by dwfreed** [comment]
That's not how you load irssi's perl module.  You want `/load perl`

**Comment by tmczar** [comment]
I'm sorry, i cut the story to short:
`/load perl`
doesn't work as it returns:
`/usr/local/lib/irssi/modules/libperl_core.so: cannot open shared object file: No such file or directory`
Because there is no such file - so i'm loading perl that exists, using method similar to the one in: 
 [https://github.com/falsovsky/FiSH-irssi/issues/57](url)
