### ISSUE TITLE
Perl is really not working

### ISSUE THREAD

**Issue by tmczar** [irssi/irssi#952]
Linux Mint. Problem exists on package manager version and on clone/compile version.
`/load perl`
doesn't work as it returns:
`/usr/local/lib/irssi/modules/libperl_core.so: cannot open shared object file: No such file or directory`
Because there is no such file - so i'm loading perl that exists:
But it doesn't help:
`/load /usr/lib/x86_64-linux-gnu/libperl.so.5.22`
Returns enigmatic:
`Irssi: perl/perl is ABI version 0 but Irssi is version 17, cannot load`

**Comment by ailin-nemui** [comment]
either you forget to run `make install ` or you did not compile the perl module

**Comment by ailin-nemui** [comment]
watch closely the output of `./configure `,at the end it prints a summary

**Comment by dwfreed** [comment]
The `/load` command can only load irssi modules, not arbitrary libraries on your system.  `/usr/lib/x86_64-linux-gnu/libperl.so.5.22` is the perl shared library, which irssi's perl scripting module links against, but irssi is not capable of loading.

**Comment by ailin-nemui** [comment]
you can also try our build service packages, I believe Linux mint is based on some ubuntu? https://irssi.org/download/

**Comment by tmczar** [comment]
Ok. I'm moron. I followed blindly notes on https://github.com/irssi/irssi for development package, and thus forgot about running .configure after .autogen.sh.
Sorry for problems
