### ISSUE TITLE
Can't locate lib.pm:   Permission denied at (eval 8) line 1.

### ISSUE THREAD

**Issue by nickpapadonis** [irssi/irssi#969]
Hi,

I'm launching Mac OSX 10.13.6 homebrew installed irssi and receiving this error message on launch:

Can't locate lib.pm:   Permission denied at (eval 8) line 1.
BEGIN failed--compilation aborted at (eval 8) line 1.

$ irssi -! -v
irssi 1.1.1 (20180213 1256)

Does anyone know whats wrong?  I have the latest homebrew apps installed and perl is up to date. 

Thanks

**Comment by ailin-nemui** [comment]
it certainly sounds like an issue with your Perl installation. Try searching your whole computer for lib.pm and check the permissions of the file and its parent folders

**Comment by rprimus** [comment]
Fri May 28 08:43:17 BST 2021

For those running across this on `macOS` 10.15, ensure:
1.  All directories under `/Library/Perl` have permissions 755
2. All files under `/Library/Perl` have permissions 644

### Details
This situation is caused whan a user (with umask 0077) runs `sudo /usr/bin/cpan` and installs a module.  This creates
directory `/Library/Perl/Updates` with perms 700.
