### ISSUE TITLE
Coverity static analysis scan results

### ISSUE THREAD

**Issue by yarda** [irssi/irssi#981]
Hi,

the following minor problems has been found by the Coverity Scan static analysis:
<pre>
Error: RESOURCE_LEAK (CWE-772): [#def1]
irssi-1.1.1/src/irc/core/irc-expandos.c:140: alloc_fn: Storage is returned from allocation function "expando_cumode".
irssi-1.1.1/src/irc/core/irc-expandos.c:121:17: alloc_fn: Storage is returned from allocation function "g_malloc".
irssi-1.1.1/src/irc/core/irc-expandos.c:121:17: var_assign: Assigning: "cumode" = "g_malloc(2UL)".
irssi-1.1.1/src/irc/core/irc-expandos.c:125:4: return_alloc: Returning allocated memory "cumode".
irssi-1.1.1/src/irc/core/irc-expandos.c:140: var_assign: Assigning: "ret" = storage returned from "expando_cumode(server, item, free_ret)".
irssi-1.1.1/src/irc/core/irc-expandos.c:141: leaked_storage: Variable "ret" going out of scope leaks the storage it points to.
#  139|   
#  140|   	ret = expando_cumode(server, item, free_ret);
#  141|-> 	return *ret == '\0' ? " " : ret;
#  142|   }
#  143|   
</pre>
I think, it should de-allocate ret when returning " ".

<pre>
Error: RESOURCE_LEAK (CWE-772): [#def2]
irssi-1.1.1/src/irc/dcc/dcc-send.c:387: open_fn: Returning handle opened by "open". [Note: The source code implementation of the function has been overridden by a user model.]
irssi-1.1.1/src/irc/dcc/dcc-send.c:387: var_assign: Assigning: "hfile" = handle returned from "open(str, 0)".
irssi-1.1.1/src/irc/dcc/dcc-send.c:396: noescape: Resource "hfile" is not freed or pointed-to in "fstat". [Note: The source code implementation of the function has been overridden by a builtin model.]
irssi-1.1.1/src/irc/dcc/dcc-send.c:428: leaked_handle: Handle variable "hfile" going out of scope leaks the handle.
#  426|   	if (dcc == NULL) {
#  427|   		g_warn_if_reached();
#  428|-> 		return FALSE;
#  429|   	}
#  430|   
</pre>
I think it should close hfile.

Also there is ticket #197 about enabling integration with coverity.

**Comment by ailin-nemui** [comment]
too bad coverity is too stupid in some cases

**Comment by yarda** [comment]
There are usually many false positives in such scans - I filtered them. But for these two cases, are there leaks or aren't? Regarding the first case I cannot see where the ret is de-allocated or stored in case when " " is returned.

**Comment by yarda** [comment]
> There are usually many false positives in such scans - I filtered them. But for these two cases, are there leaks or aren't? Regarding the first case I cannot see where the ret is de-allocated or stored in case when " " is returned.

Ah sorry, got it, it shouldn't happen, but regarding the second case?

**Comment by ailin-nemui** [comment]
ret was never allocated in that case

**Comment by yarda** [comment]
Sure, I got it, sorry for noise. What about the hfile?

**Comment by yarda** [comment]
And the [#def2]? is it false positive or not? If not is it worth to fix?

**Comment by ailin-nemui** [comment]
I believe it's fine, thanks for fixing it. as you can see the branch is marked as warn_if_reached, so it should hopefully never occur in reality but still why not fix it

**Comment by yarda** [comment]
OK, thanks for info, I updated the PR.
