### ISSUE TITLE
"/join channel" works when you have not joined #channel yet. If you have, it stops working.

### ISSUE THREAD

**Issue by RichiH** [irssi/irssi#99]
As requested by my all-time favourite ahf:

12:31:29 < ahf> we have moved to github!
12:31:34 < ahf> just file an issue with a link to bugs.i.o!
12:31:44 < ahf> haven't you read _the_ announcement RichiH
12:31:54 < ahf> I came out as a pokemon furry

http://bugs.irssi.org/index.php?do=details&task_id=581
http://bugs.irssi.org/index.php?do=details&task_id=758

**Comment by ailin-nemui** [comment]
white-space should be trimmed for the call to `channel_find` in `cmd_join`. Patch welcome

**Comment by flaw600** [comment]
I'm confused about this issue. The command goes haywire if there's whitespace?

**Comment by ailin-nemui** [comment]
the special case that makes `/join #channel` do the same as `/window goto #channel` does not work with trailing white space

**Comment by RichiH** [comment]
Yes. And auto completion introduces whitespace when tabbing.

Richard

Sent by mobile; excuse my brevity.

**Comment by KindOne-** [comment]
I use [trigger.pl](https://github.com/irssi/scripts.irssi.org/blob/gh-pages/scripts/trigger.pl) with ```-send_command -regexp '\s+$' -replace ''``` to strip all the trailing whitespaces from commands. #274

**Comment by RichiH** [comment]
Neat, I will steal that.

Does not fix the non-hash join, though.

Richard

Sent by mobile; excuse my brevity.

**Comment by ahf** [comment]
I've sold my soul to @RichiH for getting him to fix things for me elsewhere.

Let this be a note to everyone that even in the open source community we must be able to do under the table negotiations! :-D

**Comment by RichiH** [comment]
Less talking, more fixing.

**Comment by RichiH** [comment]
Less idling, more fixing.

**Comment by dequis** [comment]
I don't know what's going on here but I like this guy.

**Comment by flaw600** [comment]
As do I.

**Comment by RichiH** [comment]
I am myself.

@ahf is the lazy.

**Comment by RichiH** [comment]
That's all? That's what @ahf has been wailing about for _almost ten years_ that it's hard to fix, that he needs proper bug reports in various trackers and body cavities, plus warm milk and a blankie?

Son, I am disappoint.

That being said, the commit does not look as if it fixes the first part of the bug report, merely the latter.

**Comment by dequis** [comment]
>That being said, the commit does not look as if it fixes the first part of the bug report, merely the latter.

Okay cool. Continue torturing @ahf then.

**Comment by ahf** [comment]
<3

**Comment by RichiH** [comment]
As to @ahf , all that's left to say is [this](https://www.youtube.com/watch?v=kxopViU98Xo)

**Comment by ahf** [comment]
https://www.youtube.com/watch?v=SDIWLRvc7gQ

**Comment by RichiH** [comment]
https://www.youtube.com/watch?v=zs2e4SpyXlI

If you want me to play the cool game and close & open this issue repeatedly, I will need more rights to the repo.

**Comment by RichiH** [comment]
Weeeeeeeeeeeeeeeeeeeeeeeeee!

**Comment by LemonBoy** [comment]
doot doot

**Comment by dequis** [comment]
Closing since #357 is merged
